import { C, G6, T, compileWorlds } from "@/content/curriculum/build";
import {
  NCERT_BOOKS,
  ncertBookWorld,
  ncertRef,
} from "@/content/curriculum/ncert-books";

const SANTOOR4_NOTE =
  "Chapter titles match the official NCERT Santoor Grade 4 contents (desa1ps).";

export const ENGLISH_NCERT_WORLDS = compileWorlds([
  ncertBookWorld({
    id: "ncert-g4-santoor",
    title: "Santoor",
    subject: "english",
    category: "Literature",
    grade: 4,
    book: NCERT_BOOKS.santoor4,
    status: "official",
    note: SANTOOR4_NOTE,
    hook: "Grade 4 English literature: land, world, games, and going up high — with listening, speaking, and writing around the texts.",
    chapters: [
      { slug: "together-we-can", title: "Together We Can", about: "Read a text about working together and talk about its message.", skills: ["Retell a key event", "Share a message"] },
      { slug: "the-tinkling-bells", title: "The Tinkling Bells", about: "Enjoy a literary piece and notice sound and feeling in language.", skills: ["Notice a sound word", "Say how it feels"] },
      { slug: "be-smart-be-safe", title: "Be Smart, Be Safe", about: "Read for information and safety ideas in everyday life.", skills: ["Find a safety idea", "Retell in your own words"] },
      { slug: "one-thing-at-a-time", title: "One Thing at a Time", about: "Read a text about focus and talk about habits of attention.", skills: ["Find the main idea", "Connect to own life"] },
      { slug: "the-old-stag", title: "The Old Stag", about: "Follow a story, characters, and a lesson in a tale.", skills: ["Name a character trait", "Sequence events"] },
      { slug: "braille", title: "Braille", about: "Read about Braille and inclusion, then discuss why access matters.", skills: ["Explain what Braille is", "Give a reason access matters"] },
      { slug: "fit-body-mind-nation", title: "Fit Body, Fit Mind, Fit Nation", about: "Read about fitness and wellbeing and talk about healthy habits.", skills: ["Find a key idea", "Share a healthy habit"] },
      { slug: "the-lagori-champions", title: "The Lagori Champions", about: "Enjoy a games story and notice teamwork in the plot.", skills: ["Retell the game story", "Name a teamwork moment"] },
      { slug: "hekko", title: "Hekko", about: "Meet a traditional game through a text and talk about play.", skills: ["Describe the game idea", "Compare with a game you know"] },
      { slug: "the-swing", title: "The Swing", about: "Read a poem or piece about swinging and notice rhythm and images.", skills: ["Notice an image", "Read aloud with rhythm"] },
      { slug: "magical-mountains", title: "A Journey to the Magical Mountains", about: "Follow a journey narrative and describe setting.", skills: ["Describe the setting", "Track the journey"] },
      { slug: "maheshwar", title: "Maheshwar", about: "Read about a place and its people, crafts, or stories.", skills: ["Find a place detail", "Share what makes it special"] },
    ],
  }),
  ncertBookWorld({
    id: "ncert-g5-santoor",
    title: "Santoor",
    subject: "english",
    category: "Literature",
    grade: 5,
    book: NCERT_BOOKS.santoor5,
    status: "official",
    note: "Chapter titles match official NCERT Santoor Grade 5 chapter PDFs (eesa1).",
    hook: "Grade 5 English literature: fun, colour, water, games, and work — with talk, listen, and write around the texts.",
    chapters: [
      { slug: "papas-spectacles", title: "Papa’s Spectacles", about: "Read a humorous family text and talk about the mix-up.", skills: ["Retell the mix-up", "Notice humour"] },
      { slug: "gone-with-the-scooter", title: "Gone with the Scooter", about: "Follow an adventure-like episode and sequence events.", skills: ["Sequence events", "Describe a character"] },
      { slug: "the-rainbow", title: "The Rainbow", about: "Read a nature piece and notice images of colour and weather.", skills: ["Find an image", "Connect to observation"] },
      { slug: "the-wise-parrot", title: "The Wise Parrot", about: "Read a fable-like tale and discuss cleverness and freedom.", skills: ["Retell the turning point", "Say what the tale suggests"] },
      { slug: "the-frog", title: "The Frog", about: "Read about a frog’s life and compare it with other water animals.", skills: ["Find a frog fact from the text", "Compare two animals"] },
      { slug: "what-a-tank", title: "What a Tank!", about: "Read a water/tank text and talk about water in daily life.", skills: ["Find the main idea", "Connect to water use"] },
      { slug: "gilli-danda", title: "Gilli Danda", about: "Enjoy a traditional-game story and describe how it is played.", skills: ["Describe the game", "Notice local play"] },
      { slug: "decision-of-the-panchayat", title: "The Decision of the Panchayat", about: "Read a community-decision story and discuss fairness.", skills: ["Find the problem", "Talk about a fair decision"] },
      { slug: "vocation", title: "Vocation", about: "Read a poem about work and wishing, and talk about its feeling.", skills: ["Notice the speaker’s wish", "Read a stanza aloud"] },
      { slug: "glass-bangles", title: "Glass Bangles", about: "Read about making and wearing glass bangles and the people involved.", skills: ["Follow a making process", "Notice a human detail"] },
    ],
  }),
  {
    id: "ncert-g6-poorvi",
    title: "Poorvi",
    subject: "english",
    category: "Literature",
    grades: G6,
    hook: "Grade 6 English literature: every Poorvi text, not only the five unit titles.",
    ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official"),
    topics: [
      T(
        "ncert-g6-poorvi-fables-folk-tales",
        "Fables and Folk Tales",
        G6,
        "Timeless wisdom through a story, a fable-poem, and a graphic tale.",
        "Read the three texts in this unit and talk about their wisdom.",
        "Unit 1 of Poorvi Grade 6.",
        [
          C("ncert-g6-poorvi-bottle-of-dew", "A Bottle of Dew", G6, "What does Rama Natha learn about hard work?", "Retell the story and its idea about diligence.", "A Bottle of Dew shows that true success comes from hard work, not a magic shortcut.", ["Retell the story", "State the story’s idea"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "A Bottle of Dew" }) }),
          C("ncert-g6-poorvi-raven-and-fox", "The Raven and the Fox", G6, "Why does the raven lose the morsel?", "Read the fable-poem and talk about vanity and flattery.", "The poem-fable warns that pride and flattering words can cost you what you have.", ["Retell the fable", "Name the warning"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "The Raven and the Fox" }) }),
          C("ncert-g6-poorvi-rama-to-the-rescue", "Rama to the Rescue", G6, "How does presence of mind help in the graphic story?", "Follow the graphic tale and discuss quick thinking.", "Rama to the Rescue is a graphic story about presence of mind when facing a challenge.", ["Sequence the events", "Name a clever action"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "Rama to the Rescue" }) }),
        ],
        { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "Fables and Folk Tales" }) },
      ),
      T(
        "ncert-g6-poorvi-friendship",
        "Friendship",
        G6,
        "Friends can be unlikely, prayed for, or found in an ordinary chair.",
        "Read the three friendship texts and talk about loyalty and care.",
        "Unit 2 of Poorvi Grade 6.",
        [
          C("ncert-g6-poorvi-unlikely-best-friends", "The Unlikely Best Friends", G6, "What makes these friends ‘unlikely’?", "Describe the friendship and what holds it together.", "The story explores friendship that crosses an expected divide.", ["Describe the friends", "Find a loyalty moment"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "The Unlikely Best Friends" }) }),
          C("ncert-g6-poorvi-friends-prayer", "A Friend’s Prayer", G6, "What does the speaker wish for a friend?", "Read the poem and talk about the qualities of friendship.", "A Friend’s Prayer puts the hope of friendship into verse.", ["Find the wish", "Read a stanza aloud"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "A Friend’s Prayer" }) }),
          C("ncert-g6-poorvi-the-chair", "The Chair", G6, "What does the chair come to mean in this story?", "Follow the story and discuss belonging and care.", "The Chair is a friendship story built around an everyday object.", ["Retell the story", "Say what the chair stands for"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "The Chair" }) }),
        ],
        { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "Friendship" }) },
      ),
      T(
        "ncert-g6-poorvi-nurturing-nature",
        "Nurturing Nature",
        G6,
        "Trees, birds, and healing spices — nature as teacher and helper.",
        "Read the three nature texts and respond with care for the living world.",
        "Unit 3 of Poorvi Grade 6.",
        [
          C("ncert-g6-poorvi-neem-baba", "Neem Baba", G6, "What gifts of the neem tree does the text share?", "Read about the neem and talk about its uses and respect for trees.", "Neem Baba introduces the neem tree as a living helper in Indian life.", ["Name a neem use", "Show respect for a tree"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "Neem Baba" }) }),
          C("ncert-g6-poorvi-what-a-bird-thought", "What a Bird Thought", G6, "How does the bird’s world grow in the poem?", "Read the poem and notice how the bird’s view of the world changes.", "The poem follows a bird’s widening sense of the world.", ["Find an image", "Describe the change in view"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "What a Bird Thought" }) }),
          C("ncert-g6-poorvi-spices-that-heal-us", "Spices that Heal Us", G6, "Which everyday spice is also a healer in the text?", "Read about healing spices and connect them to home knowledge.", "Spices that Heal Us links kitchen spices to care and Indian knowledge.", ["Name a healing spice", "Connect to home use"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "Spices that Heal Us" }) }),
        ],
        { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "Nurturing Nature" }) },
      ),
      T(
        "ncert-g6-poorvi-sports-wellness",
        "Sports and Wellness",
        G6,
        "A change of heart, a race, and yoga as a way of life.",
        "Read the three wellness texts and talk about effort, fairness, and health.",
        "Unit 4 of Poorvi Grade 6.",
        [
          C("ncert-g6-poorvi-change-of-heart", "Change of Heart", G6, "What changes in the player besides the score?", "Follow the sports story and discuss fairness and feeling.", "Change of Heart is a sports story about attitude as well as the game.", ["Retell the turning point", "Talk about fair play"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "Change of Heart" }) }),
          C("ncert-g6-poorvi-the-winner", "The Winner", G6, "What does winning mean in this poem?", "Read the poem and talk about effort and winning.", "The Winner looks at competition through verse.", ["Find the poem’s idea of winning", "Read a stanza aloud"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "The Winner" }) }),
          C("ncert-g6-poorvi-yoga-way-of-life", "Yoga—A Way of Life", G6, "How is yoga more than a set of poses in this text?", "Read about yoga as a daily way of living well.", "Yoga—A Way of Life presents yoga as wellness, not only exercise.", ["Name a yoga idea from the text", "Connect to a healthy habit"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "Yoga—A Way of Life" }) }),
        ],
        { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "Sports and Wellness" }) },
      ),
      T(
        "ncert-g6-poorvi-culture-tradition",
        "Culture and Tradition",
        G6,
        "India’s people, kites, embroidery, and a national memorial.",
        "Read the four culture-and-heritage texts and notice language of belonging.",
        "Unit 5 of Poorvi Grade 6.",
        [
          C("ncert-g6-poorvi-hamara-bharat", "Hamara Bharat—Incredible India!", G6, "What makes India ‘incredible’ in this text?", "Read about India’s diversity and talk about belonging.", "Hamara Bharat—Incredible India! celebrates the country’s variety.", ["Find a diversity detail", "Share a belonging idea"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "Hamara Bharat—Incredible India!" }) }),
          C("ncert-g6-poorvi-the-kites", "The Kites", G6, "What do the kites carry besides colour?", "Read the kite text and notice festival, sky, and feeling.", "The Kites is a culture-and-play piece from Poorvi Grade 6.", ["Find a kite image", "Connect to a festival"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "The Kites" }) }),
          C("ncert-g6-poorvi-ila-sachani", "Ila Sachani: Embroidering Dreams with her Feet", G6, "How does Ila Sachani stitch her dreams?", "Read the biographical text and discuss skill, courage, and art.", "Ila Sachani: Embroidering Dreams with her Feet is about creating with determination.", ["Retell Ila’s story", "Name a quality she shows"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "Ila Sachani: Embroidering Dreams with her Feet" }) }),
          C("ncert-g6-poorvi-national-war-memorial", "National War Memorial", G6, "What does the memorial ask us to remember?", "Read about the National War Memorial and discuss respect and remembrance.", "National War Memorial is a text of gratitude and national memory.", ["Find a memorial detail", "Write a respectful line"], { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "National War Memorial" }) }),
        ],
        { ncert: ncertRef(NCERT_BOOKS.poorvi6, 6, "official", { chapter: "Culture and Tradition" }) },
      ),
    ],
  },
  ncertBookWorld({
    id: "ncert-g7-poorvi",
    title: "Poorvi",
    subject: "english",
    category: "Literature",
    grade: 7,
    book: NCERT_BOOKS.poorvi7,
    status: "official",
    hook: "Grade 7 English literature: learning together, wit, dreams, travel, and bravehearts.",
    chapters: [
      { slug: "the-day-the-river-spoke", title: "The Day the River Spoke", about: "Read a story that links nature, courage, and the wish to learn.", skills: ["Track the character’s wish", "Discuss a barrier and a choice"] },
      { slug: "try-again", title: "Try Again", about: "Read a poem on perseverance and talk about trying after a fall.", skills: ["Find the poem’s advice", "Read a stanza with feeling"] },
      { slug: "three-days-to-see", title: "Three Days to See", about: "Read Helen Keller’s reflection and discuss the gift of the senses.", skills: ["Find a sensory detail", "Write what you would notice"] },
      { slug: "animals-birds-dolittle", title: "Animals, Birds, and Dr. Dolittle", about: "Read a humorous animal text and notice wit in character and talk.", skills: ["Notice humour", "Describe a character"] },
      { slug: "a-funny-man", title: "A Funny Man", about: "Read a humorous poem and talk about playful contradiction.", skills: ["Find a funny image", "Read aloud for fun"] },
      { slug: "say-the-right-thing", title: "Say the Right Thing", about: "Read a play-like piece about choosing words kindly and wisely.", skills: ["Spot a speech choice", "Role-play a polite line"] },
      { slug: "brothers-great-invention", title: "My Brother’s Great Invention", about: "Read an invention story and discuss creativity and trial-and-error.", skills: ["Sequence the invention attempts", "Talk about trying again"] },
      { slug: "paper-boats", title: "Paper Boats", about: "Read a poem of childhood and imagination on the water.", skills: ["Find an image", "Connect to a memory"] },
      { slug: "north-south-east-west", title: "North, South, East, West", about: "Read a travel/exploration narrative and track places and purpose.", skills: ["Track directions or places", "State the traveller’s purpose"] },
      { slug: "the-tunnel", title: "The Tunnel", about: "Read an adventure story and discuss fear, courage, and setting.", skills: ["Describe the setting", "Find a courage moment"] },
      { slug: "travel", title: "Travel", about: "Read a travel poem and notice movement, curiosity, and wish.", skills: ["Find a travel image", "Read with rhythm"] },
      { slug: "conquering-the-summit", title: "Conquering the Summit", about: "Read a non-fiction climbing account and discuss endurance.", skills: ["Find a factual detail", "Explain a challenge"] },
      { slug: "homage-brave-soldiers", title: "A Homage to Our Brave Soldiers", about: "Read a tribute and discuss gratitude, service, and respect.", skills: ["Find a tribute idea", "Write a respectful line"] },
      { slug: "my-dear-soldiers", title: "My Dear Soldiers", about: "Read a poem of gratitude to soldiers and notice tone.", skills: ["Describe the tone", "Read a stanza aloud"] },
      { slug: "rani-abbakka", title: "Rani Abbakka", about: "Read a graphic/historical story of courage and resistance.", skills: ["Retell a key episode", "Name a quality of courage"] },
    ],
  }),
  ncertBookWorld({
    id: "ncert-g8-poorvi",
    title: "Poorvi",
    subject: "english",
    category: "Literature",
    grade: 8,
    book: NCERT_BOOKS.poorvi8,
    status: "official",
    hook: "Grade 8 English literature: wit, values, mystery, environment, and science curiosity.",
    chapters: [
      { slug: "wit-that-won-hearts", title: "The Wit that Won Hearts", about: "Read a witty narrative and discuss how intelligence solves a problem.", skills: ["Find the witty turn", "Explain the problem it solves"] },
      { slug: "a-concrete-example", title: "A Concrete Example", about: "Read a text that plays with example, meaning, and thinking.", skills: ["Find the example", "Say what it shows"] },
      { slug: "wisdom-paves-the-way", title: "Wisdom Paves the Way", about: "Read a tale where wisdom, not force, opens a path.", skills: ["Track the wise choice", "Contrast force and wisdom"] },
      { slug: "tale-of-valour", title: "A Tale of Valour: Major Somnath Sharma", about: "Read a biographical account of courage and service.", skills: ["Find a factual detail", "Describe a value shown"] },
      { slug: "somebodys-mother", title: "Somebody’s Mother", about: "Read a poem of kindness to an elder and discuss empathy.", skills: ["Find the kind act", "Talk about empathy"] },
      { slug: "verghese-kurien", title: "Verghese Kurien—I Too Had A Dream", about: "Read about a dream that served a community, not only the self.", skills: ["Find the dream", "Link it to community good"] },
      { slug: "case-of-the-fifth-word", title: "The Case of the Fifth Word", about: "Read a mystery and practise inference from clues.", skills: ["List a clue", "Make an inference"] },
      { slug: "magic-brush-of-dreams", title: "The Magic Brush of Dreams", about: "Read a magical tale and discuss wish, art, and consequence.", skills: ["Track the magic rule", "Discuss a consequence"] },
      { slug: "spectacular-wonders", title: "Spectacular Wonders", about: "Read about natural or human wonders and describe them clearly.", skills: ["Find a wonder detail", "Write a clear description"] },
      { slug: "the-cherry-tree", title: "The Cherry Tree", about: "Read Ruskin Bond’s story of growing a tree and patience.", skills: ["Track the tree’s growth", "Discuss patience"] },
      { slug: "harvest-hymn", title: "Harvest Hymn", about: "Read a harvest poem and notice gratitude to land and labour.", skills: ["Find a harvest image", "Describe the tone"] },
      { slug: "waiting-for-the-rain", title: "Waiting for the Rain", about: "Read a farming story about waiting on weather and balance.", skills: ["Find the waiting problem", "Link weather to livelihood"] },
      { slug: "feathered-friend", title: "Feathered Friend", about: "Read a science-fiction story and discuss curiosity and consequence.", skills: ["Find the sci-fi idea", "Discuss a what-if"] },
      { slug: "magnifying-glass", title: "Magnifying Glass", about: "Read a poem of looking closely and talk about noticing.", skills: ["Find a close-look image", "Write a noticing line"] },
      { slug: "bibha-chowdhuri", title: "Bibha Chowdhuri: The Beam of Light", about: "Read a biography of a scientist and discuss curiosity and persistence.", skills: ["Find a scientific contribution", "Describe persistence"] },
    ],
  }),
]);
