import { nounsExperience } from "@/content/curriculum/lessons";
import {
  C,
  G4,
  G45,
  G456,
  G56,
  G6,
  T,
  compileWorlds,
  type WorldSpec,
} from "@/content/curriculum/build";

const ENGLISH: WorldSpec[] = [
  {
    id: "english-nouns",
    title: "Nouns",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "Nouns are the naming words that stories and facts hang on.",
    concepts: [
      C("english-nouns-common-proper", "Common & Proper Nouns", G456, "Why does Delhi take a capital when city does not?", "Tell common nouns from proper nouns.", "A common noun names a kind of person, place, or thing. A proper noun names a particular one and starts with a capital.", ["Spot a common noun", "Spot a proper noun"], { experience: nounsExperience }),
      C("english-nouns-count", "Countable & Uncountable", G45, "Can you say two waters the same way you say two cups?", "Sort countable and uncountable nouns.", "Cups can be counted. Water is usually uncountable, so we say a glass of water.", ["Sort countable nouns", "Use a measure word"]),
      C("english-nouns-collective", "Collective Nouns", G45, "What word names a group of lions?", "Use collective nouns for groups.", "A pride, a flock, and a team name groups. The group is thought of as one unit.", ["Name a collective noun", "Match group to noun"]),
      C("english-nouns-abstract", "Abstract Nouns", G56, "Can you put kindness in a box?", "Identify abstract nouns.", "Abstract nouns name ideas and feelings: honesty, fear, time. You cannot touch them.", ["Spot an abstract noun", "Contrast with concrete"]),
      C("english-nouns-possessive", "Possessive Nouns", G56, "Where does the apostrophe go in the girl's bag?", "Form singular and plural possessives.", "Add 's to a singular noun. For a plural that already ends in s, add only an apostrophe: girls' bags.", ["Write a singular possessive", "Write a plural possessive"]),
    ],
  },
  {
    id: "english-pronouns",
    title: "Pronouns",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "Pronouns stand in so we do not repeat the same name.",
    concepts: [
      C("english-pro-personal", "Personal Pronouns", G4, "Instead of saying Riya three times, what can you use?", "Replace nouns with I, you, he, she, it, we, they.", "Pronouns match the person and number. Riya → she. The children → they.", ["Replace a noun", "Choose he or she"]),
      C("english-pro-possessive", "Possessive Pronouns", G45, "Is mine a noun or a pronoun here: 'The red bag is mine'?", "Use mine, yours, his, hers, ours, theirs.", "Possessive pronouns stand alone. My is a determiner; mine is a pronoun.", ["Use mine/yours", "Contrast my and mine"]),
      C("english-pro-reflexive", "Reflexive Pronouns", G56, "When do we say herself instead of her?", "Use myself, yourself, himself, herself, itself, ourselves, themselves.", "Use a reflexive when the same person does and receives the action: she taught herself.", ["Choose a reflexive", "Avoid a wrong extra myself"]),
      C("english-pro-relative", "Relative Pronouns", G6, "Which word joins 'the book' to 'I borrowed'?", "Use who, which, and that to join information.", "Who is for people. Which/that often add facts about things. The clause hangs on the noun.", ["Join with who", "Join with which"]),
    ],
  },
  {
    id: "english-verbs",
    title: "Verbs",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "Verbs carry the action or the state in a sentence.",
    concepts: [
      C("english-verb-action", "Action Verbs", G4, "What is the doing word in 'The kite flew'?", "Find action verbs.", "An action verb tells what someone or something does: ran, cooked, whispered.", ["Spot an action verb", "Act out a verb"]),
      C("english-verb-main", "Main Verbs", G45, "In 'is running', which word is the main verb?", "Identify the main verb in a verb group.", "The main verb holds the meaning. Helping verbs sit beside it: is running, has eaten.", ["Find the main verb", "Split helper and main"]),
      C("english-verb-helping", "Helping Verbs", G45, "What job do is, have, and will do next to a main verb?", "Name common helping verbs.", "Be, have, do, and will help show time or voice. They are not the whole action by themselves.", ["List helpers", "Build a verb group"]),
      C("english-verb-irregular", "Regular & Irregular Verbs", G56, "Why is the past of go not goed?", "Form regular -ed past and common irregular pasts.", "Regular verbs add -ed. Irregular verbs change: go/went, eat/ate, write/wrote. Learn the common ones.", ["Add -ed", "Use an irregular past"]),
      C("english-verb-state", "Being & Sensing Verbs", G56, "Is 'is' still a verb if nobody is jumping?", "Recognise be, seem, feel, look as verbs.", "Verbs can name a state: is, seems, feels. They still do a verb's job in the sentence.", ["Spot a being verb", "Contrast action and state"]),
    ],
  },
  {
    id: "english-sva",
    title: "Subject-Verb Agreement",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "The verb has to match the subject like partners in a dance.",
    concepts: [
      C("english-sva-simple", "Match Singular & Plural", G456, "Do we say The cats runs or The cats run?", "Make present-tense verbs agree with the subject.", "He/she/it takes -s in simple present: she runs. I/you/we/they do not: they run.", ["Add -s for he/she/it", "Keep the verb for they"]),
      C("english-sva-tricky", "Tricky Subjects", G6, "Does 'A pair of shoes' take is or are?", "Agree with the real subject, not a nearby noun.", "Look at the head noun. A pair is singular. The shoes in the box are plural.", ["Find the head noun", "Choose is/are"]),
    ],
  },
  {
    id: "english-tenses",
    title: "Tenses",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "Tense is how English shows when something happens.",
    topics: [
      T("english-tense-simple-present", "Simple Present", G45, "When do we use play, not is playing?", "Use simple present for habits and facts.", "Use simple present for routines and truths: The sun rises. I walk to school.", [
        C("english-sp-habits", "Habits & Facts", G4, "What tense tells a daily habit?", "Write simple present for habits.", "I eat breakfast at 8. Water boils at 100°C. These are not happening only this second.", ["Write a habit", "Write a fact"]),
        C("english-sp-s-form", "The -s Form", G45, "Why she plays but they play?", "Add -s/-es for he, she, it.", "Third person singular takes -s or -es: she watches, he goes.", ["Add -s", "Add -es after o/ch"]),
      ]),
      T("english-tense-present-continuous", "Present Continuous", G45, "How do you talk about right now?", "Use am/is/are + -ing for actions in progress.", "I am writing. They are playing. The helping verb matches the subject.", [
        C("english-pc-now", "Actions in Progress", G4, "What is happening at this moment?", "Describe now with -ing.", "Present continuous paints the scene now, not every day.", ["Describe now", "Choose am/is/are"]),
        C("english-pc-not-stative", "Not Every Verb -ing", G56, "Do we usually say I am knowing?", "Avoid continuous with many state verbs.", "Know, like, belong often stay simple: I know, not I am knowing.", ["Spot a state verb", "Keep it simple present"]),
      ]),
      T("english-tense-present-perfect", "Present Perfect", G56, "How is 'I have finished' different from 'I finished yesterday'?", "Use have/has + past participle for a link to now.", "Present perfect connects past to present: I have lost my pencil (so I need it now).", [
        C("english-pp-link", "Past With a Present Effect", G56, "Why might a speaker choose have eaten?", "Explain a present result of a past action.", "I have eaten means I am not hungry now. The exact time may not matter.", ["Choose have/has", "Use a past participle"]),
        C("english-pp-time", "For, Since, Already, Yet", G6, "Since 2020 or for five years — which fits present perfect?", "Use common present-perfect time words.", "Since marks a starting point. For marks a length. Yet often sits in questions and negatives.", ["Use since/for", "Use already/yet"]),
      ]),
      T("english-tense-simple-past", "Simple Past", G45, "How do you tell a finished story about yesterday?", "Use simple past for completed actions.", "Yesterday I walked. We went. The time is finished.", [
        C("english-past-regular", "Regular Past", G4, "How do most verbs show yesterday?", "Add -ed for regular past.", "Play → played. Stop → stopped (double the last letter after a short vowel).", ["Add -ed", "Spell a doubled consonant"]),
        C("english-past-irregular", "Irregular Past Stories", G45, "What is the past of see, go, and eat?", "Use common irregular past forms.", "Saw, went, ate do not take -ed. Keep a small bank of story verbs.", ["Use went/saw/ate", "Tell a short past story"]),
      ]),
      T("english-tense-past-continuous", "Past Continuous", G56, "How do you set a scene that was already happening?", "Use was/were + -ing for a background action.", "I was reading when the bell rang. The -ing action was in progress.", [
        C("english-pastc-scene", "Background Action", G56, "Which action was interrupted?", "Combine past continuous with simple past.", "The longer action uses -ing. The interrupting action is simple past.", ["Build was/were + -ing", "Add an interruption"]),
      ]),
      T("english-tense-past-perfect", "Past Perfect", G6, "How do you show which past event happened first?", "Use had + past participle for the earlier past.", "She had packed before the taxi came. Had packed is earlier than came.", [
        C("english-pastp-order", "Earlier Past", G6, "Which event happened first in a two-past story?", "Order two past events with had.", "Past perfect is the 'past of the past'. Use it when the order might be unclear.", ["Place had + participle", "Keep the later event simple past"]),
      ]),
      T("english-tense-future", "Future Forms", G56, "Is will the only way to talk about tomorrow?", "Use will, going to, and present continuous for future plans.", "Will often shows a decision or prediction. Going to shows a plan. I am visiting Grandma on Sunday is a fixed arrangement.", [
        C("english-fut-will", "Will & Going To", G56, "When is going to better than will?", "Choose will or going to with a reason.", "Look at evidence: those clouds — it is going to rain. A sudden offer often uses will.", ["Use will", "Use going to"]),
        C("english-fut-arrange", "Plans Already Set", G6, "How can present continuous talk about the future?", "Use present continuous for arrangements.", "We are leaving at 6 tomorrow. The diary already has the plan.", ["Write an arrangement", "Name a time"]),
      ]),
    ],
  },
  {
    id: "english-articles",
    title: "Articles",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "A, an, and the are tiny words with exact jobs.",
    concepts: [
      C("english-art-a-an", "A & An", G4, "Why an umbrella but a university?", "Choose a or an by sound.", "Use an before a vowel sound: an hour, an umbrella. A university starts with a 'y' sound, so a.", ["Choose a/an", "Listen for the sound"]),
      C("english-art-the", "The", G45, "When does the moon take the?", "Use the for something known or unique.", "The points to a particular one, or to unique things: the sun, the first bus we mentioned.", ["Mark a known noun", "Use the for unique"]),
      C("english-art-zero", "When to Skip an Article", G6, "Do we say the honesty is important?", "Omit articles with many general ideas and plurals.", "Honesty is important (general idea). I like mangoes (in general). The mangoes on this plate are ripe (specific).", ["Drop the for a general idea", "Keep the for specific"]),
    ],
  },
  {
    id: "english-determiners",
    title: "Determiners",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "Determiners sit before a noun and help us know which or how many.",
    concepts: [
      C("english-det-this-that", "This, That, These, Those", G4, "Which word points to near things in plural?", "Use demonstratives for near and far.", "This/these = near. That/those = farther. Match singular and plural.", ["Point near", "Point far"]),
      C("english-det-quant", "Some, Any, Many, Much", G56, "Why many books but much water?", "Choose quantity words with count and uncount nouns.", "Many/few go with countable. Much/little with uncountable. Some often in positives; any in questions and negatives.", ["Choose many/much", "Use some/any"]),
    ],
  },
  {
    id: "english-adjectives",
    title: "Adjectives",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "Adjectives add colour, size, number, and feeling to nouns.",
    concepts: [
      C("english-adj-describe", "Describing Nouns", G4, "Which words paint the noun in 'a tiny red boat'?", "Place adjectives before a noun or after be.", "A tiny red boat. The boat is tiny. Adjectives describe; they do not do the action.", ["Find an adjective", "Add two adjectives"]),
      C("english-adj-order", "Adjective Order", G56, "Why a small round wooden table, not wooden round small?", "Use a sensible English order of adjectives.", "Opinion, size, age, shape, colour, origin, material often follow that path: a lovely small old round brown Indian wooden table.", ["Order size then colour", "Rewrite a jumbled list"]),
    ],
  },
  {
    id: "english-degrees",
    title: "Degrees of Comparison",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "Adjectives can compare two things or pick the top of a group.",
    concepts: [
      C("english-deg-er-est", "-er & -est", G45, "How do you compare tall and taller?", "Form comparative and superlative for short adjectives.", "Tall, taller, tallest. Big, bigger, biggest (double the consonant). Use than with comparatives.", ["Write a comparative", "Write a superlative"]),
      C("english-deg-more-most", "More & Most", G56, "Why more beautiful, not beautifuler?", "Use more/most with longer adjectives.", "Beautiful → more beautiful → most beautiful. Irregular: good, better, best; bad, worse, worst.", ["Use more/most", "Use better/best"]),
    ],
  },
  {
    id: "english-adverbs",
    title: "Adverbs",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "Adverbs tell how, when, where, or how much.",
    concepts: [
      C("english-adv-how", "How, When, Where", G45, "What does slowly tell you in 'She walked slowly'?", "Identify adverbs of manner, time, and place.", "Slowly = how. Yesterday = when. Outside = where. Many manner adverbs end in -ly, but not all.", ["Spot manner", "Spot time or place"]),
      C("english-adv-degree", "Very, Too, Enough", G56, "How is too different from very?", "Use degree adverbs carefully.", "Very strengthens. Too often means more than wanted. Enough usually follows an adjective: tall enough.", ["Contrast too and very", "Place enough"]),
    ],
  },
  {
    id: "english-prepositions",
    title: "Prepositions",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "Prepositions show place, time, and relation.",
    concepts: [
      C("english-prep-place", "Place: in, on, under, between", G4, "Where is the cat relative to the box?", "Use common place prepositions.", "In the box, on the box, under the box, between two boxes. The preposition links the noun to a place.", ["Choose in/on/under", "Use between"]),
      C("english-prep-time", "Time: at, on, in", G45, "Why at 6 o'clock, on Monday, in July?", "Use at/on/in for time.", "At a clock time, on a day or date, in a month, year, or longer period.", ["Use at a time", "Use on a day", "Use in a month"]),
      C("english-prep-other", "For, With, From, About", G56, "Which preposition fits a gift for a friend?", "Use prepositions that show purpose, company, source.", "A gift for Riya. I went with my sister. A letter from Dad. A story about elephants.", ["Choose for/with", "Choose from/about"]),
    ],
  },
  {
    id: "english-conjunctions",
    title: "Conjunctions",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "Conjunctions are joining words for ideas.",
    concepts: [
      C("english-conj-and-but-or", "And, But, Or", G4, "When is but the honest joiner?", "Join words and simple sentences with and, but, or.", "And adds. But contrasts. Or offers a choice. Do not glue everything with and.", ["Join with and", "Contrast with but"]),
      C("english-conj-because-so", "Because & So", G45, "Which word introduces a reason?", "Link cause and result.", "Because introduces a reason. So introduces a result. I stayed in because it rained. It rained, so I stayed in.", ["Give a reason", "Give a result"]),
      C("english-conj-although", "Although & If", G56, "How does although change the expected ending?", "Use although for contrast and if for a condition.", "Although I was tired, I finished. If it rains, we will wait. These join whole clauses.", ["Write although", "Write if"]),
    ],
  },
  {
    id: "english-interjections",
    title: "Interjections",
    subject: "english",
    category: "Grammar",
    grades: G45,
    hook: "Interjections are sudden feeling-words, often with an exclamation mark.",
    concepts: [
      C("english-int-feel", "Oh, Wow, Oops", G4, "What feeling does oops show?", "Use common interjections with the right tone.", "Wow shows surprise. Oops shows a small mistake. They are not the subject or the verb.", ["Match feeling to word", "Punctuate an exclamation"]),
    ],
  },
  {
    id: "english-modals",
    title: "Modals",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "Can, could, may, must, should colour what is possible, allowed, or wise.",
    concepts: [
      C("english-mod-can", "Can & Could", G45, "How is could softer than can?", "Use can for ability and could for polite or past ability.", "I can swim. Could you help me? Could also tells past ability: I could ride at six.", ["Show ability", "Make a polite request"]),
      C("english-mod-must-should", "Must, Should, May", G56, "Which word is strongest: should or must?", "Choose must, should, and may with the right force.", "Must is strong necessity. Should is advice. May is permission or possibility.", ["Give advice with should", "State a rule with must"]),
    ],
  },
  {
    id: "english-sentence-structure",
    title: "Sentence Structure",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "A sentence is a complete thought with a job to do.",
    concepts: [
      C("english-sent-complete", "What Makes a Sentence", G4, "Why is 'Under the table' not a sentence by itself?", "Write a complete sentence with a subject and a verb.", "A sentence needs someone or something and a verb that finishes the thought. Fragments leave you hanging.", ["Spot a fragment", "Finish a sentence"]),
      C("english-sent-types", "Statement, Question, Command, Exclamation", G45, "How does punctuation change the job of a sentence?", "Identify four sentence jobs.", "Statements tell. Questions ask. Commands tell someone to do. Exclamations show strong feeling.", ["Write each type", "Match end marks"]),
    ],
  },
  {
    id: "english-subject-predicate",
    title: "Subject & Predicate",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "The subject is who or what; the predicate tells about it.",
    concepts: [
      C("english-sub-who", "Finding the Subject", G4, "Who or what is this sentence about?", "Name the subject of a simple sentence.", "The subject is the person, animal, or thing the sentence is about. The rest that tells about it is the predicate.", ["Underline the subject", "Underline the predicate"]),
      C("english-sub-complete", "Complete Subject & Predicate", G56, "Is 'The little brown sparrow' all subject?", "Split complete subject and complete predicate.", "All the describing words before the verb belong to the subject. The verb and what follows belong to the predicate.", ["Bracket the complete subject", "Bracket the predicate"]),
    ],
  },
  {
    id: "english-subject-object",
    title: "Subject & Object",
    subject: "english",
    category: "Grammar",
    grades: G56,
    hook: "The object receives the action the subject does.",
    concepts: [
      C("english-obj-direct", "Direct Objects", G56, "What did she throw in 'She threw the ball'?", "Find the direct object.", "Ask 'subject + verb + what/whom?' The ball is the direct object.", ["Ask what/whom", "Name the object"]),
      C("english-obj-indirect", "Indirect Objects", G6, "Who received the gift in 'Aman gave Riya a gift'?", "Find an indirect object.", "Riya is the indirect object (to whom). Gift is the direct object (what).", ["Name the receiver", "Name the thing given"]),
    ],
  },
  {
    id: "english-phrases",
    title: "Phrases",
    subject: "english",
    category: "Grammar",
    grades: G56,
    hook: "A phrase is a group of words that belongs together but is not a full sentence.",
    concepts: [
      C("english-phr-prep", "Prepositional Phrases", G56, "What extra information does 'on the roof' add?", "Identify prepositional phrases.", "A preposition plus its noun: on the roof, after dinner. A phrase has no finite verb of its own.", ["Box a phrase", "Say what it tells"]),
      C("english-phr-noun", "Noun Phrases", G6, "How many words make the noun idea in 'the tall coconut tree'?", "Expand a noun into a noun phrase.", "Determiners and adjectives build a noun phrase around the head noun tree.", ["Find the head noun", "Expand a noun phrase"]),
    ],
  },
  {
    id: "english-clauses",
    title: "Clauses",
    subject: "english",
    category: "Grammar",
    grades: G56,
    hook: "A clause has a subject and a verb; some can stand alone.",
    concepts: [
      C("english-cl-independent", "Independent Clauses", G56, "Can this group of words stand as a sentence?", "Recognise a clause that can stand alone.", "The rain stopped is independent. It has a subject and a verb and a finished thought.", ["Spot an independent clause", "Add end punctuation"]),
      C("english-cl-dependent", "Dependent Clauses", G6, "Why does 'because the rain stopped' feel unfinished?", "Recognise a clause that needs a partner.", "A subordinating word (because, when, if, although) makes a clause dependent. It needs an independent clause.", ["Spot because/when/if", "Attach it to a main clause"]),
    ],
  },
  {
    id: "english-simple-sentences",
    title: "Simple Sentences",
    subject: "english",
    category: "Grammar",
    grades: G45,
    hook: "A simple sentence is one complete thought.",
    concepts: [
      C("english-simple-one", "One Independent Clause", G4, "Can a simple sentence still have two nouns?", "Write a simple sentence with one main clause.", "Birds fly. The black bird and the crow flew. Still one clause if they share one verb idea.", ["Write a short simple sentence", "Add adjectives without extra clauses"]),
    ],
  },
  {
    id: "english-compound-sentences",
    title: "Compound Sentences",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "A compound sentence joins two equal thoughts.",
    concepts: [
      C("english-comp-fanboys", "Joining With And, But, Or, So", G45, "How do you join two complete sentences without a comma splice?", "Build a compound sentence with a coordinating conjunction.", "Two independent clauses + and/but/or/so. A comma often sits before the conjunction.", ["Join with and", "Join with but"]),
      C("english-comp-comma", "Avoiding Run-ons", G56, "Why is 'I ran I fell' not enough?", "Fix run-ons with a conjunction or a full stop.", "Two sentences need a joiner or a stop. A comma alone is not a strong enough glue.", ["Fix a run-on", "Choose a full stop"]),
    ],
  },
  {
    id: "english-complex-sentences",
    title: "Complex Sentences",
    subject: "english",
    category: "Grammar",
    grades: G56,
    hook: "A complex sentence hangs a dependent clause on a main clause.",
    concepts: [
      C("english-cpx-when", "When, Because, If, Although", G56, "Which clause cannot stand alone?", "Write a complex sentence with a subordinating conjunction.", "If you start with the dependent clause, use a comma: When the bell rang, we stood. No comma if it comes second.", ["Start with when/if", "Put the clause second"]),
    ],
  },
  {
    id: "english-questions",
    title: "Questions",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "Questions ask; their word order and helpers do the asking.",
    concepts: [
      C("english-q-yesno", "Yes/No Questions", G4, "How do you turn 'She is ready' into a question?", "Form yes/no questions with be or do.", "Is she ready? Do they play? The helper moves or appears at the front.", ["Invert be", "Add do/does/did"]),
      C("english-q-wh", "Wh- Questions", G45, "Which word asks for a person, and which for a thing?", "Use who, what, where, when, why, how.", "Who = person. What = thing. Where = place. When = time. Why = reason. How = manner.", ["Ask who/what", "Ask why/how"]),
    ],
  },
  {
    id: "english-negatives",
    title: "Negatives",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "Negatives say that something is not so.",
    concepts: [
      C("english-neg-not", "Not & n't", G4, "How do you make 'I like spinach' negative?", "Form negatives with not / n't.", "I do not like spinach. She is not ready. Use do/does/did when there is no other helper.", ["Add not", "Use don't/doesn't"]),
      C("english-neg-double", "One Negative Is Enough", G56, "Why avoid I don't know nothing in careful writing?", "Use a single negative in standard English.", "I don't know anything. Nobody came. Two negatives (don't + nothing) can confuse the meaning.", ["Choose anything/anybody", "Rewrite a double negative"]),
    ],
  },
  {
    id: "english-voice",
    title: "Active & Passive Voice",
    subject: "english",
    category: "Grammar",
    grades: G6,
    hook: "Voice chooses whether the doer or the receiver leads the sentence.",
    concepts: [
      C("english-voice-active", "Active Voice", G6, "Who does the action in 'The chef baked the cake'?", "Write clear active sentences.", "Active: subject does the verb. The chef baked the cake. It is usually clearer.", ["Name the doer", "Write an active sentence"]),
      C("english-voice-passive", "Passive Voice", G6, "When might we say 'The cake was baked'?", "Form a simple passive with be + past participle.", "Passive puts the receiver first: The cake was baked (by the chef). Use it when the doer is unknown or less important.", ["Form was/were + participle", "Add by + doer"]),
    ],
  },
  {
    id: "english-speech",
    title: "Direct & Indirect Speech",
    subject: "english",
    category: "Grammar",
    grades: G56,
    hook: "We can quote exact words or report them.",
    concepts: [
      C("english-speech-direct", "Direct Speech", G56, "Where do the quotation marks go?", "Punctuate a speaker's exact words.", "Riya said, \"I am ready.\" Comma before the quote. Capital inside. Marks around the spoken words.", ["Place quotation marks", "Capitalise the quote"]),
      C("english-speech-indirect", "Indirect Speech", G6, "How do tenses often shift when we report?", "Report speech without quotation marks.", "She said she was ready. I becomes she. Am often becomes was after a past reporting verb.", ["Change the pronoun", "Shift a present to past"]),
    ],
  },
  {
    id: "english-conditionals",
    title: "Conditionals",
    subject: "english",
    category: "Grammar",
    grades: G56,
    hook: "If-clauses show what depends on what.",
    concepts: [
      C("english-cond-zero-first", "Real Conditions", G56, "How do you talk about a likely future if?", "Use if + present, will for a real future result.", "If it rains, we will stay in. For facts: If you heat ice, it melts.", ["Write a first conditional", "Write a fact condition"]),
      C("english-cond-unreal", "Unreal or Imaginary", G6, "Why do we say If I were... for imaginary ideas?", "Use past forms for imaginary present/future.", "If I had a telescope, I would look at Saturn. The past form does not mean the time is past; it means imaginary.", ["Write an imaginary if", "Use would"]),
    ],
  },
  {
    id: "english-question-tags",
    title: "Question Tags",
    subject: "english",
    category: "Grammar",
    grades: G6,
    hook: "A tag turns a statement into a checking question.",
    concepts: [
      C("english-tag-match", "Matching the Helper", G6, "Why isn't it 'You are ready, are you?' if we expect yes?", "Add a tag with the opposite positive/negative.", "You are ready, aren't you? She doesn't swim, does she? The helper matches; the +/− flips.", ["Add a negative tag", "Add a positive tag"]),
    ],
  },
  {
    id: "english-punctuation",
    title: "Punctuation",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "Punctuation is the traffic system of writing.",
    concepts: [
      C("english-punct-end", "Full Stop, Question, Exclamation", G4, "Which mark belongs at the end of a question?", "Choose the correct end mark.", "Statements end with a full stop. Questions with a question mark. Strong feeling with an exclamation mark — not after every sentence.", ["End a statement", "End a question"]),
      C("english-punct-comma", "Commas", G45, "Where do commas help a list?", "Use commas in lists and to pause clearly.", "Red, blue, and green. A comma can also mark a pause after a fronted phrase: After dinner, we walked.", ["Punctuate a list", "Pause after an opener"]),
      C("english-punct-apostrophe", "Apostrophes", G56, "Is it the cats' bowls or the cat's bowls?", "Use apostrophes for possession and contractions.", "It's = it is. Its = belonging to it (no apostrophe). Apostrophes also show possession.", ["Write a contraction", "Write a possessive"]),
    ],
  },
  {
    id: "english-capitalization",
    title: "Capitalization",
    subject: "english",
    category: "Grammar",
    grades: G45,
    hook: "Capitals mark starts and special names.",
    concepts: [
      C("english-cap-start", "Sentence Starts & I", G4, "When must I be capital even in the middle?", "Capitalise sentence starts, the word I, and names.", "The first word of a sentence, the pronoun I, and proper nouns take capitals.", ["Capitalise a start", "Capitalise I and names"]),
      C("english-cap-titles", "Titles & Places", G45, "Which words in a book title take capitals?", "Capitalise important words in titles and place names.", "The Secret Garden. New Delhi. Days and months: Monday, April.", ["Capitalise a title", "Capitalise a place"]),
    ],
  },
  {
    id: "english-grammar-errors",
    title: "Common Grammar Errors",
    subject: "english",
    category: "Grammar",
    grades: G456,
    hook: "A few mix-ups show up again and again — we can catch them.",
    concepts: [
      C("english-err-their", "Their, There, They're", G45, "Which spelling means they are?", "Choose their, there, and they're.", "Their = belonging to them. There = a place. They're = they are.", ["Pick their", "Pick they're"]),
      C("english-err-your", "Your & You're", G45, "Which one is you are?", "Choose your and you're.", "Your bag. You're late = you are late.", ["Pick your", "Pick you're"]),
      C("english-err-its", "Its & It's", G56, "Does the possessive its want an apostrophe?", "Choose its and it's.", "It's = it is or it has. Its = belonging to it.", ["Pick it's", "Pick its"]),
      C("english-err-agree", "Agreement Slip-ups", G6, "Why does 'The list of names are long' sound off?", "Fix subject-verb agreement in longer subjects.", "List is the head, so is. Of names is extra. Match the verb to the head noun.", ["Find the head", "Fix the verb"]),
    ],
  },
  {
    id: "english-synonyms",
    title: "Synonyms",
    subject: "english",
    category: "Vocabulary",
    grades: G456,
    hook: "Synonyms are words close in meaning — not always perfect twins.",
    concepts: [
      C("english-syn-near", "Near Meanings", G4, "Is happy a good swap for glad?", "Find a synonym that still fits the sentence.", "Big/large are close. Whisper/shout are not. Check the sentence before you swap.", ["Find a synonym", "Test it in a sentence"]),
      C("english-syn-shade", "Shades of Meaning", G56, "Why might you choose stroll instead of walk?", "Choose a synonym for tone.", "Stroll is unhurried. March is firm. Synonyms carry feeling.", ["Pick a stronger word", "Pick a gentler word"]),
    ],
  },
  {
    id: "english-antonyms",
    title: "Antonyms",
    subject: "english",
    category: "Vocabulary",
    grades: G456,
    hook: "Antonyms sit at the other end of a meaning.",
    concepts: [
      C("english-ant-pairs", "Opposite Pairs", G4, "What is an opposite of empty?", "Name common antonyms.", "Empty/full, ancient/modern. Some opposites use un- or in-: kind/unkind.", ["Name an opposite", "Use un-"]),
      C("english-ant-grade", "Not Always Perfect Opposites", G56, "Is warm the opposite of hot?", "Choose antonyms that fit the scale.", "Hot/cold is a far pair. Warm sits in between. Context decides.", ["Place words on a scale", "Pick a true opposite"]),
    ],
  },
  {
    id: "english-homophones",
    title: "Homophones",
    subject: "english",
    category: "Vocabulary",
    grades: G456,
    hook: "Homophones sound the same but are not the same word.",
    concepts: [
      C("english-homo-pairs", "Sound-Alike Pairs", G45, "Which two is a number, and which too means also?", "Choose the right homophone in a sentence.", "Two/to/too, sea/see, right/write. Meaning, not sound, picks the spelling.", ["Choose two/to/too", "Choose see/sea"]),
    ],
  },
  {
    id: "english-homonyms",
    title: "Homonyms",
    subject: "english",
    category: "Vocabulary",
    grades: G56,
    hook: "Some words share spelling or sound and split their meanings.",
    concepts: [
      C("english-homonym-bat", "Same Word, Different Meaning", G56, "Is bat an animal or sports gear here?", "Use context to pick a homonym's meaning.", "A cricket bat and a flying bat share a spelling. The sentence tells you which.", ["Use context", "Write two meanings"]),
    ],
  },
  {
    id: "english-prefixes",
    title: "Prefixes",
    subject: "english",
    category: "Vocabulary",
    grades: G456,
    hook: "A prefix is a chunk added at the front to change meaning.",
    concepts: [
      C("english-pre-un-re", "Un-, Re-, Dis-", G45, "What does un- usually do to a word?", "Explain un-, re-, and dis-.", "Un- often means not. Re- means again. Dis- can reverse: disappear, disagree.", ["Make an un- word", "Make a re- word"]),
      C("english-pre-pre-mis", "Pre-, Mis-, Over-", G56, "What does mis- warn you about?", "Use pre-, mis-, and over-.", "Pre- = before. Mis- = wrongly. Over- = too much. Preview, misspell, overcook.", ["Explain mis-", "Build a new word"]),
    ],
  },
  {
    id: "english-suffixes",
    title: "Suffixes",
    subject: "english",
    category: "Vocabulary",
    grades: G456,
    hook: "A suffix is a chunk at the end that can change job or meaning.",
    concepts: [
      C("english-suf-ly-ful", "-ly, -ful, -less", G45, "How does -ly turn kind into kindly?", "Form adverbs and adjectives with common suffixes.", "-ly often makes an adverb. -ful = full of. -less = without.", ["Add -ly", "Contrast -ful and -less"]),
      C("english-suf-tion-er", "-tion, -er, -ness", G56, "How do you turn invent into a noun?", "Build nouns with -tion, -er, -ness.", "Invent → invention. Teach → teacher. Kind → kindness. The suffix can change the word class.", ["Make a -tion noun", "Make an -er noun"]),
    ],
  },
  {
    id: "english-roots",
    title: "Root Words",
    subject: "english",
    category: "Vocabulary",
    grades: G56,
    hook: "A root is the core meaning a family of words shares.",
    concepts: [
      C("english-root-family", "Finding the Root", G56, "What root do rewrite, writer, and written share?", "Spot a root and related words.", "Write is the root. Prefixes and suffixes dress it up. Knowing the root helps spelling and meaning.", ["Name the root", "List related words"]),
    ],
  },
  {
    id: "english-compounds",
    title: "Compound Words",
    subject: "english",
    category: "Vocabulary",
    grades: G45,
    hook: "Two words can join to make a new idea.",
    concepts: [
      C("english-comp-join", "Joining Two Words", G4, "What new idea does sunflower name?", "Read and build compound words.", "Sun + flower = sunflower. Some stay open (ice cream), some hyphenate, many close up.", ["Split a compound", "Build a compound"]),
    ],
  },
  {
    id: "english-word-families",
    title: "Word Families",
    subject: "english",
    category: "Vocabulary",
    grades: G456,
    hook: "Word families share a pattern of sound or meaning.",
    concepts: [
      C("english-fam-pattern", "Families That Rhyme or Share a Root", G45, "What family do play, playing, and replay belong to?", "Group words by pattern or root.", "Families help spelling: night, light, bright. Meaning families: play, player, replay.", ["List a sound family", "List a meaning family"]),
    ],
  },
  {
    id: "english-context-clues",
    title: "Context Clues",
    subject: "english",
    category: "Vocabulary",
    grades: G456,
    hook: "Nearby words can unlock a new word.",
    concepts: [
      C("english-ctx-guess", "Guessing From the Sentence", G45, "If the sentence says 'the arid desert with almost no rain', what might arid mean?", "Use a definition, example, or contrast clue.", "Writers sometimes explain, give an example, or use but/unlike. Use those clues before a dictionary.", ["Use a definition clue", "Use a contrast clue"]),
      C("english-ctx-check", "Checking a Guess", G56, "How do you know your guess is good enough?", "Replace the word with your guess and reread.", "If the sentence still makes sense, you are close. Then confirm with a dictionary when you can.", ["Substitute a synonym", "Reread the sentence"]),
    ],
  },
  {
    id: "english-idioms",
    title: "Idioms",
    subject: "english",
    category: "Vocabulary",
    grades: G56,
    hook: "An idiom's meaning is not the sum of the words.",
    concepts: [
      C("english-idiom-meaning", "Not Word-by-Word", G56, "Does raining cats and dogs mean animals fall from the sky?", "Explain a common idiom in plain language.", "Piece of cake means easy. Hold your horses means wait. Picture the idea, not the animals.", ["Explain an idiom", "Use one in a sentence"]),
    ],
  },
  {
    id: "english-proverbs",
    title: "Proverbs",
    subject: "english",
    category: "Vocabulary",
    grades: G56,
    hook: "A proverb is a short saying that offers a lesson.",
    concepts: [
      C("english-prov-lesson", "A Lesson in a Line", G56, "What does 'Look before you leap' advise?", "Restate a proverb in your own words.", "Proverbs teach caution, effort, or kindness. Honesty is the best policy means telling the truth is wiser.", ["Restate a proverb", "Match a proverb to a situation"]),
    ],
  },
  {
    id: "english-spelling",
    title: "Spelling",
    subject: "english",
    category: "Vocabulary",
    grades: G456,
    hook: "Spelling is pattern plus a few rebels you learn by heart.",
    concepts: [
      C("english-spell-patterns", "Useful Patterns", G4, "When do we double a letter before -ing?", "Apply a few reliable spelling patterns.", "Drop silent e before -ing: make → making. Double a short-vowel consonant: run → running.", ["Drop silent e", "Double a consonant"]),
      C("english-spell-tricky", "Tricky High-Frequency Words", G56, "Which pair is often swapped: their/there or because/becuase?", "Spell common trouble words.", "Because, friend, they, said, which. Look, say, cover, write, check.", ["Spell a trouble word", "Use look-say-cover-write"]),
    ],
  },
  {
    id: "english-vocab-context",
    title: "Vocabulary in Context",
    subject: "english",
    category: "Vocabulary",
    grades: G456,
    hook: "A word's best meaning is the one that fits this sentence.",
    concepts: [
      C("english-voc-fit", "The Meaning That Fits", G45, "Does bright mean clever or shining here?", "Choose a meaning that fits the passage.", "Bright light vs a bright idea. Do not grab the first dictionary sense.", ["Pick the fitting sense", "Reject a wrong sense"]),
    ],
  },
  {
    id: "english-fluency",
    title: "Reading Fluency",
    subject: "english",
    category: "Reading",
    grades: G45,
    hook: "Fluency is reading so the words sound like talking, not like a robot.",
    concepts: [
      C("english-flu-smooth", "Smooth & Expressive", G4, "How do punctuation marks tell your voice what to do?", "Read aloud with phrasing and expression.", "Pause at commas and stops. Let a question rise. Group words that belong together.", ["Pause at punctuation", "Read a sentence in one breath-group"]),
    ],
  },
  {
    id: "english-comprehension",
    title: "Reading Comprehension",
    subject: "english",
    category: "Reading",
    grades: G456,
    hook: "Comprehension is understanding, not just saying the words.",
    concepts: [
      C("english-comp-check", "Checking Understanding", G4, "Can you retell what you just read in one or two sentences?", "Pause and retell to check meaning.", "If you cannot retell, reread the tricky sentence. Understanding is the goal.", ["Retell a paragraph", "Reread a hard sentence"]),
      C("english-comp-q", "Answering From the Text", G45, "Where is the evidence for your answer?", "Find answers that the text actually supports.", "Some answers are right there. Some need putting ideas together. Guessing without the text is not reading.", ["Point to a sentence", "Use because + text"]),
    ],
  },
  {
    id: "english-main-idea",
    title: "Main Idea",
    subject: "english",
    category: "Reading",
    grades: G456,
    hook: "The main idea is what the whole text is mostly about.",
    concepts: [
      C("english-main-mostly", "Mostly About", G4, "If you had to give the paragraph a title, what would it be?", "State a main idea in a sentence.", "Details are the leaves. The main idea is the stem they grow from.", ["Give a title", "Write a main-idea sentence"]),
      C("english-main-vs-topic", "Topic vs Main Idea", G56, "How is 'elephants' different from the writer's point about elephants?", "Separate a topic word from a full main idea.", "Topic: elephants. Main idea: Elephants use their trunks as tools. The second is a claim.", ["Name the topic", "Write the point"]),
    ],
  },
  {
    id: "english-details",
    title: "Supporting Details",
    subject: "english",
    category: "Reading",
    grades: G456,
    hook: "Details prove, explain, or paint the main idea.",
    concepts: [
      C("english-det-support", "Details That Earn Their Place", G45, "Which sentence actually supports the main idea?", "Pick details that belong.", "A supporting detail answers how, why, or for example. A stray fact about an unrelated animal does not help.", ["Choose a supporting sentence", "Drop a stray detail"]),
    ],
  },
  {
    id: "english-sequencing",
    title: "Sequencing",
    subject: "english",
    category: "Reading",
    grades: G45,
    hook: "Order words keep events from getting scrambled.",
    concepts: [
      C("english-seq-order", "First, Next, Then, Finally", G4, "What happened before the character ran?", "Order events from a text.", "Look for time words and cause. Number the events. Retell in order.", ["Number events", "Retell in order"]),
    ],
  },
  {
    id: "english-cause-effect",
    title: "Cause & Effect",
    subject: "english",
    category: "Reading",
    grades: G456,
    hook: "A cause makes something happen; the effect is what happens.",
    concepts: [
      C("english-ce-because", "Because & So in Texts", G45, "What caused the crops to fail in the passage?", "Name a cause and its effect.", "Because, so, therefore, and as a result are clues. The cause is the why.", ["Name a cause", "Name an effect"]),
    ],
  },
  {
    id: "english-compare-contrast",
    title: "Compare & Contrast",
    subject: "english",
    category: "Reading",
    grades: G456,
    hook: "Compare finds likeness; contrast finds difference.",
    concepts: [
      C("english-cc-alike", "Alike & Different", G45, "How are two characters the same, and how not?", "Compare and contrast using a simple chart.", "Both... / Unlike... Signal words: similarly, however, but, on the other hand.", ["List a likeness", "List a difference"]),
    ],
  },
  {
    id: "english-inference",
    title: "Inference",
    subject: "english",
    category: "Reading",
    grades: G456,
    hook: "An inference is a smart guess using clues plus what you know.",
    concepts: [
      C("english-inf-clues", "Clues + What You Know", G45, "The character slammed the door and sat in silence. What might they feel?", "Make an inference and name the clue.", "The text does not always say angry. Clues + life knowledge = inference. It must still fit the text.", ["Name a clue", "State an inference"]),
      C("english-inf-prove", "Checking an Inference", G6, "Could the same clue mean something else?", "Test whether another inference also fits.", "If the next sentence shows they were late, maybe they are stressed, not angry. Keep reading.", ["Test another idea", "Revise with new evidence"]),
    ],
  },
  {
    id: "english-prediction",
    title: "Prediction",
    subject: "english",
    category: "Reading",
    grades: G45,
    hook: "A prediction is a thoughtful guess about what might happen next.",
    concepts: [
      C("english-pred-next", "What Might Happen Next", G4, "What in the story makes you think that?", "Predict and give a because.", "Use character, setting, and problem. After you read on, check if you were close.", ["Make a prediction", "Check after reading on"]),
    ],
  },
  {
    id: "english-fact-opinion",
    title: "Fact vs Opinion",
    subject: "english",
    category: "Reading",
    grades: G456,
    hook: "A fact can be checked; an opinion is a belief or preference.",
    concepts: [
      C("english-fo-sort", "Checkable vs Personal", G45, "Is 'Mangoes are the best fruit' a fact?", "Sort facts and opinions.", "Water boils at 100°C at standard pressure is checkable. Best fruit is an opinion. Look for I think, should, best.", ["Spot a fact", "Spot an opinion"]),
    ],
  },
  {
    id: "english-summarizing",
    title: "Summarizing",
    subject: "english",
    category: "Reading",
    grades: G56,
    hook: "A summary is the important ideas in fewer words, in your own words.",
    concepts: [
      C("english-sum-short", "Short & Faithful", G56, "What would you keep if you could only keep three sentences?", "Write a short summary without copying whole lines.", "Keep who/what, the problem, and the outcome or main points. Drop tiny decorations.", ["List key points", "Write a 3-sentence summary"]),
    ],
  },
  {
    id: "english-character",
    title: "Character",
    subject: "english",
    category: "Reading",
    grades: G456,
    hook: "Characters are who the story is about — and how they change.",
    concepts: [
      C("english-ch-traits", "Traits From Actions", G45, "What does a character's choice show about them?", "Name a trait and support it with an action.", "Kind is a trait. Sharing lunch is evidence. Do not only use looks.", ["Name a trait", "Quote an action"]),
      C("english-ch-change", "How Characters Change", G56, "Who is different by the last page, and why?", "Describe a change and its cause.", "A character may grow braver or kinder because of the problem. The change needs a because.", ["Describe a change", "Give the because"]),
    ],
  },
  {
    id: "english-setting",
    title: "Setting",
    subject: "english",
    category: "Reading",
    grades: G45,
    hook: "Setting is where and when, and it shapes what can happen.",
    concepts: [
      C("english-set-where", "Where & When", G4, "Could this story happen in your classroom tomorrow?", "Identify place and time.", "A forest at night is a different story from a busy market at noon. Setting limits and invites events.", ["Name the place", "Name the time"]),
    ],
  },
  {
    id: "english-plot",
    title: "Plot",
    subject: "english",
    category: "Reading",
    grades: G456,
    hook: "Plot is the chain of events: problem, attempts, turning point, end.",
    concepts: [
      C("english-plot-problem", "Problem & Attempts", G45, "What does the character want, and what gets in the way?", "Name the problem and two attempts.", "A plot needs a want and obstacles. List beginning, middle, end without every tiny action.", ["Name the want", "Name an obstacle"]),
      C("english-plot-turn", "Turning Point", G56, "Where does the story tip toward its ending?", "Identify a turning point.", "The turning point is when something important changes. After it, the ending becomes likely.", ["Mark the turning point", "Say what changed"]),
    ],
  },
  {
    id: "english-theme",
    title: "Theme",
    subject: "english",
    category: "Reading",
    grades: G56,
    hook: "Theme is a bigger idea the story suggests, not just the topic.",
    concepts: [
      C("english-theme-idea", "A Lesson Without Preaching", G56, "Is 'friendship' a theme, or is it only a topic?", "State a theme as a full sentence.", "Topic: friendship. Theme: True friends tell the truth even when it is hard. Theme is a message you can argue from the story.", ["Write a theme sentence", "Support it with a moment"]),
    ],
  },
  {
    id: "english-authors-purpose",
    title: "Author's Purpose",
    subject: "english",
    category: "Reading",
    grades: G456,
    hook: "Writers usually want to inform, entertain, or persuade — sometimes more than one.",
    concepts: [
      C("english-ap-pie", "Inform, Entertain, Persuade", G45, "Why was this text written?", "Choose a primary purpose and give a clue.", "A recipe informs. A trickster tale entertains. An appeal to save water persuades. Look at the clues.", ["Choose a purpose", "Point to a clue"]),
    ],
  },
  {
    id: "english-reading-vocab",
    title: "Words in a Passage",
    subject: "english",
    category: "Reading",
    grades: G456,
    hook: "In reading, new words are unlocked by the passage around them.",
    concepts: [
      C("english-rv-passage", "Words Inside a Passage", G45, "Which nearby words help you?", "Use passage clues while reading, not only a list.", "Reread the sentence before and after. Try a synonym. Then move on if the gist is clear.", ["Use a nearby clue", "Keep the gist"]),
    ],
  },
  {
    id: "english-sentence-writing",
    title: "Sentence Writing",
    subject: "english",
    category: "Writing",
    grades: G45,
    hook: "Strong sentences are complete, clear, and varied.",
    concepts: [
      C("english-sw-clear", "Clear Complete Sentences", G4, "Does your sentence tell who did what?", "Write a complete, clear sentence.", "Name the subject. Choose a strong verb. Cut extra fog. Capital and end mark.", ["Write who did what", "Add an end mark"]),
      C("english-sw-vary", "Varying Sentences", G45, "What happens if every sentence starts the same way?", "Vary length and openings.", "Mix short and longer sentences. Start some with a time or place phrase.", ["Write a short sentence", "Write a longer one"]),
    ],
  },
  {
    id: "english-paragraphs",
    title: "Paragraph Writing",
    subject: "english",
    category: "Writing",
    grades: G456,
    hook: "A paragraph is a cluster of sentences about one idea.",
    concepts: [
      C("english-para-topic", "Topic Sentence & Details", G45, "What belongs in this paragraph, and what does not?", "Write a paragraph with a topic sentence and supporting details.", "Open with the idea. Add two or three details. Close or move on. Indent or skip a line as you are taught.", ["Write a topic sentence", "Add supporting details"]),
      C("english-para-unity", "Sticking to One Idea", G56, "When should you start a new paragraph?", "Keep one idea per paragraph.", "A new time, place, speaker, or idea often wants a new paragraph. Do not dump a whole story in one block.", ["Split a mixed paragraph", "Stay on topic"]),
    ],
  },
  {
    id: "english-descriptive",
    title: "Descriptive Writing",
    subject: "english",
    category: "Writing",
    grades: G456,
    hook: "Description lets a reader see, hear, and feel the moment.",
    concepts: [
      C("english-desc-senses", "Show With Senses", G45, "Instead of nice, what did you see or hear?", "Use sensory details instead of empty words.", "The mango was sticky-sweet on my fingers is stronger than it was nice. Choose exact nouns and verbs.", ["Replace nice/good", "Add a sound or texture"]),
    ],
  },
  {
    id: "english-narrative",
    title: "Narrative Writing",
    subject: "english",
    category: "Writing",
    grades: G456,
    hook: "A narrative tells a story with a beginning, middle, and end.",
    concepts: [
      C("english-nar-arc", "Beginning, Middle, End", G45, "What problem gets the story moving?", "Plan a simple narrative arc.", "Start in a moment. Give a problem. Show attempts. End with a change. Do not start with 'Hi my name is' unless it serves the story.", ["Write an opening moment", "Write an ending change"]),
    ],
  },
  {
    id: "english-story",
    title: "Story Writing",
    subject: "english",
    category: "Writing",
    grades: G456,
    hook: "A story needs character, setting, problem, and a satisfying close.",
    concepts: [
      C("english-story-parts", "The Story Kit", G4, "Who wants what, and what gets in the way?", "Include character, setting, problem, and ending.", "Name a character. Place them. Give a want and a problem. End on purpose, not 'then I woke up' unless the dream is the point.", ["Name want and problem", "Write a real ending"]),
      C("english-story-dialogue", "Dialogue That Moves the Story", G56, "Does this speech tell us something we could not skip?", "Write dialogue with tags and purpose.", "New speaker, new line. \"I can't climb that,\" whispered Mira. Dialogue should show character or move plot.", ["Punctuate a spoken line", "Cut empty chat"]),
    ],
  },
  {
    id: "english-creative",
    title: "Creative Writing",
    subject: "english",
    category: "Writing",
    grades: G56,
    hook: "Creative writing plays with ideas while still making sense to a reader.",
    concepts: [
      C("english-cre-image", "Fresh Images", G56, "Can you describe rain without the word rain?", "Invent a fresh image that a reader can picture.", "Avoid the first cliché. Compare using like or as only if it is exact. Surprise with a true detail.", ["Write a fresh comparison", "Replace a cliché"]),
    ],
  },
  {
    id: "english-picture-comp",
    title: "Picture Composition",
    subject: "english",
    category: "Writing",
    grades: G45,
    hook: "A picture is a story waiting for careful looking.",
    concepts: [
      C("english-pic-observe", "Look, Then Write", G4, "What is happening in the foreground that you almost missed?", "Turn a picture into an ordered paragraph.", "Name who, where, and what is happening. Guess feelings from faces. Write in a sensible order, not a jumble.", ["List what you see", "Write a sequenced paragraph"]),
    ],
  },
  {
    id: "english-diary",
    title: "Diary Writing",
    subject: "english",
    category: "Writing",
    grades: G45,
    hook: "A diary entry is a day's thoughts in first person, dated.",
    concepts: [
      C("english-diary-voice", "Dear Diary", G45, "What feeling belongs to this day?", "Write a dated first-person entry.", "Start with a date. Use I. Tell events and feelings. It can be honest and still kind.", ["Write a date line", "Include a feeling"]),
    ],
  },
  {
    id: "english-letter",
    title: "Letter Writing",
    subject: "english",
    category: "Writing",
    grades: G456,
    hook: "Letters have a greeting, a purpose, and a closing.",
    concepts: [
      C("english-let-informal", "Friendly Letters", G45, "How do you open a letter to a cousin?", "Write an informal letter with address parts you are taught.", "Greeting, news or thanks, closing, name. Keep a warm tone.", ["Write a greeting", "Write a closing"]),
      C("english-let-formal", "Formal Letters", G56, "How is a letter to a principal different from a letter to a friend?", "Write a polite formal letter of request or complaint.", "Clear purpose, polite words, no slang, correct closing. State what you want.", ["State the purpose", "Keep a formal tone"]),
    ],
  },
  {
    id: "english-email",
    title: "Email Writing",
    subject: "english",
    category: "Writing",
    grades: G56,
    hook: "An email needs a subject line and a clear ask.",
    concepts: [
      C("english-email-clear", "Subject & Purpose", G56, "Would a busy adult know why you wrote from the subject line?", "Write a short email with a useful subject.", "Subject: Request for library books. Greeting, 3–5 sentences, thanks, name. Do not shout in ALL CAPS.", ["Write a subject line", "Write a polite ask"]),
    ],
  },
  {
    id: "english-notice",
    title: "Notice Writing",
    subject: "english",
    category: "Writing",
    grades: G56,
    hook: "A notice is a public, compact announcement.",
    concepts: [
      C("english-notice-facts", "Who, What, When, Where", G56, "What must a reader know to turn up?", "Write a notice with heading, date, and key facts.", "Heading, date, body with event, time, place, who should come. No story-style fluff.", ["Include time and place", "Keep it brief"]),
    ],
  },
  {
    id: "english-report",
    title: "Report Writing",
    subject: "english",
    category: "Writing",
    grades: G56,
    hook: "A report tells what happened in a clear, factual order.",
    concepts: [
      C("english-rep-facts", "Facts Before Flourishes", G56, "What would a reader need if they were not there?", "Write a short factual report.", "Headline or title, when/where, what happened, who was involved, outcome. Past tense. No invented drama.", ["Answer when/where/what", "Stay factual"]),
    ],
  },
  {
    id: "english-essay",
    title: "Essay Writing",
    subject: "english",
    category: "Writing",
    grades: G56,
    hook: "An essay develops one idea with an opening, middle, and close.",
    concepts: [
      C("english-essay-plan", "Plan Then Write", G56, "What is your one idea in a sentence?", "Plan an essay with introduction, body, conclusion.", "Introduction names the idea. Each body paragraph one point. Conclusion echoes without copying. Stay on the title.", ["Write a one-sentence idea", "List two body points"]),
    ],
  },
  {
    id: "english-opinion",
    title: "Opinion Writing",
    subject: "english",
    category: "Writing",
    grades: G456,
    hook: "Opinion writing says what you think and why.",
    concepts: [
      C("english-op-because", "Opinion + Reasons", G45, "Can you give two because reasons?", "State an opinion and support it.", "I think... because... For example... A second reason... Opinions still need reasons, not only feelings.", ["State an opinion", "Give two reasons"]),
    ],
  },
  {
    id: "english-argument",
    title: "Argument Writing",
    subject: "english",
    category: "Writing",
    grades: G6,
    hook: "Argument writing tries to convince with reasons and a fair look at the other side.",
    concepts: [
      C("english-arg-claim", "Claim, Reason, Counter", G6, "What would someone who disagrees say?", "Write a claim, reasons, and a short counterpoint.", "Claim. Because. Evidence or example. Some people say... however... Stay respectful.", ["Write a claim", "Answer a counterpoint"]),
    ],
  },
  {
    id: "english-editing",
    title: "Editing & Revising",
    subject: "english",
    category: "Writing",
    grades: G456,
    hook: "Revising improves ideas; editing cleans the surface.",
    concepts: [
      C("english-edit-revise", "Make It Clearer", G45, "Which sentence can you cut without losing the point?", "Revise for clarity and then edit mechanics.", "Revise: order, missing because, stronger verbs. Edit: spelling, capitals, punctuation. They are two different passes.", ["Cut a weak sentence", "Fix an end mark"]),
      C("english-edit-checklist", "A Writer's Checklist", G56, "Have you read it aloud once?", "Use a checklist before sharing.", "Read aloud. Check one idea per paragraph. Check their/there/they're. Ask: would a friend understand?", ["Read aloud", "Tick a checklist"]),
    ],
  },
  {
    id: "english-listening",
    title: "Listening Comprehension",
    subject: "english",
    category: "Speaking & Listening",
    grades: G456,
    hook: "Listening is catching meaning, not only waiting to talk.",
    concepts: [
      C("english-list-main", "Catch the Main Message", G4, "What was the speaker mainly asking you to do?", "Restate a spoken message.", "Listen for the purpose. Note a key word. Ask a clarifying question if you may.", ["Restate the message", "Ask to clarify"]),
      C("english-list-detail", "Important Details", G56, "Which detail would change what you do next?", "Note a detail that matters.", "Times, names, and because reasons often matter more than jokes around them.", ["Note a key detail", "Ignore a distraction"]),
    ],
  },
  {
    id: "english-conversation",
    title: "Conversation",
    subject: "english",
    category: "Speaking & Listening",
    grades: G456,
    hook: "Conversation is taking turns, building on ideas, and staying kind.",
    concepts: [
      C("english-conv-turns", "Taking Turns", G4, "How do you join without interrupting?", "Practise turn-taking and building on a partner's idea.", "Wait for a pause. I agree because... / I wonder... is kinder than talking over.", ["Wait and add", "Build on an idea"]),
    ],
  },
  {
    id: "english-asking",
    title: "Asking Questions",
    subject: "english",
    category: "Speaking & Listening",
    grades: G45,
    hook: "Good questions open doors; yes/no questions sometimes close them too soon.",
    concepts: [
      C("english-ask-open", "Open Questions", G4, "How is 'What happened next?' different from 'Did you like it?'?", "Ask an open question to learn more.", "Open questions often start with what, how, why. They invite a sentence, not only yes.", ["Ask a what/how question", "Follow a yes/no with why"]),
    ],
  },
  {
    id: "english-answering",
    title: "Answering Clearly",
    subject: "english",
    category: "Speaking & Listening",
    grades: G45,
    hook: "A clear answer names the point, then a because.",
    concepts: [
      C("english-ans-because", "Full Answers", G4, "Can you answer in a sentence, not a shrug?", "Answer in a complete sentence with a reason when asked.", "I chose the river path because it was shorter. Restate a bit of the question so listeners can follow.", ["Answer in a sentence", "Add because"]),
    ],
  },
  {
    id: "english-instructions",
    title: "Giving Instructions",
    subject: "english",
    category: "Speaking & Listening",
    grades: G456,
    hook: "Instructions work when the order is possible to follow.",
    concepts: [
      C("english-ins-steps", "Clear Steps", G45, "Could someone do this without watching you?", "Give ordered, specific steps.", "First, next, then, finally. Use exact words: fold in half, not do that thing. Check understanding.", ["Give three steps", "Use order words"]),
    ],
  },
  {
    id: "english-storytelling",
    title: "Storytelling",
    subject: "english",
    category: "Speaking & Listening",
    grades: G456,
    hook: "Spoken stories need a hook, a problem, and a voice the room can hear.",
    concepts: [
      C("english-tell-voice", "Tell It Aloud", G45, "Where will you pause for effect?", "Tell a short story with a beginning, problem, and end.", "Look at listeners. Speak slower than you think. Show the feeling in your voice, not only in the words.", ["Open with a moment", "End on purpose"]),
    ],
  },
  {
    id: "english-presentation",
    title: "Presentation",
    subject: "english",
    category: "Speaking & Listening",
    grades: G56,
    hook: "A presentation teaches an idea out loud, with a plan.",
    concepts: [
      C("english-pres-plan", "Opening, Points, Close", G56, "What should the audience remember in one sentence?", "Plan a short talk with a hook, two points, and a close.", "Tell them what you will tell them. Two clear points. End by restating the one sentence. Face the listeners.", ["Write a one-sentence message", "Plan two points"]),
    ],
  },
  {
    id: "english-opinions-speak",
    title: "Expressing Opinions",
    subject: "english",
    category: "Speaking & Listening",
    grades: G456,
    hook: "You can disagree without being unkind.",
    concepts: [
      C("english-op-speak", "I Think, I Hear You", G45, "How do you disagree and still stay a teammate?", "State an opinion and acknowledge another view.", "I think... because... I hear that you... Phrase banks beat insults.", ["State an opinion politely", "Acknowledge another view"]),
    ],
  },
  {
    id: "english-discussion",
    title: "Discussion",
    subject: "english",
    category: "Speaking & Listening",
    grades: G56,
    hook: "A discussion builds a shared idea, not a winner-takes-all fight.",
    concepts: [
      C("english-disc-build", "Building on Ideas", G56, "Can you add, not only repeat?", "Contribute, invite others, and stay on the question.", "Building on that... What do you think, [name]? Bring the group back if you wander.", ["Add to an idea", "Invite someone in"]),
    ],
  },
  {
    id: "english-debate",
    title: "Debate Basics",
    subject: "english",
    category: "Speaking & Listening",
    grades: G6,
    hook: "A debate has sides, reasons, and rules — not shouting.",
    concepts: [
      C("english-deb-side", "Claim and Rebuttal", G6, "What is one fair point the other side might make?", "Give a claim, a reason, and a short rebuttal.", "We should... because... The other side might say... however... Listen while they speak.", ["State a side", "Rebut politely"]),
    ],
  },
  {
    id: "english-communication",
    title: "Communication Skills",
    subject: "english",
    category: "Speaking & Listening",
    grades: G456,
    hook: "Communication is making sure the message that left you is the one that arrived.",
    concepts: [
      C("english-comm-audience", "Know Your Listener", G45, "Would you explain this the same way to a five-year-old and a teacher?", "Adjust words for the listener.", "Shorter words for a younger child. More precise words for a report. Eye contact and a kind tone help any audience.", ["Simplify for a younger listener", "Keep a respectful tone"]),
      C("english-comm-clarity", "Say It So They Can Do It", G56, "What would you check at the end?", "Close the loop: message, check, repair.", "After instructions, ask them to repeat the key step. If they misheard, rephrase, do not only repeat louder.", ["Check understanding", "Rephrase a mix-up"]),
    ],
  },
];

export const ENGLISH_WORLDS = compileWorlds(ENGLISH);
