import { equivalentFractionsExperience, placeValueExperience } from "@/content/curriculum/lessons";
import {
  C,
  G4,
  G45,
  G456,
  G56,
  G6,
  compileWorlds,
  type WorldSpec,
} from "@/content/curriculum/build";

const MATH: WorldSpec[] = [
  {
    id: "math-number-sense",
    title: "Number Sense",
    subject: "math",
    category: "Number",
    grades: G456,
    hook: "Numbers are names for how many, how much, and how far.",
    concepts: [
      C("math-ns-count", "Counting & Quantity", G4, "How do you know this handful is eight, not seven?", "Count objects and say how many there are.", "Counting matches each object to one number word in order. The last number said is the quantity.", ["Count a set", "Say how many"]),
      C("math-ns-read-write", "Reading & Writing Numbers", G45, "Can you read 3,046 out loud without mixing the places?", "Read and write numbers using digits and words.", "Each comma groups thousands. 3,046 is three thousand forty-six, not three hundred forty-six.", ["Read a number", "Write a number in words"]),
      C("math-ns-compose", "Composing Numbers", G45, "How many ways can you build 100 with tens and ones?", "Break numbers into tens and ones, or hundreds, tens, and ones.", "100 is 10 tens or 9 tens and 10 ones. Composing is putting parts back together.", ["Split a number", "Rebuild a number"]),
      C("math-ns-even-odd", "Even & Odd", G4, "Can you share 11 marbles equally between two friends?", "Tell even numbers from odd numbers.", "Even numbers make pairs with none left. Odd numbers leave one over.", ["Spot even numbers", "Spot odd numbers"]),
      C("math-ns-compare-sense", "Number Magnitude", G45, "Which is closer to 1,000: 870 or 1,200?", "Judge whether a number is large or small in context.", "Magnitude is about size, not just counting up. 1,200 is 200 above 1,000; 870 is 130 below.", ["Compare sizes", "Use a number line"]),
      C("math-ns-integers-intro", "Negative Numbers Intro", G6, "If the temperature is 3° below 0, how do we write it?", "Read simple negative numbers on a number line.", "Negatives sit to the left of zero. −3 is three steps below 0, not a subtraction sign floating alone.", ["Place negatives", "Read below zero"]),
    ],
  },
  {
    id: "math-place-value",
    title: "Place Value",
    subject: "math",
    category: "Number",
    grades: G456,
    hook: "A digit's job changes when it moves house.",
    concepts: [
      C("math-pv-ones-tens", "Ones & Tens", G4, "Why is 4 in 40 worth more than 4 in 4?", "Explain ones and tens places.", "In 40 the 4 is four tens. In 4 it is four ones. Same digit, different place, different value.", ["Name ones", "Name tens"]),
      C("math-pv-hundreds", "Hundreds", G4, "How many tens make a hundred?", "Use hundreds, tens, and ones.", "Ten tens make one hundred. 307 has 3 hundreds, 0 tens, and 7 ones.", ["Build hundreds", "Read 3-digit numbers"]),
      C("math-pv-thousands", "Thousands", G45, "What does the comma in 4,218 help you see?", "Read numbers to thousands and ten thousands.", "Each place is ten times the place to its right. The comma marks thousands.", ["Read thousands", "Write expanded form"], { experience: placeValueExperience }),
      C("math-pv-lakhs", "Indian Place Value", G56, "How is 1,00,000 different from 100,000 in commas?", "Use lakhs and Indian grouping.", "In the Indian system, 1,00,000 is one lakh. International 100,000 is the same amount with different commas.", ["Read lakhs", "Compare grouping"]),
      C("math-pv-expanded", "Expanded Form", G45, "Can you stretch 2,406 into hundreds and ones?", "Write expanded form and standard form.", "2,406 = 2,000 + 400 + 6. Expanded form shows the value of each digit.", ["Write expanded form", "Return to standard form"]),
      C("math-pv-rounding-place", "Rounding by Place", G56, "When a shop says 'about 2,000', which place did they look at?", "Round using a named place.", "Look at the digit one place to the right. 5 or more rounds up.", ["Round to tens", "Round to hundreds"]),
    ],
  },
  {
    id: "math-compare-order",
    title: "Comparing & Ordering Numbers",
    subject: "math",
    category: "Number",
    grades: G456,
    hook: "Greater, smaller, or the same — how do you know?",
    concepts: [
      C("math-co-symbols", "Greater & Less", G4, "Does 29 > 31 ever make sense?", "Use >, <, and = to compare whole numbers.", "Compare from the largest place. 31 has more tens than 29, so 31 is greater.", ["Use > and <", "Use ="]),
      C("math-co-order", "Ordering Numbers", G45, "Can you line up 108, 80, and 180 from smallest to largest?", "Order numbers on a line or in a list.", "Order means arranging by size. 80, 108, 180 rises because of hundreds then tens.", ["Order ascending", "Order descending"]),
      C("math-co-between", "Between & Around", G4, "What whole numbers sit between 40 and 45?", "Name numbers between two given numbers.", "Between 40 and 45 sit 41, 42, 43, 44. Endpoints are not between.", ["List between", "Spot neighbours"]),
      C("math-co-large", "Comparing Large Numbers", G56, "Which is greater: 99,999 or 100,001?", "Compare numbers with more digits.", "More digits in a whole number usually means greater, but always check the leftmost place.", ["Compare 5-digit numbers", "Explain a comparison"]),
    ],
  },
  {
    id: "math-estimation",
    title: "Estimation & Rounding",
    subject: "math",
    category: "Number",
    grades: G456,
    hook: "Sometimes 'about' is wiser than an exact pile of digits.",
    concepts: [
      C("math-est-round-ten", "Rounding to Ten", G45, "Is 47 closer to 40 or 50?", "Round whole numbers to the nearest ten.", "Look at ones. 5 or more goes up. 47 rounds to 50.", ["Round up", "Round down"]),
      C("math-est-round-hundred", "Rounding to Hundred", G45, "Is 249 closer to 200 or 300?", "Round to the nearest hundred.", "Look at tens. 249 has 4 tens, so it stays 200.", ["Round hundreds", "Explain the digit you used"]),
      C("math-est-front", "Front-End Estimation", G56, "If pencils cost ₹18, about how much are 6?", "Estimate products and sums with friendly numbers.", "Use the front digits: 6 × 20 is 120, a sensible estimate for 6 × 18.", ["Estimate a sum", "Estimate a product"]),
      C("math-est-reason", "Sensible Estimates", G56, "Would you estimate a classroom as 10 children or 10,000?", "Judge whether an estimate is reasonable.", "An estimate should fit the story. 10,000 children cannot sit in one classroom.", ["Check reasonableness", "Choose a unit"]),
    ],
  },
  {
    id: "math-addition",
    title: "Addition",
    subject: "math",
    category: "Operations",
    grades: G456,
    hook: "Addition puts amounts together.",
    concepts: [
      C("math-add-meaning", "What Addition Means", G4, "If 8 children join 5, is that adding or multiplying?", "Describe addition as combining or adding on.", "Addition finds a total. 8 + 5 is joining two groups.", ["Join groups", "Add on"]),
      C("math-add-facts", "Addition Facts", G4, "What pairs make 10?", "Recall addition facts to 20.", "Facts like 7 + 3 = 10 free your mind for larger problems.", ["Make 10", "Add within 20"]),
      C("math-add-regroup", "Regrouping in Addition", G45, "What happens when ones add to 14?", "Add with regrouping.", "14 ones become 1 ten and 4 ones. That ten moves to the tens place.", ["Regroup ones", "Add 2-digit numbers"]),
      C("math-add-large", "Larger Sums", G56, "How do you keep places lined up in 4,086 + 759?", "Add multi-digit numbers accurately.", "Line up ones under ones. Add from the right, regrouping as needed.", ["Add 4-digit numbers", "Check a sum"]),
      C("math-add-properties", "Properties of Addition", G56, "Does 9 + 4 equal 4 + 9?", "Use commutative and associative ideas.", "Order and grouping of addends do not change the sum. 9 + 4 = 4 + 9.", ["Swap addends", "Group addends"]),
    ],
  },
  {
    id: "math-subtraction",
    title: "Subtraction",
    subject: "math",
    category: "Operations",
    grades: G456,
    hook: "Subtraction finds what is left, how far, or how much more.",
    concepts: [
      C("math-sub-meaning", "What Subtraction Means", G4, "Is 'how many more' a subtraction idea?", "See subtraction as take away, compare, or missing addend.", "12 − 5 can mean 5 left, or how far 5 is from 12.", ["Take away", "Compare two amounts"]),
      C("math-sub-facts", "Subtraction Facts", G4, "What is 10 minus 6 in your head?", "Use subtraction facts related to addition.", "If 6 + 4 = 10, then 10 − 6 = 4. Facts come in families.", ["Related facts", "Subtract within 20"]),
      C("math-sub-regroup", "Regrouping in Subtraction", G45, "How do you subtract 9 from 3 in the ones place?", "Subtract with regrouping.", "Ungroup a ten into 10 ones. Then 13 − 9 is possible.", ["Ungroup a ten", "Subtract 2-digit numbers"]),
      C("math-sub-large", "Larger Differences", G56, "What if there is a zero in the tens place?", "Subtract across zeros.", "5,000 − 276 needs careful ungrouping through zeros.", ["Subtract across zero", "Check with addition"]),
    ],
  },
  {
    id: "math-multiplication",
    title: "Multiplication",
    subject: "math",
    category: "Operations",
    grades: G456,
    hook: "Multiplication is equal groups, arrays, and scaling.",
    concepts: [
      C("math-mul-groups", "Equal Groups", G4, "Three bags with 4 apples — add or multiply?", "See multiplication as equal groups.", "3 × 4 means 3 groups of 4. It is repeated addition, faster.", ["Draw equal groups", "Write a multiplication"]),
      C("math-mul-tables", "Multiplication Tables", G45, "Why do people learn 7 × 8 by heart?", "Use tables through 10 × 10.", "Known facts let you solve bigger problems without counting by ones.", ["Recall tables", "Use a fact you know"]),
      C("math-mul-array", "Arrays", G45, "A 5 by 6 tray of eggs — what multiplication is that?", "Connect arrays to multiplication.", "5 rows of 6 is 5 × 6. Turning the tray is 6 × 5, same total.", ["Read an array", "Turn an array"]),
      C("math-mul-algorithm", "Multi-digit Multiplication", G56, "How do you multiply 24 × 6 without 24 sixes?", "Multiply 2-digit by 1-digit and 2-digit by 2-digit.", "Multiply ones, then tens, then add the partial products.", ["Multiply by 1 digit", "Use partial products"]),
      C("math-mul-properties", "Properties of Multiplication", G56, "Is 7 × 1 still 7?", "Use 0, 1, commutative, and distributive ideas.", "×1 leaves a number the same. ×0 is 0. 7 × 8 = 7 × 5 + 7 × 3.", ["Use ×1 and ×0", "Split a factor"]),
    ],
  },
  {
    id: "math-division",
    title: "Division",
    subject: "math",
    category: "Operations",
    grades: G456,
    hook: "Division shares equally or measures how many groups.",
    concepts: [
      C("math-div-share", "Sharing Equally", G4, "12 sweets, 4 children — how do you share fairly?", "Divide by sharing into equal groups.", "12 ÷ 4 = 3 means each share is 3 if sharing is equal.", ["Share equally", "Write a division"]),
      C("math-div-measure", "How Many Groups", G45, "How many 5-seater cars for 20 children?", "Divide by measuring equal groups.", "20 ÷ 5 = 4 groups. Division asks how many groups of 5 fit.", ["Measure groups", "Use skip counting"]),
      C("math-div-remainder", "Remainders", G45, "17 books in boxes of 5 — what is left over?", "Interpret remainders in a story.", "17 ÷ 5 is 3 remainder 2. The leftover 2 may still need a box in real life.", ["Find a remainder", "Explain leftover"]),
      C("math-div-long", "Longer Division", G56, "How do you divide 144 by 12?", "Divide 2- and 3-digit numbers.", "Division undoes multiplication. 12 × 12 = 144, so 144 ÷ 12 = 12.", ["Divide 3-digit numbers", "Check with multiplication"]),
    ],
  },
  {
    id: "math-factors",
    title: "Factors",
    subject: "math",
    category: "Number",
    grades: G56,
    hook: "Factors are the numbers that fit inside another number without leftovers.",
    concepts: [
      C("math-fac-factors", "Finding Factors", G56, "Which numbers multiply to 12?", "List factors of a number.", "Factors of 12 are 1, 2, 3, 4, 6, 12. They divide 12 with no remainder.", ["List factors", "Use arrays"]),
      C("math-fac-pairs", "Factor Pairs", G56, "What pair with 4 makes 12?", "Write factor pairs.", "12 = 1 × 12, 2 × 6, 3 × 4. Pairs keep multiplication honest.", ["Write factor pairs", "Check with multiplication"]),
    ],
  },
  {
    id: "math-multiples",
    title: "Multiples",
    subject: "math",
    category: "Number",
    grades: G45,
    hook: "Multiples are what you land on when you skip-count.",
    concepts: [
      C("math-fac-multiples", "Naming Multiples", G45, "Is 35 a multiple of 7?", "Name multiples of 2, 5, 10, and other small numbers.", "Multiples of 7 are 7, 14, 21... 35 is 7 × 5, so yes.", ["Skip count", "Spot a multiple"]),
      C("math-fac-common-multiples", "Common Multiples", G45, "When do 4 and 6 meet on a number line?", "Find a common multiple of two numbers.", "4, 8, 12... and 6, 12, 18... meet at 12.", ["List two sequences", "Name a common multiple"]),
    ],
  },
  {
    id: "math-prime",
    title: "Prime & Composite Numbers",
    subject: "math",
    category: "Number",
    grades: G56,
    hook: "Primes have a very small factor family.",
    concepts: [
      C("math-fac-prime", "Prime & Composite", G56, "Is 9 prime because it is odd?", "Tell primes from composite numbers.", "Primes have exactly two factors: 1 and themselves. 9 is 3 × 3, so composite. 2 is the even prime.", ["Spot primes", "Spot composites"]),
      C("math-fac-one", "Why 1 Is Special", G6, "Is 1 prime, composite, or neither?", "Explain that 1 is neither prime nor composite.", "1 has only one factor — itself. Primes need exactly two. So 1 sits aside.", ["Say 1 is not prime", "Give the two-factor rule"]),
    ],
  },
  {
    id: "math-divisibility",
    title: "Divisibility",
    subject: "math",
    category: "Number",
    grades: G56,
    hook: "Divisibility tests let you peek without long division.",
    concepts: [
      C("math-fac-divisibility", "Tests for 2, 5, and 10", G56, "How can you tell 246 is divisible by 2?", "Use digit tests for 2, 5, and 10.", "Even ones digit means divisible by 2. 0 or 5 ones means 5. 0 ones means 10.", ["Test for 2", "Test for 5 and 10"]),
      C("math-fac-div-three", "Tests for 3 and 9", G56, "How can you tell 246 is divisible by 3 without dividing?", "Use digit-sum tests for 3 and 9.", "A number is divisible by 3 if its digits add to a multiple of 3. 2+4+6=12.", ["Test for 3", "Test for 9"]),
    ],
  },
  {
    id: "math-hcf",
    title: "HCF",
    subject: "math",
    category: "Number",
    grades: G56,
    hook: "HCF is the largest number that divides both.",
    concepts: [
      C("math-fac-hcf", "Highest Common Factor", G56, "What is the largest number that divides both 12 and 18?", "Find the highest common factor.", "Common factors of 12 and 18 include 1, 2, 3, 6. The highest is 6.", ["List common factors", "Name the HCF"]),
    ],
  },
  {
    id: "math-lcm",
    title: "LCM",
    subject: "math",
    category: "Number",
    grades: G56,
    hook: "LCM is the smallest shared multiple — when things next line up.",
    concepts: [
      C("math-fac-lcm", "Least Common Multiple", G56, "When do two flashing lights blink together again?", "Find the least common multiple.", "LCM of 4 and 6 is 12, the smallest shared multiple.", ["List multiples", "Name the LCM"]),
    ],
  },
  {
    id: "math-number-patterns",
    title: "Number Patterns",
    subject: "math",
    category: "Number",
    grades: G456,
    hook: "A pattern is a rule you can ride forward.",
    concepts: [
      C("math-pat-skip", "Skip Counting Patterns", G4, "What comes after 5, 10, 15...?", "Continue skip-counting sequences.", "The rule is +5. Next is 20. Saying the rule keeps the pattern honest.", ["Name the rule", "Continue the sequence"]),
      C("math-pat-growing", "Growing Patterns", G45, "2, 4, 8, 16 — what is happening?", "Describe growing number patterns.", "Each term doubles. The rule is ×2, not +2.", ["Find a multiplier", "Predict a term"]),
      C("math-pat-input-output", "Input–Output Rules", G56, "A machine adds 7. What comes out if 9 goes in?", "Use a simple function rule.", "If the rule is +7, 9 becomes 16. Tables of in and out show the rule.", ["Apply a rule", "Guess a rule"]),
    ],
  },
  {
    id: "math-fractions",
    title: "Fractions",
    subject: "math",
    category: "Fractions & Decimals",
    grades: G456,
    hook: "Fractions name equal parts of a whole or a set.",
    concepts: [
      C("math-frac-meaning", "Understanding Fractions", G4, "If a roti is cut into 4 equal parts, what is one part called?", "Explain a fraction as equal parts of a whole.", "The denominator names equal parts. The numerator names how many parts you have. Unequal cuts are not fair fractions.", ["Name equal parts", "Point to numerator and denominator"]),
      C("math-frac-identify", "Identifying Fractions", G4, "Which picture shows 3/4?", "Identify unit and non-unit fractions.", "3/4 means three of four equal parts. 1/4 is a unit fraction.", ["Identify a fraction", "Draw a fraction"]),
      C("equivalent-fractions", "Equivalent Fractions", G456, "Do 1/2 and 2/4 name the same amount of sandwich?", "Find and explain equivalent fractions.", "Equivalent fractions are different names for the same amount. Multiply or divide top and bottom by the same number.", ["Find an equivalent fraction", "Explain why they match"], { experience: equivalentFractionsExperience }),
      C("math-frac-compare", "Comparing Simple Fractions", G45, "Which is larger, 1/2 or 1/3 of the same cake?", "Compare fractions with the same whole.", "With the same whole, a smaller denominator means larger pieces. 1/2 is larger than 1/3.", ["Compare unit fractions", "Compare like denominators"]),
      C("math-frac-add-like", "Adding & Subtracting Like Fractions", G45, "What is 2/8 + 3/8?", "Add and subtract fractions with the same denominator.", "Keep the denominator. Add the numerators: 2/8 + 3/8 = 5/8.", ["Add like fractions", "Subtract like fractions"]),
      C("math-frac-mixed", "Mixed Numbers", G56, "How do you write 1 and 1/2 as an improper fraction?", "Convert mixed numbers and improper fractions.", "1 1/2 is 3/2. Mixed numbers join a whole and a part.", ["Write mixed numbers", "Convert to improper"]),
      C("math-frac-operations", "Fraction Operations", G56, "How do you add 1/2 and 1/3?", "Add, subtract, and multiply simple fractions.", "Unlike denominators need a common denominator. 1/2 + 1/3 = 3/6 + 2/6 = 5/6.", ["Add unlike fractions", "Multiply a fraction by a whole number"]),
      C("math-frac-word", "Fraction Word Problems", G56, "A recipe needs 3/4 cup and you have 1/2. How much more?", "Solve fraction stories with a diagram.", "3/4 − 1/2 = 3/4 − 2/4 = 1/4 cup more.", ["Draw the story", "Choose an operation"]),
      C("math-frac-links", "Fractions, Decimals & Percent", G6, "Is 1/2 the same as 0.5 and 50%?", "Connect fractions to decimals and percentages.", "1/2 = 0.5 = 50%. Different languages for the same amount.", ["Match 1/2 to 0.5", "Match 1/4 to 25%"]),
    ],
  },
  {
    id: "math-decimals",
    title: "Decimals",
    subject: "math",
    category: "Fractions & Decimals",
    grades: G456,
    hook: "The decimal point continues place value to the right of one.",
    concepts: [
      C("math-dec-tenths", "Tenths", G45, "What does 0.3 mean on a 10-part bar?", "Read tenths as fractions of one.", "0.3 is 3 tenths, or 3/10. The first place after the point is tenths.", ["Read tenths", "Write tenths"]),
      C("math-dec-hundredths", "Hundredths", G56, "Is 0.40 the same as 0.4?", "Read hundredths and compare decimals.", "0.40 is 40 hundredths, equal to 4 tenths. Extra zeros after the last non-zero can hold place.", ["Read hundredths", "Compare decimals"]),
      C("math-dec-add", "Adding Decimals", G56, "Why line up the decimal points?", "Add and subtract decimals.", "Points mark ones. 1.5 + 0.25 needs tenths under tenths.", ["Add decimals", "Subtract decimals"]),
      C("math-dec-money", "Decimals in Money", G56, "Why does ₹7.50 have two places?", "Use decimals for rupees and paise.", "Paise are hundredths of a rupee. ₹7.50 is 7 rupees and 50 paise.", ["Read money", "Add money amounts"]),
    ],
  },
  {
    id: "math-percentages",
    title: "Percentages",
    subject: "math",
    category: "Fractions & Decimals",
    grades: G56,
    hook: "Percent means per hundred.",
    concepts: [
      C("math-pct-meaning", "What Percent Means", G56, "If 50% of a class of 40 stand up, how many stand?", "Explain percent as parts per 100.", "50% is 50 per 100, or half. Half of 40 is 20.", ["Read a percent", "Find a simple percent"]),
      C("math-pct-links", "Percent, Fractions, Decimals", G6, "Is 25% the same as 1/4?", "Convert among percent, fraction, and decimal.", "25% = 25/100 = 1/4 = 0.25.", ["Convert 50%", "Convert 25%"]),
      C("math-pct-problems", "Percent Problems", G6, "A shirt of ₹400 is 10% off. How much is off?", "Find a percent of an amount.", "10% of 400 is 40. The discount is ₹40.", ["Find 10%", "Find 50%"]),
    ],
  },
  {
    id: "math-ratio",
    title: "Ratio & Proportion",
    subject: "math",
    category: "Fractions & Decimals",
    grades: G6,
    hook: "A ratio compares two quantities in the same kind of unit.",
    concepts: [
      C("math-ratio-meaning", "What a Ratio Is", G6, "If there are 2 cups of rice to 1 cup of water, how do we write that?", "Write a ratio and explain it.", "2 : 1 means two parts rice for one part water. Order matters.", ["Write a ratio", "Explain order"]),
      C("math-ratio-equivalent", "Equivalent Ratios", G6, "Is 4:2 the same comparison as 2:1?", "Find equivalent ratios.", "Multiply or divide both parts by the same number. 2:1 = 4:2 = 6:3.", ["Scale a ratio", "Simplify a ratio"]),
      C("math-ratio-proportion", "Proportion", G6, "If 2 pencils cost ₹10, what do 6 cost at the same rate?", "Solve simple proportions.", "The rate stays the same. 2:10 = 6:30, so ₹30.", ["Find a missing term", "Use a rate"]),
    ],
  },
  {
    id: "math-money",
    title: "Money",
    subject: "math",
    category: "Measurement",
    grades: G456,
    hook: "Rupees and paise are a decimal system you already use.",
    concepts: [
      C("math-money-count", "Counting Money", G4, "How do you make ₹20 with notes and coins?", "Count mixed notes and coins.", "Group coins into rupees. 100 paise make ₹1.", ["Count coins", "Make an amount"]),
      C("math-money-add", "Money Calculations", G45, "You have ₹50 and spend ₹28. What remains?", "Add and subtract money.", "Subtract paise then rupees, or think in paise. ₹50 − ₹28 = ₹22.", ["Add money", "Give change"]),
      C("math-money-bills", "Bills & Change", G56, "A bill is ₹137. You pay ₹200. How much change?", "Calculate change from a note.", "200 − 137 = 63. Check by adding change back to the bill.", ["Find change", "Check a bill"]),
    ],
  },
  {
    id: "math-time",
    title: "Time",
    subject: "math",
    category: "Measurement",
    grades: G456,
    hook: "Time is a circle of 60, not a ten.",
    concepts: [
      C("math-time-clock", "Reading a Clock", G4, "Where is the hour hand at half past 3?", "Read hours and half hours, then minutes.", "At half past 3 the hour hand sits halfway to 4. The minute hand is at 6.", ["Read hour and half hour", "Read minutes"]),
      C("math-time-elapsed", "Elapsed Time", G45, "A film starts at 4:20 and ends at 5:05. How long is it?", "Find duration between two times.", "From 4:20 to 5:00 is 40 minutes, plus 5 is 45 minutes.", ["Find duration", "Count on a clock"]),
      C("math-time-24h", "24-Hour Clock", G56, "What is 15:00 in the 12-hour clock?", "Convert 12-hour and 24-hour time.", "15:00 is 3:00 p.m. Subtract 12 from hours after 12:00.", ["Read 24-hour time", "Convert to a.m./p.m."]),
      C("math-time-calendar", "Calendar", G4, "How many days is a week? A year?", "Use days, weeks, months.", "7 days make a week. A common year has 365 days.", ["Read a calendar", "Count weeks"]),
    ],
  },
  {
    id: "math-measurement",
    title: "Measurement",
    subject: "math",
    category: "Measurement",
    grades: G456,
    hook: "We measure so we can compare fairly.",
    concepts: [
      C("math-mea-length", "Length", G45, "When do you use centimetres instead of metres?", "Measure length in cm, m, and km.", "100 cm = 1 m. 1,000 m = 1 km. Choose a unit that fits the object.", ["Measure in cm", "Convert m and cm"]),
      C("math-mea-mass", "Mass", G45, "Is a watermelon closer to 200 g or 2 kg?", "Use grams and kilograms.", "1,000 g = 1 kg. A watermelon is about 2 kg, not 200 g.", ["Compare mass", "Choose g or kg"]),
      C("math-mea-capacity", "Capacity", G45, "How many millilitres in a litre?", "Use millilitres and litres.", "1,000 ml = 1 l. A teaspoon is millilitres; a bottle is litres.", ["Compare capacity", "Convert ml and l"]),
      C("math-mea-tools", "Choosing Tools", G4, "Would you measure a pencil with a metre rod or a 15 cm ruler?", "Choose a sensible measuring tool and unit.", "The tool should fit the size. A pencil matches a ruler in centimetres.", ["Choose a tool", "Choose a unit"]),
    ],
  },
  {
    id: "math-perimeter",
    title: "Perimeter",
    subject: "math",
    category: "Measurement",
    grades: G456,
    hook: "Perimeter is the distance around.",
    concepts: [
      C("math-per-meaning", "What Perimeter Is", G4, "If an ant walks the edge of a book, what is it measuring?", "Define perimeter as the boundary length.", "Add the side lengths. A rectangle 8 cm by 3 cm has perimeter 22 cm.", ["Walk the edge", "Add sides"]),
      C("math-per-rect", "Perimeter of Rectangles", G45, "Do you need all four sides, or will two do?", "Use length and breadth.", "P = 2 × (l + b). Opposite sides are equal.", ["Use 2(l+b)", "Find a missing side"]),
      C("math-per-composite", "Around Composite Shapes", G56, "An L-shape garden — which edges are outside?", "Find perimeter of simple composite shapes.", "Add every outer edge. Inner cuts that are not outer boundary are not perimeter.", ["Trace the outside", "Add outer edges"]),
    ],
  },
  {
    id: "math-area",
    title: "Area",
    subject: "math",
    category: "Measurement",
    grades: G456,
    hook: "Area is how much surface a shape covers.",
    concepts: [
      C("math-area-squares", "Counting Squares", G4, "How many square tiles cover this rectangle?", "Measure area by counting unit squares.", "A 3 by 4 rectangle covers 12 squares. Area is counted in square units.", ["Count squares", "Use square centimetres"]),
      C("math-area-rect", "Area of a Rectangle", G45, "Why multiply length by breadth?", "Use A = l × b.", "Each row has l squares and there are b rows, so l × b.", ["Multiply length and breadth", "Find a missing side"]),
      C("math-area-composite", "Composite Area", G56, "Can you split an L into two rectangles?", "Add or subtract rectangular areas.", "Split, find each area, then add. Do not count an overlap twice.", ["Split a shape", "Add areas"]),
    ],
  },
  {
    id: "math-volume",
    title: "Volume",
    subject: "math",
    category: "Measurement",
    grades: G56,
    hook: "Volume is the space inside a 3D object.",
    concepts: [
      C("math-vol-cubes", "Counting Cubes", G56, "How many unit cubes fill this box?", "Find volume by packing unit cubes.", "A 2 by 3 by 4 box holds 24 cubes. Volume uses cubic units.", ["Count cubes", "Layer the box"]),
      C("math-vol-cuboid", "Volume of a Cuboid", G6, "Why multiply three lengths?", "Use V = l × b × h.", "Length, breadth, and height of the layers multiply to the number of cubes.", ["Use l×b×h", "Choose cubic units"]),
    ],
  },
  {
    id: "math-geometry",
    title: "Geometry",
    subject: "math",
    category: "Geometry",
    grades: G456,
    hook: "Geometry is the language of shape and space.",
    concepts: [
      C("math-geo-point-line", "Points & Lines", G4, "How thin is a point?", "Use point, line, ray, and line segment.", "A point has position, not size. A segment has two ends. A ray has one. A line goes on.", ["Name a point", "Name a segment"]),
      C("math-geo-plane", "Shapes on a Plane", G45, "What makes a shape 2D?", "Describe plane figures.", "2D shapes have length and breadth, not thickness you can pick up like a box.", ["Spot 2D shapes", "Name sides and vertices"]),
      C("math-geo-nets", "Nets Intro", G6, "Can you fold this drawing into a cube?", "Match simple nets to 3D shapes.", "A net is a 2D unfolding. A cube net has 6 squares in a foldable pattern.", ["Spot a cube net", "Reject an impossible net"]),
    ],
  },
  {
    id: "math-angles",
    title: "Angles",
    subject: "math",
    category: "Geometry",
    grades: G456,
    hook: "An angle is a turn between two rays.",
    concepts: [
      C("math-ang-meaning", "What an Angle Is", G45, "Where is the angle in a clock at 3:00?", "Identify angles in objects and drawings.", "Two hands from the same centre make an angle. 3:00 is a right angle.", ["Spot an angle", "Name the vertex"]),
      C("math-ang-types", "Right, Acute, Obtuse", G45, "Is every corner of a door a right angle?", "Classify angles.", "A right angle is a square corner. Acute is smaller; obtuse is larger but less than a straight line.", ["Spot right angles", "Sort acute and obtuse"]),
      C("math-ang-measure", "Measuring Angles", G56, "What does a protractor's 90 mean?", "Measure angles in degrees.", "A full turn is 360°. A right angle is 90°. Place the protractor centre on the vertex.", ["Read a protractor", "Estimate an angle"]),
    ],
  },
  {
    id: "math-lines",
    title: "Lines",
    subject: "math",
    category: "Geometry",
    grades: G456,
    hook: "Lines can meet, never meet, or cross at right angles.",
    concepts: [
      C("math-lin-parallel", "Parallel Lines", G45, "Do railway tracks meet in the real world in front of you?", "Identify parallel lines.", "Parallel lines keep the same distance and never meet. Tracks look parallel.", ["Spot parallel lines", "Draw parallels"]),
      C("math-lin-perpendicular", "Perpendicular Lines", G45, "What kind of meeting makes a plus sign?", "Identify perpendicular lines.", "Perpendicular lines meet at a right angle. Window frames often do.", ["Spot perpendiculars", "Mark a right angle"]),
      C("math-lin-intersect", "Intersecting Lines", G56, "If two lines cross, how many angles appear?", "Describe intersecting lines.", "Two crossing lines make four angles. Opposite angles are equal.", ["Name intersecting lines", "Spot opposite angles"]),
    ],
  },
  {
    id: "math-triangles",
    title: "Triangles",
    subject: "math",
    category: "Geometry",
    grades: G456,
    hook: "Three sides, three angles, many personalities.",
    concepts: [
      C("math-tri-sides", "By Sides", G45, "Can a triangle have all sides equal?", "Classify triangles by sides.", "Equilateral has 3 equal sides, isosceles 2, scalene none equal.", ["Spot equilateral", "Spot scalene"]),
      C("math-tri-angles", "By Angles", G56, "Can a triangle have two right angles?", "Classify triangles by angles.", "A triangle's angles add to 180°. Two right angles would already be 180°, leaving 0 — impossible.", ["Spot right triangles", "Use angle sum"]),
      C("math-tri-sum", "Angle Sum", G6, "If two angles are 40° and 60°, what is the third?", "Use the 180° sum.", "40 + 60 = 100, so the third is 80°.", ["Find a missing angle", "Check the sum"]),
    ],
  },
  {
    id: "math-quadrilaterals",
    title: "Quadrilaterals",
    subject: "math",
    category: "Geometry",
    grades: G456,
    hook: "Four sides can make a square, a kite, or a wild four-sided shape.",
    concepts: [
      C("math-quad-square-rect", "Squares & Rectangles", G45, "Is every square a rectangle?", "Describe squares and rectangles.", "A rectangle has four right angles. A square is a rectangle with equal sides.", ["Spot a square", "Spot a rectangle"]),
      C("math-quad-para-rhombus", "Parallelogram & Rhombus", G56, "Do both pairs of sides stay parallel?", "Describe parallelograms and rhombuses.", "A parallelogram has two pairs of parallel sides. A rhombus has all sides equal.", ["Spot a parallelogram", "Spot a rhombus"]),
      C("math-quad-trapezium", "Trapezium", G56, "What if only one pair of sides is parallel?", "Identify a trapezium.", "A trapezium (trapezoid) has exactly one pair of parallel sides in many school definitions.", ["Spot a trapezium", "Name the parallel pair"]),
    ],
  },
  {
    id: "math-polygons",
    title: "Polygons",
    subject: "math",
    category: "Geometry",
    grades: G56,
    hook: "A polygon is a closed shape with straight sides.",
    concepts: [
      C("math-poly-names", "Naming Polygons", G56, "What do we call a five-sided shape?", "Name pentagon, hexagon, octagon.", "Penta means five, hexa six, octa eight. Count the sides.", ["Count sides", "Name the polygon"]),
      C("math-poly-regular", "Regular Polygons", G6, "Does regular mean 'ordinary'?", "Describe regular polygons.", "Regular means all sides equal and all angles equal. A stop sign is a regular octagon.", ["Spot regular", "Spot irregular"]),
    ],
  },
  {
    id: "math-circles",
    title: "Circles",
    subject: "math",
    category: "Geometry",
    grades: G456,
    hook: "Every point on a circle is the same distance from the centre.",
    concepts: [
      C("math-cir-parts", "Centre, Radius, Diameter", G45, "How many radii make a diameter?", "Name radius, diameter, and circumference.", "Diameter is twice the radius and passes through the centre.", ["Name the radius", "Name the diameter"]),
      C("math-cir-compass", "Drawing Circles", G56, "What must stay the same while the pencil turns?", "Draw a circle with a compass.", "Keep the centre pin still and the radius fixed. That equal distance makes the circle.", ["Set a radius", "Draw a circle"]),
    ],
  },
  {
    id: "math-symmetry",
    title: "Symmetry",
    subject: "math",
    category: "Geometry",
    grades: G456,
    hook: "A line of symmetry is a fold that matches both halves.",
    concepts: [
      C("math-sym-line", "Line Symmetry", G45, "How many fold lines does a square have?", "Find lines of symmetry.", "A square has 4. A rectangle that is not a square has 2. A scalene triangle has 0.", ["Draw a fold line", "Count lines"]),
      C("math-sym-reflection", "Reflection", G56, "If you flip a letter b over a line, what might you see?", "Describe reflection.", "Reflection flips a shape over a line. Distances to the line stay equal.", ["Reflect a shape", "Check distances"]),
    ],
  },
  {
    id: "math-2d-shapes",
    title: "2D Shapes",
    subject: "math",
    category: "Geometry",
    grades: G456,
    hook: "Flat shapes live on a page.",
    concepts: [
      C("math-2d-sort", "Sorting 2D Shapes", G4, "What do a triangle and a square share?", "Sort shapes by sides and corners.", "Both are closed and straight-sided. They differ in number of sides.", ["Count sides", "Count vertices"]),
      C("math-2d-properties", "Properties", G45, "Does a rectangle need equal sides?", "Use properties to justify a name.", "A rectangle needs four right angles. Equal sides make it a square too.", ["Use properties", "Name a shape"]),
    ],
  },
  {
    id: "math-3d-shapes",
    title: "3D Shapes",
    subject: "math",
    category: "Geometry",
    grades: G456,
    hook: "Solid shapes take up space.",
    concepts: [
      C("math-3d-names", "Cubes, Cuboids, Spheres", G4, "Is a ball a circle or a sphere?", "Name common 3D shapes.", "A circle is 2D. A ball is a sphere. A dice is a cube.", ["Name 3D shapes", "Match objects"]),
      C("math-3d-faces", "Faces, Edges, Vertices", G45, "How many faces does a cube have?", "Count faces, edges, and vertices.", "A cube has 6 faces, 12 edges, 8 vertices. All faces are squares.", ["Count faces", "Count edges"]),
      C("math-3d-prisms", "Prisms & Pyramids", G56, "What is the same along a triangular prism?", "Distinguish prisms and pyramids.", "A prism has two matching ends. A pyramid comes to a point.", ["Spot a prism", "Spot a pyramid"]),
    ],
  },
  {
    id: "math-data",
    title: "Data Handling",
    subject: "math",
    category: "Data",
    grades: G456,
    hook: "Data is information we collect to answer a question.",
    concepts: [
      C("math-data-collect", "Collecting Data", G4, "How would you find the class favourite fruit?", "Collect and tally data.", "A tally marks each vote. Four lines and a diagonal make five.", ["Make a tally", "Ask a question"]),
      C("math-data-pictograph", "Pictographs", G45, "If one mango picture means 2 children, what do 3 pictures mean?", "Read a pictograph.", "Read the key. 3 pictures × 2 = 6 children.", ["Read a key", "Read a pictograph"]),
      C("math-data-bar", "Bar Graphs", G56, "Which bar is tallest, and what does that mean?", "Read a bar graph.", "Taller bars mean greater frequency. Read the scale on the axis.", ["Read a bar graph", "Compare bars"]),
    ],
  },
  {
    id: "math-tables",
    title: "Tables",
    subject: "math",
    category: "Data",
    grades: G456,
    hook: "A table organises information in rows and columns.",
    concepts: [
      C("math-tab-read", "Reading Tables", G4, "Where do you look for Monday's rainfall?", "Read a simple table.", "Find the row and column that meet. Their cell is the answer.", ["Find a cell", "Read a row"]),
      C("math-tab-make", "Making Tables", G45, "How do you record 4 sports and their votes?", "Organise data in a table.", "Headers name categories. Each row is one item.", ["Write headers", "Fill a table"]),
    ],
  },
  {
    id: "math-graphs",
    title: "Graphs",
    subject: "math",
    category: "Data",
    grades: G56,
    hook: "A graph turns numbers into a picture you can compare.",
    concepts: [
      C("math-grp-bar", "Drawing Bar Graphs", G56, "What if the scale is 1 square = 5 votes?", "Draw a bar graph from a table.", "Choose a scale so bars fit. Label axes.", ["Choose a scale", "Draw bars"]),
      C("math-grp-line", "Line Graphs Intro", G6, "Why connect the points for temperature across a day?", "Read a simple line graph.", "Line graphs show change over time. The slope tells whether values rise or fall.", ["Read a trend", "Read a point"]),
    ],
  },
  {
    id: "math-average",
    title: "Average",
    subject: "math",
    category: "Data",
    grades: G6,
    hook: "An average is a fair share of a total.",
    concepts: [
      C("math-avg-mean", "Mean as Fair Share", G6, "Four scores 2, 4, 4, 6 — what is a fair share?", "Find the arithmetic mean.", "Add, then divide by how many numbers. (2+4+4+6)/4 = 4.", ["Add the data", "Divide by the count"]),
      C("math-avg-story", "Average Stories", G6, "If the average of 3 tests is 8, what is the total?", "Use mean in a story.", "Total = mean × count. 8 × 3 = 24 marks in all.", ["Find a total", "Find a missing value"]),
    ],
  },
  {
    id: "math-probability",
    title: "Probability Basics",
    subject: "math",
    category: "Data",
    grades: G56,
    hook: "Some events are certain, some impossible, some in between.",
    concepts: [
      C("math-prob-language", "Certain, Likely, Impossible", G56, "Is it certain you will toss heads?", "Use chance language.", "Heads or tails is equally likely if the coin is fair. Tuesday after Monday is certain.", ["Use chance words", "Sort events"]),
      C("math-prob-simple", "Simple Chance", G6, "A bag has 3 red and 1 blue. Which colour is more likely?", "Compare simple chances.", "More reds make red more likely. Chance can be written as a fraction of equally likely outcomes.", ["Compare likelihood", "Count outcomes"]),
    ],
  },
  {
    id: "math-patterns",
    title: "Patterns",
    subject: "math",
    category: "Algebra",
    grades: G456,
    hook: "Patterns hide rules in shapes and numbers.",
    concepts: [
      C("math-shp-pat", "Shape Patterns", G4, "Circle, square, circle, square — what is next?", "Continue a shape pattern.", "The rule repeats two shapes. Next is circle.", ["Name the repeating unit", "Continue the pattern"]),
      C("math-shp-growing", "Growing Shape Patterns", G56, "1 square, then 3, then 5... what is the rule?", "Describe a growing shape pattern.", "Each step adds 2 squares. The next has 7.", ["Count the increase", "Predict the next"]),
    ],
  },
  {
    id: "math-algebra",
    title: "Algebra Foundations",
    subject: "math",
    category: "Algebra",
    grades: G56,
    hook: "A letter can stand for a number we do not yet know.",
    concepts: [
      C("math-alg-unknown", "Unknowns", G56, "If ☐ + 7 = 12, what sits in the box?", "Find a missing number.", "The box is 5 because 5 + 7 = 12. Letters do the same job as boxes.", ["Find a missing addend", "Check by substituting"]),
      C("math-alg-letter", "Using a Letter", G6, "If n stands for a number of notebooks, what is n + 2?", "Write a simple expression with a letter.", "n + 2 means two more than n. It is not a word; it is a number once n is known.", ["Write n + a", "Read an expression"]),
    ],
  },
  {
    id: "math-expressions",
    title: "Expressions",
    subject: "math",
    category: "Algebra",
    grades: G6,
    hook: "An expression is a mathematical phrase, not yet a full sentence.",
    concepts: [
      C("math-exp-write", "Writing Expressions", G6, "How do you write '3 more than a number'?", "Write expressions from phrases.", "3 more than n is n + 3, not 3n (which is 3 times n).", ["Translate more than", "Translate times"]),
      C("math-exp-evaluate", "Evaluating Expressions", G6, "If n = 4, what is 2n + 1?", "Substitute a number into an expression.", "2 × 4 + 1 = 9. Do multiplication before addition.", ["Substitute", "Follow order"]),
    ],
  },
  {
    id: "math-equations",
    title: "Simple Equations",
    subject: "math",
    category: "Algebra",
    grades: G6,
    hook: "An equation says two amounts are equal.",
    concepts: [
      C("math-eq-balance", "Keeping Balance", G6, "If you add 3 to one side, what must you do to the other?", "Solve by keeping both sides equal.", "An equation is a balance. Do the same to both sides. x + 3 = 10 → x = 7.", ["Undo addition", "Check the solution"]),
      C("math-eq-one-step", "One-Step Equations", G6, "Solve 4x = 20.", "Solve one-step equations.", "Divide both sides by 4. x = 5. Check: 4 × 5 = 20.", ["Undo multiplication", "Undo subtraction"]),
    ],
  },
  {
    id: "math-reasoning",
    title: "Mathematical Reasoning",
    subject: "math",
    category: "Reasoning",
    grades: G456,
    hook: "A reason is a because, not just an answer.",
    concepts: [
      C("math-rea-because", "Explain Why", G45, "Is 16 even? Why?", "Give a reason with a definition.", "16 is even because it is 2 × 8, or it ends with 6.", ["Use a definition", "Give a because"]),
      C("math-rea-counter", "Counter-examples", G56, "Is every odd number prime? Find a no.", "Disprove with a counter-example.", "9 is odd but 3 × 3, so not prime. One counter-example is enough.", ["Find a counter-example", "State what it disproves"]),
      C("math-rea-steps", "Logical Steps", G6, "Can you order your thinking so a friend can follow?", "Write a short chain of reasons.", "Start from what you know, take one allowed step at a time, land on the claim.", ["Order steps", "Check each step"]),
    ],
  },
  {
    id: "math-word-problems",
    title: "Word Problems",
    subject: "math",
    category: "Reasoning",
    grades: G456,
    hook: "A story hides an operation. Your job is to find it.",
    concepts: [
      C("math-wp-choose", "Choosing an Operation", G4, "Words like 'in all' and 'left' hint at what?", "Choose add, subtract, multiply, or divide.", "'In all' often adds. 'Left' often subtracts. Equal groups often multiply or divide.", ["Spot combining", "Spot leftover"]),
      C("math-wp-two-step", "Two-Step Stories", G56, "First you buy 3 pens, then you share them. What is first?", "Solve two-step word problems.", "Do the first action, then the second. A bar model can hold both steps.", ["Plan two steps", "Compute in order"]),
      C("math-wp-units", "Units in Stories", G56, "If one bag is 2 kg, are 4 bags 8 kg or 8 bags?", "Keep track of units.", "4 × 2 kg = 8 kg. The unit stays kilograms, not 'bags' unless you count bags.", ["Name the unit", "Match the question"]),
    ],
  },
  {
    id: "math-problem-solving",
    title: "Problem Solving",
    subject: "math",
    category: "Reasoning",
    grades: G456,
    hook: "A good solver tries, checks, and tries another way.",
    concepts: [
      C("math-ps-understand", "Understand the Problem", G4, "What is asked, and what is extra?", "Restate a problem in your own words.", "Underline the question. Cross out extra decoration. Name the known numbers.", ["Restate the question", "List knowns"]),
      C("math-ps-strategies", "Strategies", G56, "When do you draw, when do you work backwards?", "Choose a strategy: draw, table, guess-check, work backwards.", "If you know the end, work backwards. If numbers grow in a pattern, make a table.", ["Draw a model", "Work backwards"]),
      C("math-ps-check", "Check the Answer", G56, "Does 400 children in a minibus make sense?", "Check reasonableness and reverse operations.", "Estimate first. Reverse the operations. Read the question again.", ["Estimate first", "Reverse check"]),
    ],
  },
];

export const MATH_WORLDS = compileWorlds(MATH);
