import {
  C,
  G7,
  G78,
  G8,
  compileWorlds,
  type WorldSpec,
} from "@/content/curriculum/build";

const MATH_MIDDLE: WorldSpec[] = [
  {
    id: "math-integers-ops",
    title: "Integer Operations",
    subject: "math",
    category: "Number",
    grades: G7,
    hook: "Integers remember direction: above zero and below zero.",
    concepts: [
      C("math-int-number-line", "Integers on a Line", G7, "Which is greater, −2 or −5?", "Compare and order integers.", "Further left is smaller. −5 is less than −2. Absolute value is distance from zero.", ["Order integers", "Read a signed number"]),
      C("math-int-add-sub", "Adding & Subtracting Integers", G7, "What does 3 + (−8) mean on a number line?", "Add and subtract integers.", "Adding a negative moves left. Subtracting a negative is adding the opposite.", ["Add integers", "Subtract integers"]),
      C("math-int-mul-div", "Multiplying & Dividing Integers", G7, "Why is negative times negative positive?", "Multiply and divide integers.", "Same signs make a positive product. Different signs make a negative product. Division follows the same sign story.", ["Multiply integers", "Divide integers"]),
    ],
  },
  {
    id: "math-rational-numbers",
    title: "Rational Numbers",
    subject: "math",
    category: "Number",
    grades: G78,
    hook: "A rational number can be written as a fraction of integers.",
    concepts: [
      C("math-rat-meaning", "What a Rational Number Is", G78, "Is −3/4 a rational number?", "Recognise rational numbers on a number line.", "A rational number is p/q with integers p and q, q not 0. Decimals that stop or repeat are rational.", ["Give a rational example", "Place a rational on a line"]),
      C("math-rat-ops", "Operations with Rationals", G8, "How do you add −1/2 and 2/3?", "Add, subtract, multiply, and divide rational numbers.", "Use a common denominator to add. Multiply numerators and denominators. Dividing is multiplying by the reciprocal.", ["Add rationals", "Multiply rationals"]),
    ],
  },
  {
    id: "math-exponents",
    title: "Exponents & Powers",
    subject: "math",
    category: "Number",
    grades: G8,
    hook: "A power is a short way to write repeated multiplication.",
    concepts: [
      C("math-exp-powers", "Squares, Cubes & Powers", G8, "What is 2^5 in ordinary multiplication?", "Read and evaluate whole-number powers.", "2^5 = 2×2×2×2×2. Square is power 2. Cube is power 3.", ["Evaluate a power", "Name square and cube"]),
      C("math-exp-laws", "Laws of Exponents", G8, "Why is 3^4 × 3^2 equal to 3^6?", "Use product, quotient, and power laws for the same base.", "When multiplying same bases, add exponents. When dividing, subtract. (a^m)^n = a^(mn).", ["Multiply same-base powers", "Divide same-base powers"]),
      C("math-exp-standard", "Large & Small with Powers of 10", G8, "How do you write 45,000 using a power of 10?", "Use powers of 10 to write large numbers.", "45,000 = 45 × 10^3. Powers of 10 move the place.", ["Write a power of 10", "Read a large number"]),
    ],
  },
  {
    id: "math-squares-cubes",
    title: "Squares & Square Roots",
    subject: "math",
    category: "Number",
    grades: G8,
    hook: "A square root undoes a square, the way a root undoes a plant from a seed story — carefully.",
    concepts: [
      C("math-sq-perfect", "Perfect Squares", G8, "Why is 49 a square but 50 not a whole-number square?", "Identify perfect squares.", "7×7=49. Square numbers make a square array.", ["List square numbers", "Spot a non-square"]),
      C("math-sq-root", "Square Roots", G8, "What number squared is 81?", "Find square roots of perfect squares.", "√81 = 9 because 9×9=81. A square root asks for the side of a square.", ["Find a square root", "Check by squaring"]),
    ],
  },
  {
    id: "math-hcf-lcm-middle",
    title: "HCF & LCM in Problems",
    subject: "math",
    category: "Number",
    grades: G7,
    hook: "Common factors and common multiples solve sharing and repeating stories.",
    concepts: [
      C("math-hcf-lcm-apply", "Choosing HCF or LCM", G7, "When do you want the largest shared size, and when the next shared time?", "Choose HCF or LCM in a story.", "HCF is the largest shared piece. LCM is the next time both patterns meet.", ["Choose HCF", "Choose LCM"]),
    ],
  },
  {
    id: "math-fractions-middle",
    title: "Fractions",
    subject: "math",
    category: "Fractions & Decimals",
    grades: G78,
    hook: "Fractions keep working as you meet mixed numbers, products, and rationals.",
    concepts: [
      C("math-frac-mul-div", "Multiplying & Dividing Fractions", G7, "Why does 1/2 × 1/3 become 1/6?", "Multiply and divide fractions.", "Multiply tops and bottoms. Dividing by a fraction is multiplying by its reciprocal.", ["Multiply fractions", "Divide fractions"]),
      C("math-frac-disguise", "Fractions in Disguise", G8, "Is 0.2 a fraction in another outfit?", "Move among fractions, decimals, and percents.", "1/5 = 0.2 = 20%. Rational numbers wear different clothes.", ["Rewrite as a decimal", "Rewrite as a percent"]),
    ],
  },
  {
    id: "math-decimals-middle",
    title: "Decimal Operations",
    subject: "math",
    category: "Fractions & Decimals",
    grades: G7,
    hook: "The decimal point must stay honest when you multiply and divide.",
    concepts: [
      C("math-dec-mul", "Multiplying Decimals", G7, "Where does the point go in 1.2 × 0.4?", "Multiply decimals.", "Multiply as whole numbers, then count decimal places from the factors.", ["Place the decimal point", "Estimate first"]),
      C("math-dec-div", "Dividing Decimals", G7, "How do you divide 1.44 by 1.2?", "Divide decimals.", "Make the divisor a whole number by moving both points the same number of places.", ["Divide by a decimal", "Check with multiplication"]),
    ],
  },
  {
    id: "math-percent-middle",
    title: "Percent & Applications",
    subject: "math",
    category: "Fractions & Decimals",
    grades: G78,
    hook: "Percent is a comparison to 100 that shows up in discounts and data.",
    concepts: [
      C("math-pct-increase", "Increase & Decrease", G8, "A price of ₹500 rises by 10%. What is new?", "Find percent increase and decrease.", "10% of 500 is 50. Increase adds; decrease subtracts.", ["Find 10% of an amount", "Find a new amount"]),
      C("math-pct-profit", "Profit, Loss & Simple Interest Intro", G8, "If cost is ₹200 and selling price is ₹240, what is profit percent?", "Use percent in profit-loss stories.", "Profit = SP − CP. Profit percent is profit compared to CP, as a percent.", ["Find profit", "Find a simple percent"]),
    ],
  },
  {
    id: "math-ratio-middle",
    title: "Ratio, Proportion & Variation",
    subject: "math",
    category: "Fractions & Decimals",
    grades: G78,
    hook: "Some quantities grow together; some grow as the other shrinks.",
    concepts: [
      C("math-ratio-direct", "Direct Proportion", G78, "If 3 books cost ₹90, what do 5 cost at the same rate?", "Solve direct proportion.", "The ratio stays the same. 3:90 = 5:x, so x = 150.", ["Set up a proportion", "Find the missing value"]),
      C("math-ratio-inverse", "Inverse Proportion", G8, "If 4 people take 6 days, what if 8 people work at the same rate?", "Solve inverse proportion.", "People × days stays constant if the work is the same. Twice the people, half the days.", ["Spot inverse stories", "Find the new time"]),
    ],
  },
  {
    id: "math-algebra-middle",
    title: "Algebraic Expressions",
    subject: "math",
    category: "Algebra",
    grades: G78,
    hook: "Letters let you write a pattern once and use it many times.",
    concepts: [
      C("math-alg-terms", "Terms, Coefficients, Like Terms", G7, "Are 3x and 3y like terms?", "Identify terms and combine like terms.", "Like terms have the same letter parts. 3x and 5x combine; 3x and 3y do not.", ["Name a coefficient", "Combine like terms"]),
      C("math-alg-simplify", "Simplifying Expressions", G78, "What is 2(x + 4) − x?", "Expand and simplify linear expressions.", "2(x + 4) = 2x + 8, then 2x + 8 − x = x + 8.", ["Use the distributive property", "Simplify"]),
      C("math-alg-identities", "Simple Identities", G8, "Why is (a + b)^2 not a^2 + b^2?", "Use (a+b)^2 and (a−b)^2 as patterns.", "(a+b)^2 = a^2 + 2ab + b^2. The middle term is the missing piece people forget.", ["Expand a square", "Spot a missing 2ab"]),
    ],
  },
  {
    id: "math-equations-middle",
    title: "Linear Equations",
    subject: "math",
    category: "Algebra",
    grades: G78,
    hook: "An equation is a balance you are allowed to change fairly.",
    concepts: [
      C("math-eq-two-step", "Two-Step Equations", G7, "Solve 2x + 5 = 17.", "Solve two-step linear equations.", "Undo addition first, then division: 2x = 12, x = 6. Check by substituting.", ["Undo two operations", "Check the solution"]),
      C("math-eq-brackets", "Equations with Brackets", G8, "Solve 3(x − 2) = 12.", "Solve equations with simple brackets.", "Expand or divide first. 3(x − 2)=12 → x − 2 = 4 → x = 6.", ["Expand brackets", "Isolate x"]),
    ],
  },
  {
    id: "math-geometry-middle",
    title: "Lines, Angles & Triangles",
    subject: "math",
    category: "Geometry",
    grades: G78,
    hook: "Lines that meet write angle stories you can prove with reasons.",
    concepts: [
      C("math-geo-parallel-angles", "Angles with Parallel Lines", G7, "If a transversal crosses parallels, which angles match?", "Use corresponding and alternate angles.", "Corresponding angles are equal when lines are parallel. Alternate interior angles are equal too.", ["Name corresponding angles", "Use them to find a size"]),
      C("math-tri-congruence", "Congruent Triangles", G7, "When are two triangles geometric twins?", "Explain congruence and matching parts.", "Congruent triangles match in sides and angles. Corresponding parts of congruent triangles are equal.", ["Match corresponding sides", "Say why they match"]),
      C("math-tri-pythagoras", "Baudhāyana–Pythagoras", G8, "In a right triangle, how are the three sides related?", "Use a^2 + b^2 = c^2 for a right triangle.", "c is the hypotenuse, the side opposite the right angle. Check by squaring.", ["Identify the hypotenuse", "Find a missing side"]),
    ],
  },
  {
    id: "math-quadrilaterals-middle",
    title: "Quadrilaterals",
    subject: "math",
    category: "Geometry",
    grades: G8,
    hook: "Four sides can hide parallel pairs, equal sides, and right angles.",
    concepts: [
      C("math-quad-properties", "Properties of Quadrilaterals", G8, "What must a parallelogram keep that a trapezium might not?", "Use properties of parallelograms, rhombuses, and kites.", "A parallelogram has opposite sides parallel and equal. A rhombus has all sides equal.", ["Use opposite sides", "Use opposite angles"]),
    ],
  },
  {
    id: "math-constructions-middle",
    title: "Constructions",
    subject: "math",
    category: "Geometry",
    grades: G78,
    hook: "A construction is a drawing that follows allowed tools and reasons.",
    concepts: [
      C("math-con-ruler-compass", "Ruler & Compass Constructions", G7, "How do you copy an angle without measuring in degrees?", "Construct basic copies, bisectors, and perpendiculars.", "Compass equal lengths and arcs mark equal distances. A bisector splits an angle in half.", ["Copy a segment", "Bisect an angle"]),
      C("math-con-tilings", "Tilings", G7, "Which shapes can cover a floor without gaps?", "Describe simple tilings.", "Rectangles tile easily. Regular hexagons tile. Regular pentagons do not tile the plane by themselves.", ["Name a tiling shape", "Spot a gap"]),
    ],
  },
  {
    id: "math-mensuration-middle",
    title: "Mensuration",
    subject: "math",
    category: "Measurement",
    grades: G78,
    hook: "Mensuration turns length into around, inside, and how much space.",
    concepts: [
      C("math-men-triangle-area", "Area of a Triangle", G8, "Why is a triangle half a parallelogram with the same base and height?", "Use A = 1/2 × base × height.", "A triangle is half of a parallelogram that shares base and height.", ["Identify base and height", "Compute triangle area"]),
      C("math-men-para-area", "Area of a Parallelogram", G8, "Does a slanted parallelogram have the same area as a rectangle of the same base and height?", "Use A = base × height.", "Height is perpendicular height, not the slanted side.", ["Use perpendicular height", "Find parallelogram area"]),
      C("math-men-circle-intro", "Circumference Ideas", G8, "Why do people say about 3 times the diameter?", "Relate circumference to diameter.", "C = πd, and π is a little more than 3. Radius is half the diameter.", ["Use C ≈ 3d as an estimate", "Name radius and diameter"]),
    ],
  },
  {
    id: "math-data-middle",
    title: "Data & Statistics",
    subject: "math",
    category: "Data",
    grades: G78,
    hook: "Averages are different kinds of typical.",
    concepts: [
      C("math-stat-mean-median-mode", "Mean, Median, Mode", G7, "When is the median fairer than the mean?", "Find mean, median, and mode.", "Mean is fair share. Median is the middle after ordering. Mode is the most frequent. A huge outlier pulls the mean.", ["Find all three", "Choose which typical to use"]),
      C("math-stat-range", "Range & Reading Graphs", G78, "What does a big range tell you?", "Use range and read line or bar graphs.", "Range = largest − smallest. It tells spread, not the typical value.", ["Compute range", "Read a trend"]),
    ],
  },
  {
    id: "math-probability-middle",
    title: "Chance & Probability",
    subject: "math",
    category: "Data",
    grades: G8,
    hook: "Probability numbers sit between impossible and certain.",
    concepts: [
      C("math-prob-fraction", "Probability as a Fraction", G8, "A fair spinner has 4 equal parts, one red. What is P(red)?", "Write simple theoretical probability.", "P = favourable / equally likely outcomes. P(red)=1/4. Impossible is 0; certain is 1.", ["Write a probability", "Compare two chances"]),
    ],
  },
  {
    id: "math-reasoning-middle",
    title: "Mathematical Reasoning",
    subject: "math",
    category: "Reasoning",
    grades: G78,
    hook: "A Grade 7–8 reason uses a definition, a property, or a counter-example.",
    concepts: [
      C("math-rea-justify", "Justifying a Step", G78, "Can you say which property allowed that step?", "Give a property or definition as a reason.", "Name commutative, distributive, or a geometry fact instead of 'because it looks right'.", ["Name a property", "Write a because"]),
    ],
  },
];

export const MATH_MIDDLE_WORLDS = compileWorlds(MATH_MIDDLE);
