import { compileWorlds } from "@/content/curriculum/build";
import { NCERT_BOOKS, ncertBookWorld } from "@/content/curriculum/ncert-books";

export const MATH_NCERT_WORLDS = compileWorlds([
  ncertBookWorld({
    id: "ncert-g4-maths-mela",
    title: "Maths Mela",
    subject: "math",
    category: "NCERT Mathematics",
    grade: 4,
    book: NCERT_BOOKS.mathsMela4,
    status: "official",
    hook: "Grade 4 maths through shapes, sharing, measuring, and stories around us.",
    chapters: [
      { slug: "shapes-around-us", title: "Shapes Around Us", about: "Notice and name 2D and 3D shapes in familiar places.", skills: ["Name a shape", "Find a shape in the room"] },
      { slug: "hide-and-seek", title: "Hide and Seek", about: "Use position, direction, and spatial language to locate things.", skills: ["Use left and right", "Describe a position"] },
      { slug: "patterns-around-us", title: "Patterns Around Us", about: "Spot, continue, and create repeating patterns.", skills: ["Continue a pattern", "Name the repeating unit"] },
      { slug: "thousands-around-us", title: "Thousands Around Us", about: "Read, write, and make sense of numbers into the thousands.", skills: ["Read a thousands number", "Build a number with places"] },
      { slug: "sharing-and-measuring", title: "Sharing and Measuring", about: "Share fairly and begin measuring with a purpose.", skills: ["Share equally", "Choose a unit"] },
      { slug: "measuring-length", title: "Measuring Length", about: "Measure length with standard units and compare distances.", skills: ["Measure in centimetres", "Compare two lengths"] },
      { slug: "the-cleanest-village", title: "The Cleanest Village", about: "Use numbers in a community story to add, compare, and decide.", skills: ["Use numbers in a story", "Explain a comparison"] },
      { slug: "weigh-it-pour-it", title: "Weigh it, Pour it", about: "Compare mass and capacity using weighing and pouring.", skills: ["Compare mass", "Compare capacity"] },
      { slug: "equal-groups", title: "Equal Groups", about: "See multiplication as equal groups and arrays.", skills: ["Make equal groups", "Write a multiplication"] },
      { slug: "elephants-tigers-leopards", title: "Elephants, Tigers, and Leopards", about: "Use large numbers, grouping, and comparison in animal stories.", skills: ["Compare large numbers", "Group and count"] },
      { slug: "fun-with-symmetry", title: "Fun with Symmetry", about: "Find lines of symmetry and make symmetrical designs.", skills: ["Find a fold line", "Complete a symmetrical drawing"] },
      { slug: "ticking-clocks", title: "Ticking Clocks and Turning Calendar", about: "Read clocks and use calendar time — days, weeks, and months.", skills: ["Read a clock", "Use a calendar"] },
      { slug: "the-transport-museum", title: "The Transport Museum", about: "Solve measurement and number problems in a travel setting.", skills: ["Choose an operation", "Keep track of units"] },
      { slug: "data-handling", title: "Data Handling", about: "Collect, tally, and read simple picture or table data.", skills: ["Make a tally", "Read a table"] },
    ],
  }),
  ncertBookWorld({
    id: "ncert-g5-maths-mela",
    title: "Maths Mela",
    subject: "math",
    category: "NCERT Mathematics",
    grade: 5,
    book: NCERT_BOOKS.mathsMela5,
    status: "official",
    hook: "Grade 5 maths through journeys, farms, maps, fractions, and data pictures.",
    chapters: [
      { slug: "we-the-travellers-1", title: "We the Travellers—I", about: "Use number, distance, and time ideas while travelling.", skills: ["Read travel numbers", "Estimate a distance"] },
      { slug: "fractions", title: "Fractions", about: "Name, compare, and use fractions of wholes and collections.", skills: ["Name a fraction", "Compare two fractions"] },
      { slug: "angles-as-turns", title: "Angles as Turns", about: "See angles as turns and sort right, acute, and obtuse turns.", skills: ["Spot a right turn", "Compare two angles"] },
      { slug: "we-the-travellers-2", title: "We the Travellers—II", about: "Continue multi-digit number work in travel contexts.", skills: ["Add large numbers", "Subtract large numbers"] },
      { slug: "far-and-near", title: "Far and Near", about: "Measure and compare longer distances with suitable units.", skills: ["Choose m or km", "Compare distances"] },
      { slug: "the-dairy-farm", title: "The Dairy Farm", about: "Use multiplication, division, and measures in a farm story.", skills: ["Solve an equal-groups story", "Use a remainder"] },
      { slug: "shapes-and-patterns", title: "Shapes and Patterns", about: "Explore 2D shapes, tiling, and growing patterns.", skills: ["Name a polygon", "Continue a growing pattern"] },
      { slug: "weight-and-capacity", title: "Weight and Capacity", about: "Measure mass and capacity and convert simple units.", skills: ["Use grams and kilograms", "Use millilitres and litres"] },
      { slug: "coconut-farm", title: "Coconut Farm", about: "Solve multi-step problems with grouping and measures.", skills: ["Plan two steps", "Check a total"] },
      { slug: "symmetrical-designs", title: "Symmetrical Designs", about: "Create and describe designs with line symmetry.", skills: ["Draw a line of symmetry", "Complete a design"] },
      { slug: "grandmothers-quilt", title: "Grandmother’s Quilt", about: "Use area, tiling, and fractions on a quilt grid.", skills: ["Count unit squares", "Name a fraction of a quilt"] },
      { slug: "racing-seconds", title: "Racing Seconds", about: "Measure elapsed time in minutes and seconds.", skills: ["Read minutes and seconds", "Find a duration"] },
      { slug: "animal-jumps", title: "Animal Jumps", about: "Compare lengths, jumps, and number patterns.", skills: ["Compare lengths", "Describe a pattern"] },
      { slug: "maps-and-locations", title: "Maps and Locations", about: "Read simple maps, directions, and relative positions.", skills: ["Read a map key", "Give a direction"] },
      { slug: "data-through-pictures", title: "Data Through Pictures", about: "Read pictographs and other picture data with a key.", skills: ["Read a pictograph key", "Compare categories"] },
    ],
  }),
  ncertBookWorld({
    id: "ncert-g6-ganita-prakash",
    title: "Ganita Prakash",
    subject: "math",
    category: "NCERT Mathematics",
    grade: 6,
    book: NCERT_BOOKS.ganitaPrakash6,
    status: "official",
    hook: "Grade 6 maths: patterns, number play, primes, fractions, integers, and constructions.",
    chapters: [
      { slug: "patterns-in-mathematics", title: "Patterns in Mathematics", about: "Find rules in number and shape patterns.", skills: ["Name a rule", "Predict a next term"] },
      { slug: "lines-and-angles", title: "Lines and Angles", about: "Work with lines, rays, and kinds of angles.", skills: ["Name a line or ray", "Classify an angle"] },
      { slug: "number-play", title: "Number Play", about: "Explore place value, factors of play, and number puzzles.", skills: ["Play with place value", "Explain a number trick"] },
      { slug: "data-handling", title: "Data Handling and Presentation", about: "Collect data and present it in tables and graphs.", skills: ["Organise a table", "Read a bar graph"] },
      { slug: "prime-time", title: "Prime Time", about: "Use primes, composites, factors, and multiples.", skills: ["Spot a prime", "Find factor pairs"] },
      { slug: "perimeter-and-area", title: "Perimeter and Area", about: "Measure around and inside rectangles and related shapes.", skills: ["Find a perimeter", "Find a rectangle area"] },
      { slug: "fractions", title: "Fractions", about: "Compare, equivalent, and operate with fractions.", skills: ["Find an equivalent fraction", "Add like fractions"] },
      { slug: "playing-with-constructions", title: "Playing with Constructions", about: "Construct figures with ruler and compass ideas.", skills: ["Draw with a compass", "Copy a length"] },
      { slug: "symmetry", title: "Symmetry", about: "Find and create line symmetry in shapes.", skills: ["Count symmetry lines", "Complete a reflection"] },
      { slug: "the-other-side-of-zero", title: "The Other Side of Zero", about: "Meet integers and negative numbers on a number line.", skills: ["Place a negative number", "Compare integers"] },
    ],
  }),
  ncertBookWorld({
    id: "ncert-g7-ganita-prakash-1",
    title: "Ganita Prakash Part 1",
    subject: "math",
    category: "NCERT Mathematics",
    grade: 7,
    book: NCERT_BOOKS.ganitaPrakash7p1,
    status: "official",
    hook: "Grade 7 maths part 1: large numbers, expressions, decimals, lines, triangles, and fractions.",
    chapters: [
      { slug: "large-numbers", title: "Large Numbers", about: "Read, compare, and operate with large numbers.", skills: ["Read a large number", "Compare large numbers"] },
      { slug: "arithmetic-expressions", title: "Arithmetic Expressions", about: "Write and evaluate arithmetic expressions with order.", skills: ["Use brackets", "Follow order of operations"] },
      { slug: "peek-beyond-the-point", title: "A Peek Beyond the Point", about: "Extend place value through decimals.", skills: ["Read tenths and hundredths", "Compare decimals"] },
      { slug: "letter-numbers", title: "Expressions Using Letter-Numbers", about: "Use letters to stand for numbers in expressions.", skills: ["Write an expression with a letter", "Substitute a value"] },
      { slug: "parallel-intersecting", title: "Parallel and Intersecting Lines", about: "Study parallel, intersecting, and related angles.", skills: ["Spot parallel lines", "Name intersecting angles"] },
      { slug: "number-play", title: "Number Play", about: "Use number play to notice patterns, parity, and what numbers can tell us.", skills: ["Describe a number pattern", "Explain a property"] },
      { slug: "three-intersecting-lines", title: "A Tale of Three Intersecting Lines", about: "Explore triangles formed by three lines.", skills: ["Spot a triangle", "Use angle facts in a triangle"] },
      { slug: "working-with-fractions", title: "Working with Fractions", about: "Operate with fractions in Grade 7 contexts.", skills: ["Add unlike fractions", "Multiply simple fractions"] },
    ],
  }),
  ncertBookWorld({
    id: "ncert-g7-ganita-prakash-2",
    title: "Ganita Prakash Part 2",
    subject: "math",
    category: "NCERT Mathematics",
    grade: 7,
    book: NCERT_BOOKS.ganitaPrakash7p2,
    status: "official",
    hook: "Grade 7 maths part 2: congruence, integers, HCF/LCM, decimals, data, constructions, and equations.",
    chapters: [
      { slug: "geometric-twins", title: "Geometric Twins", about: "Understand congruence as shapes that match exactly.", skills: ["Explain congruence", "Match corresponding parts"] },
      { slug: "operations-with-integers", title: "Operations with Integers", about: "Add, subtract, multiply, and divide integers.", skills: ["Multiply integers", "Divide integers"] },
      { slug: "finding-common-ground", title: "Finding Common Ground", about: "Use HCF and LCM to solve sharing and repeating problems.", skills: ["Find an HCF", "Find an LCM"] },
      { slug: "another-peek-beyond-the-point", title: "Another Peek Beyond the Point", about: "Multiply and divide decimals.", skills: ["Multiply decimals", "Divide decimals"] },
      { slug: "connecting-the-dots", title: "Connecting the Dots", about: "Use mean, median, and mode to summarise data.", skills: ["Find a mean", "Find a median or mode"] },
      { slug: "constructions-and-tilings", title: "Constructions and Tilings", about: "Construct figures and explore tilings.", skills: ["Make a construction", "Describe a tiling"] },
      { slug: "finding-the-unknown", title: "Finding the Unknown", about: "Solve simple equations to find an unknown.", skills: ["Solve a one-step equation", "Check a solution"] },
    ],
  }),
  ncertBookWorld({
    id: "ncert-g8-ganita-prakash",
    title: "Ganita Prakash",
    subject: "math",
    category: "NCERT Mathematics",
    grade: 8,
    book: NCERT_BOOKS.ganitaPrakash8,
    status: "official",
    note: "Fourteen chapters across Ganita Prakash Parts 1 and 2, matching official NCERT chapter PDFs (hegp1 / hegp2).",
    hook: "Grade 8 maths: powers, quadrilaterals, proportion, Pythagoras, algebra, and area.",
    chapters: [
      { slug: "a-square-and-a-cube", title: "A Square and a Cube", about: "Explore squares, cubes, and related number patterns.", skills: ["Recognise a square number", "Recognise a cube number"] },
      { slug: "power-play", title: "Power Play", about: "Use exponents and laws of powers.", skills: ["Read a power", "Multiply same-base powers"] },
      { slug: "a-story-of-numbers", title: "A Story of Numbers", about: "See how number systems grew and why place value matters.", skills: ["Explain place value", "Compare number ideas"] },
      { slug: "quadrilaterals", title: "Quadrilaterals", about: "Study properties of quadrilaterals.", skills: ["Name a quadrilateral", "Use a property"] },
      { slug: "number-play", title: "Number Play", about: "Play with number properties and puzzles at Grade 8 depth.", skills: ["Use a number property", "Explain a puzzle"] },
      { slug: "we-distribute-yet-things-multiply", title: "We Distribute, Yet Things Multiply", about: "Use the distributive property in algebra and arithmetic.", skills: ["Expand with distribution", "Factor a simple expression"] },
      { slug: "proportional-reasoning-1", title: "Proportional Reasoning-1", about: "Use ratio and proportion in Grade 8 situations.", skills: ["Write a proportion", "Find a missing term"] },
      { slug: "fractions-in-disguise", title: "Fractions in Disguise", about: "Connect fractions, decimals, percentages, and rational numbers.", skills: ["Rewrite a fraction", "Connect to a percent"] },
      { slug: "baudhayana-pythagoras", title: "The Baudhāyana-Pythagoras Theorem", about: "Use the Pythagorean relation in right triangles.", skills: ["State the relation", "Find a missing side"] },
      { slug: "proportional-reasoning-2", title: "Proportional Reasoning-2", about: "Go deeper with direct and inverse proportion.", skills: ["Spot direct proportion", "Spot inverse proportion"] },
      { slug: "exploring-geometric-themes", title: "Exploring Some Geometric Themes", about: "Explore further geometry themes such as constructions and properties.", skills: ["Use a geometric property", "Sketch a figure"] },
      { slug: "tales-by-dots-and-lines", title: "Tales by Dots and Lines", about: "Reason with points, lines, and geometric stories.", skills: ["Read a geometric diagram", "Give a reason"] },
      { slug: "algebra-play", title: "Algebra Play", about: "Manipulate algebraic expressions and identities.", skills: ["Simplify an expression", "Use an identity"] },
      { slug: "area", title: "Area", about: "Find areas of triangles, quadrilaterals, and related shapes.", skills: ["Find a triangle area", "Find a parallelogram area"] },
    ],
  }),
]);
