import { plantsNeedExperience } from "@/content/curriculum/lessons";
import {
  C,
  G4,
  G45,
  G456,
  G56,
  G6,
  compileWorlds,
  type WorldSpec,
} from "@/content/curriculum/build";

const SCIENCE: WorldSpec[] = [
  {
    id: "science-living-things",
    title: "Living Things",
    subject: "science",
    category: "Living World",
    grades: G456,
    hook: "Living things grow, need energy, and respond to the world.",
    concepts: [
      C("science-life-signs", "Signs of Life", G4, "Is a fire alive because it moves and uses air?", "List signs of living things.", "Living things grow, need food or energy, reproduce, and respond. Fire does not grow or have offspring.", ["List life signs", "Sort living and non-living"]),
      C("science-life-cells-intro", "Building Blocks Intro", G6, "What are we made of that a rock is not?", "Say that living things are made of cells.", "Cells are tiny living units. Plants and animals are made of them; rocks are not.", ["Name cells", "Contrast with non-living"]),
      C("science-life-classify", "Grouping Living Things", G45, "How is a mango tree more like grass than like a cat?", "Group plants and animals with simple features.", "Plants usually make food; animals usually eat. Grouping uses features, not size alone.", ["Group plants vs animals", "Use a feature"]),
    ],
  },
  {
    id: "science-plants",
    title: "Plants",
    subject: "science",
    category: "Living World",
    grades: G456,
    hook: "Plants make food and hold up almost every food chain.",
    concepts: [
      C("science-plants-parts", "Parts of a Plant", G4, "What job does a root do that a leaf cannot?", "Name root, stem, leaf, flower, and fruit.", "Roots take water. Stems support. Leaves make food. Flowers help make seeds.", ["Name plant parts", "Match a job"]),
      C("science-plants-needs", "What Plants Need", G45, "A plant has no mouth. So how does it 'eat'?", "Explain that green plants need light, water, air, and minerals.", "Green plants make food in leaves using light. They do not chew soil for meals.", ["List plant needs", "Explain light"], { experience: plantsNeedExperience }),
      C("science-plants-photosynthesis", "Photosynthesis", G456, "Why do leaves look green in the sun?", "Describe photosynthesis in simple terms.", "Leaves use light, water, and carbon dioxide to make sugar and oxygen. Green pigment helps catch light.", ["Name inputs", "Name outputs"]),
      C("science-plants-seeds", "Seeds & Dispersal", G45, "Why do some seeds have wings?", "Explain how seeds travel.", "Wind, water, animals, and bursting pods move seeds so new plants are not crowded.", ["Name a dispersal way", "Match a seed to a method"]),
      C("science-plants-life-cycle", "Plant Life Cycle", G4, "Does a bean plant start as a bean?", "Order seed, seedling, plant, flower, fruit.", "A seed grows into a seedling, then a plant that can flower and make new seeds.", ["Order the stages", "Plant a sequence"]),
    ],
  },
  {
    id: "science-animals",
    title: "Animals",
    subject: "science",
    category: "Living World",
    grades: G456,
    hook: "Animals move, sense, and get food in many ways.",
    concepts: [
      C("science-ani-groups", "Animal Groups", G4, "Is a whale a fish because it lives in water?", "Group animals by body covering and birth.", "Whales are mammals: they breathe air and feed milk. Fish have gills.", ["Sort mammals and birds", "Sort insects"]),
      C("science-ani-food", "Herbivores, Carnivores, Omnivores", G45, "What does a cow eat that a tiger does not?", "Classify animals by diet.", "Herbivores eat plants, carnivores eat animals, omnivores eat both.", ["Name a herbivore", "Name a carnivore"]),
      C("science-ani-life-cycles", "Animal Life Cycles", G45, "Does a butterfly look like its baby?", "Compare complete metamorphosis with live birth.", "A butterfly changes from egg to larva to pupa to adult. A kitten looks more like a cat.", ["Order a butterfly cycle", "Compare to mammals"]),
    ],
  },
  {
    id: "science-habitats",
    title: "Habitats",
    subject: "science",
    category: "Living World",
    grades: G456,
    hook: "A habitat is a living thing's address plus its food and shelter.",
    concepts: [
      C("science-hab-what", "What a Habitat Provides", G4, "Could a fish live in a desert for a week?", "Name food, water, shelter, and space.", "A habitat must supply what a species needs. A fish needs water; a cactus needs a dry place.", ["List habitat needs", "Match animal to habitat"]),
      C("science-hab-types", "Forest, Pond, Desert, Ocean", G45, "Why are pond animals different from desert animals?", "Describe features of major habitats.", "Ponds are wet and full of plants. Deserts are dry, so animals save water.", ["Compare two habitats", "Name a pond organism"]),
    ],
  },
  {
    id: "science-adaptations",
    title: "Adaptations",
    subject: "science",
    category: "Living World",
    grades: G456,
    hook: "An adaptation is a feature that helps survival in a place.",
    concepts: [
      C("science-adp-body", "Body Adaptations", G45, "Why does a camel have wide feet?", "Connect a body feature to a habitat.", "Wide feet spread weight on sand. A polar bear's fur traps heat.", ["Match feature to job", "Explain one adaptation"]),
      C("science-adp-behaviour", "Behaviour Adaptations", G56, "Why do some birds fly away in winter?", "Give examples of behavioural adaptations.", "Migration finds food and warmth. Nocturnal animals hunt at night when it is cooler.", ["Name a behaviour", "Link it to survival"]),
    ],
  },
  {
    id: "science-food-chains",
    title: "Food Chains",
    subject: "science",
    category: "Living World",
    grades: G456,
    hook: "A food chain shows who eats whom, starting from a producer.",
    concepts: [
      C("science-fc-producer", "Producers & Consumers", G45, "Who makes the first food in a grass → deer → tiger chain?", "Identify producers and consumers.", "Grass is the producer. Deer and tiger are consumers. Energy starts with the producer.", ["Spot the producer", "Spot a consumer"]),
      C("science-fc-arrows", "Reading the Arrows", G45, "Does the arrow point to the eater or the eaten?", "Read food-chain arrows as energy flow.", "The arrow points to the eater: grass → deer means energy goes to the deer.", ["Read an arrow", "Order a chain"]),
      C("science-fc-break", "If a Link Disappears", G56, "What if all the deer vanish?", "Predict what happens if a link is removed.", "Tigers lose food. Grass may grow more. Chains are connections, not just lists.", ["Predict a change", "Explain a missing link"]),
    ],
  },
  {
    id: "science-ecosystems",
    title: "Ecosystems",
    subject: "science",
    category: "Living World",
    grades: G56,
    hook: "An ecosystem is living things plus their non-living surroundings, interacting.",
    concepts: [
      C("science-eco-living-non", "Living & Non-living Parts", G56, "Is sunlight part of a forest ecosystem?", "Name biotic and abiotic parts.", "Trees are living. Sunlight, water, and soil are non-living but essential.", ["Name a biotic part", "Name an abiotic part"]),
      C("science-eco-balance", "Interdependence", G6, "Why can cutting trees change a river?", "Explain simple interdependence.", "Trees hold soil. Without them, rain can wash soil into rivers. Parts affect parts.", ["Give one link", "Predict a human effect"]),
    ],
  },
  {
    id: "science-human-body",
    title: "Human Body",
    subject: "science",
    category: "Human Body",
    grades: G456,
    hook: "Your body is a team of systems working together.",
    concepts: [
      C("science-body-senses", "Sense Organs", G4, "Which organ lets you know a bell is ringing?", "Name the five sense organs and their jobs.", "Eyes see, ears hear, nose smells, tongue tastes, skin feels. Nerves carry messages.", ["Name five senses", "Match organ to job"]),
      C("science-body-skeletal", "Skeletal System", G45, "What would happen if you had no bones?", "Explain that bones support and protect.", "The skull protects the brain. Bones also help you stand and move with muscles.", ["Name a protecting bone", "Say why we need a skeleton"]),
      C("science-body-muscular", "Muscular System", G45, "How do you lift a school bag?", "Describe muscles pulling on bones.", "Muscles contract and pull. They work in pairs around joints.", ["Describe a pull", "Name a joint"]),
      C("science-body-digestive", "Digestive System", G56, "Where does a banana start becoming you?", "Outline mouth to stomach to intestines.", "Teeth break food. The stomach and intestines digest and absorb. Waste leaves the body.", ["Order digestion", "Name absorption"]),
      C("science-body-respiratory", "Respiratory System", G56, "What gas do you need with every breath?", "Explain breathing in oxygen and out carbon dioxide.", "Lungs take in oxygen for the body and give out carbon dioxide.", ["Name oxygen", "Name the lungs"]),
      C("science-body-circulatory", "Circulatory System", G56, "Why does a cut bleed?", "Describe heart, blood, and vessels in simple terms.", "The heart pumps blood. Blood carries oxygen and nutrients through vessels.", ["Name the pump", "Say what blood carries"]),
    ],
  },
  {
    id: "science-nutrition",
    title: "Nutrition",
    subject: "science",
    category: "Human Body",
    grades: G456,
    hook: "Food is more than filling a stomach — it is fuel and building material.",
    concepts: [
      C("science-nut-groups", "Food Groups", G45, "Why is a meal of only sweets a problem?", "Name energy foods, body-building foods, and protective foods.", "Rice gives energy, dal helps build, fruits and vegetables protect with vitamins.", ["Name an energy food", "Name a body-building food"]),
      C("science-nut-balanced", "A Balanced Plate", G56, "What is missing if a plate is only rice?", "Describe a balanced diet.", "A balanced diet mixes grains, proteins, vegetables, fruits, and water. Too much of one group is not enough.", ["Build a balanced plate", "Spot a missing group"]),
    ],
  },
  {
    id: "science-health",
    title: "Health & Hygiene",
    subject: "science",
    category: "Human Body",
    grades: G456,
    hook: "Hygiene is care that keeps germs from spreading.",
    concepts: [
      C("science-hea-hygiene", "Personal Hygiene", G4, "Why wash hands before eating?", "Explain handwashing and cleanliness.", "Hands pick up germs. Soap and water lower the chance they enter your mouth.", ["When to wash hands", "Give a hygiene habit"]),
      C("science-hea-disease", "Preventing Illness", G56, "Why cover a sneeze?", "Connect germs, spread, and prevention.", "Coughs can spread droplets. Covering, clean water, and vaccines are prevention, not magic.", ["Name a spread path", "Name a prevention"]),
    ],
  },
  {
    id: "science-matter",
    title: "Matter",
    subject: "science",
    category: "Matter",
    grades: G456,
    hook: "Matter is anything that takes up space and has mass.",
    concepts: [
      C("science-mat-what", "What Is Matter?", G4, "Is air matter if you cannot see it?", "Give examples of matter, including air.", "Air takes up space in a balloon and has mass. Ideas and light are not lumps of matter in the same way.", ["Give a matter example", "Say air is matter"]),
      C("science-mat-properties", "Properties of Materials", G45, "Why is a window glass, not wood?", "Compare hardness, transparency, and flexibility.", "We choose materials for properties. Glass lets light through; wood does not.", ["Compare two materials", "Match property to use"]),
    ],
  },
  {
    id: "science-solids",
    title: "Solids",
    subject: "science",
    category: "Matter",
    grades: G45,
    hook: "A solid keeps its shape unless you force it to change.",
    concepts: [
      C("science-sol-shape", "Shape & Volume", G4, "Does a stone take the shape of a bowl?", "Describe solids as definite shape and volume.", "A stone keeps its shape in a bowl. A solid's particles are packed tightly.", ["Name a solid", "Describe its shape"]),
    ],
  },
  {
    id: "science-liquids",
    title: "Liquids",
    subject: "science",
    category: "Matter",
    grades: G45,
    hook: "A liquid takes the shape of its container but keeps its volume.",
    concepts: [
      C("science-liq-flow", "Flowing & Volume", G4, "Why does water look different in a bottle and a plate?", "Describe liquids as definite volume, no fixed shape.", "The amount of water stays; the shape changes. Liquids flow.", ["Pour a liquid", "Compare two containers"]),
    ],
  },
  {
    id: "science-gases",
    title: "Gases",
    subject: "science",
    category: "Matter",
    grades: G456,
    hook: "A gas spreads to fill the space it is in.",
    concepts: [
      C("science-gas-spread", "Filling Space", G45, "How does a smell travel across a room?", "Describe gases as no fixed shape or volume.", "Gas particles move freely. A smell spreads because the gas mixes through the air.", ["Give a gas example", "Explain spreading"]),
    ],
  },
  {
    id: "science-mixtures",
    title: "Mixtures",
    subject: "science",
    category: "Matter",
    grades: G456,
    hook: "A mixture keeps the properties of its parts.",
    concepts: [
      C("science-mix-what", "What a Mixture Is", G45, "Is salty water still water and salt?", "Define a mixture.", "You can often separate a mixture. Salt water still tastes of salt; the parts are not a new substance.", ["Give a mixture", "Contrast with a new substance"]),
      C("science-mix-types", "Solutions & Suspensions", G56, "Why does sand settle while sugar water looks clear?", "Contrast dissolving and settling.", "Sugar dissolves. Sand in water is a suspension and settles. Stirring is not dissolving.", ["Name a solution", "Name a suspension"]),
    ],
  },
  {
    id: "science-separation",
    title: "Separation",
    subject: "science",
    category: "Matter",
    grades: G456,
    hook: "We separate mixtures by using differences.",
    concepts: [
      C("science-sep-hand", "Handpicking, Sieving, Winnowing", G4, "How do you take pebbles out of rice?", "Match a simple method to a mixture.", "Handpicking uses size you can see. Sieving uses holes. Winnowing uses wind on husk.", ["Choose sieving", "Choose handpicking"]),
      C("science-sep-filter", "Filtration & Evaporation", G56, "How can you get salt back from salt water?", "Explain filtration and evaporation.", "A filter catches sand. Evaporation leaves salt when water becomes vapour.", ["Filter a solid", "Get salt by evaporation"]),
    ],
  },
  {
    id: "science-changes-state",
    title: "Changes of State",
    subject: "science",
    category: "Matter",
    grades: G456,
    hook: "Heat can turn ice to water to vapour — same water, different form.",
    concepts: [
      C("science-state-melt-freeze", "Melting & Freezing", G45, "Is melted ice still water?", "Describe melting and freezing.", "Ice melts to water when heated. Water freezes to ice when cooled. The substance is still water.", ["Describe melting", "Describe freezing"]),
      C("science-state-evap-cond", "Evaporation & Condensation", G56, "Why do a cold glass's outside get wet?", "Describe evaporation and condensation.", "Water from air condenses on the cold glass. Evaporation is liquid becoming vapour.", ["Explain a wet glass", "Name evaporation"]),
    ],
  },
  {
    id: "science-reversible",
    title: "Reversible & Irreversible Changes",
    subject: "science",
    category: "Matter",
    grades: G56,
    hook: "Some changes can go back. Some cannot.",
    concepts: [
      C("science-rev-ice", "Reversible Changes", G56, "Can you freeze melted ice again?", "Give reversible examples.", "Melting ice is reversible. Folding paper is often reversible. The material can return.", ["Give a reversible example", "Say how to reverse it"]),
      C("science-irr-cook", "Irreversible Changes", G56, "Can you un-bake a cake?", "Give irreversible examples.", "Cooking, burning, and rusting make new materials. You cannot get the egg back from a cake.", ["Give an irreversible example", "Name a new material"]),
    ],
  },
  {
    id: "science-force",
    title: "Force",
    subject: "science",
    category: "Energy & Forces",
    grades: G456,
    hook: "A force is a push or a pull.",
    concepts: [
      C("science-force-push-pull", "Pushes & Pulls", G4, "Is opening a drawer a push or a pull?", "Identify pushes and pulls.", "You pull a drawer toward you. You push a swing. Both are forces.", ["Spot a push", "Spot a pull"]),
      C("science-force-effects", "What Forces Do", G45, "Can a force change an object's shape?", "State that forces can start, stop, speed, slow, turn, or squash.", "Kicking a ball starts motion. Sitting on a cushion changes shape.", ["Change motion", "Change shape"]),
    ],
  },
  {
    id: "science-motion",
    title: "Motion",
    subject: "science",
    category: "Energy & Forces",
    grades: G456,
    hook: "Motion is a change of position with time.",
    concepts: [
      C("science-mot-types", "Types of Motion", G45, "How is a swing's motion different from a car's?", "Describe straight, circular, and to-and-fro motion.", "A car on a straight road is linear. A fan is circular. A swing is to-and-fro.", ["Name linear motion", "Name oscillatory motion"]),
      C("science-mot-speed", "Fast & Slow", G4, "How do you know a cycle is faster than a walk?", "Compare speeds in everyday language.", "Speed is distance in a time. A cycle covers more road in a minute than a walk.", ["Compare two speeds", "Use time and distance"]),
    ],
  },
  {
    id: "science-friction",
    title: "Friction",
    subject: "science",
    category: "Energy & Forces",
    grades: G456,
    hook: "Friction is a force between surfaces that can slow things down.",
    concepts: [
      C("science-fri-help", "Useful Friction", G45, "Could you walk if the floor were perfectly slippery?", "Give uses of friction.", "Friction lets shoes grip. Brakes use friction. Too little friction and you slip.", ["Name a use", "Explain walking"]),
      C("science-fri-hurt", "Friction as a Problem", G56, "Why does a machine need oil?", "Give problems caused by friction.", "Friction can wear parts and make heat. Oil reduces friction.", ["Name a problem", "Name a reduction method"]),
    ],
  },
  {
    id: "science-gravity",
    title: "Gravity",
    subject: "science",
    category: "Energy & Forces",
    grades: G456,
    hook: "Gravity pulls objects toward Earth.",
    concepts: [
      C("science-gra-fall", "Things Fall Down", G4, "Why does a thrown ball come back?", "Describe gravity as a downward pull on Earth.", "Earth pulls objects toward its centre. Up is away from the ground; down is toward it.", ["Say what gravity does", "Give an example"]),
      C("science-gra-weight", "Weight & Mass Intro", G6, "Would you 'weigh' the same on the Moon?", "Contrast mass and weight in simple words.", "Mass is how much matter. Weight is the pull of gravity. The Moon's pull is weaker, so weight changes.", ["Define mass simply", "Define weight simply"]),
    ],
  },
  {
    id: "science-machines",
    title: "Simple Machines",
    subject: "science",
    category: "Energy & Forces",
    grades: G56,
    hook: "Simple machines help us do work with less effort or a smarter direction.",
    concepts: [
      C("science-mac-lever", "Levers", G56, "Why is a see-saw a machine?", "Describe a lever and fulcrum.", "A lever turns around a fulcrum. A bottle opener is a lever.", ["Name fulcrum", "Give a lever example"]),
      C("science-mac-others", "Pulleys, Ramps, Wheels", G56, "How does a ramp help load a truck?", "Give examples of pulley, inclined plane, and wheel.", "A ramp spreads lifting over a longer path. A pulley can change direction of a pull.", ["Name a ramp", "Name a pulley"]),
    ],
  },
  {
    id: "science-energy",
    title: "Energy",
    subject: "science",
    category: "Energy & Forces",
    grades: G456,
    hook: "Energy is what makes change and motion possible.",
    concepts: [
      C("science-ene-forms", "Forms of Energy", G45, "Is a stretched rubber band holding energy?", "Name light, heat, sound, and stored energy examples.", "A stretched band stores energy. The Sun gives light and heat. A drum gives sound.", ["Name two forms", "Give a stored-energy example"]),
      C("science-ene-change", "Energy Changes", G56, "What energy does a toaster use and what does it become?", "Describe simple energy changes.", "Electrical energy in a toaster becomes heat. Energy changes form; it does not vanish in everyday talk.", ["Name a change", "Trace one device"]),
    ],
  },
  {
    id: "science-heat",
    title: "Heat",
    subject: "science",
    category: "Energy & Forces",
    grades: G456,
    hook: "Heat is energy moving from warmer to cooler.",
    concepts: [
      C("science-heat-flow", "Heat Flows", G45, "Why does ice melt in a warm room?", "Describe heat flowing to cooler objects.", "The room is warmer, so energy flows into the ice and it melts.", ["Say the direction of heat", "Give a melting example"]),
      C("science-heat-conduct", "Conductors of Heat", G56, "Why does a metal spoon in soup get hot?", "Contrast heat conductors and insulators.", "Metals conduct heat well. Wood and plastic often do not, so handles stay cooler.", ["Name a conductor", "Name an insulator"]),
    ],
  },
  {
    id: "science-light",
    title: "Light",
    subject: "science",
    category: "Energy & Forces",
    grades: G456,
    hook: "We see when light enters our eyes.",
    concepts: [
      C("science-lig-source", "Sources of Light", G4, "Is the Moon a lamp?", "Distinguish sources from reflectors.", "The Sun is a source. The Moon reflects sunlight. We see objects when light bounces to our eyes.", ["Name a source", "Explain the Moon"]),
      C("science-lig-shadow", "Shadows", G45, "When is your shadow longest?", "Explain shadows as blocked light.", "Opaque objects block light. Shadows are long when the Sun is low.", ["Make a shadow", "Link Sun height to length"]),
      C("science-lig-reflect", "Reflection", G56, "How does a mirror show your face?", "Describe reflection from shiny surfaces.", "Light bounces off a mirror to your eyes. Dull surfaces scatter light more.", ["Describe bouncing light", "Name a shiny surface"]),
    ],
  },
  {
    id: "science-sound",
    title: "Sound",
    subject: "science",
    category: "Energy & Forces",
    grades: G456,
    hook: "Sound begins with a vibration.",
    concepts: [
      C("science-snd-vibrate", "Vibrations", G45, "What is a drum doing when you hear it?", "Connect vibration to sound.", "The skin moves back and forth. That vibration travels through air to your ear.", ["Feel a vibration", "Name the ear"]),
      C("science-snd-travel", "Sound Travels", G56, "Why is space described as silent in films that are trying to be accurate?", "Say sound needs a medium.", "Sound needs air, water, or solids. Space has almost none, so there is no sound to carry.", ["Name a medium", "Explain silence in space"]),
    ],
  },
  {
    id: "science-electricity",
    title: "Electricity",
    subject: "science",
    category: "Energy & Forces",
    grades: G456,
    hook: "Electricity is a useful flow of energy in circuits.",
    concepts: [
      C("science-ele-safety", "Electrical Safety", G4, "Why not poke a pin into a socket?", "State basic electrical safety.", "Mains electricity can harm you. Dry hands, no metal in sockets, and adult help for plugs.", ["Give a safety rule", "Say why water is risky"]),
      C("science-ele-circuit", "Circuits", G56, "Why does a bulb stay dark if a wire is off?", "Describe a closed circuit.", "A closed loop lets current flow. A gap stops the bulb.", ["Close a loop", "Explain a gap"]),
      C("science-ele-conduct", "Conductors & Insulators", G56, "Why are wires metal inside and plastic outside?", "Identify conductors and insulators.", "Metal conducts. Plastic insulates so you can hold the wire.", ["Name a conductor", "Name an insulator"]),
    ],
  },
  {
    id: "science-magnets",
    title: "Magnets",
    subject: "science",
    category: "Energy & Forces",
    grades: G456,
    hook: "A magnet pulls some metals and has two poles.",
    concepts: [
      C("science-mag-attract", "Attraction", G4, "Will a magnet pick up a plastic comb?", "Test which materials a magnet attracts.", "Magnets attract iron and steel, not plastic or wood.", ["Test objects", "Name a magnetic material"]),
      C("science-mag-poles", "Poles", G56, "What happens when two north poles meet?", "Describe poles and repulsion.", "Like poles repel. Opposite poles attract. A freely hanging magnet lines up north–south.", ["Show repulsion", "Name north and south"]),
    ],
  },
  {
    id: "science-earth",
    title: "Earth",
    subject: "science",
    category: "Earth & Space",
    grades: G456,
    hook: "Earth is our home planet, with land, water, and air.",
    concepts: [
      C("science-ear-surface", "Land, Water, Air", G4, "What covers more of Earth — land or water?", "Describe Earth's surface simply.", "More of Earth is water. Land includes mountains, plains, and soil.", ["Name land and water", "Name the air around us"]),
      C("science-ear-rotate", "Day & Night", G45, "Why is it night for some people when it is day for you?", "Explain day and night by Earth's rotation.", "Earth spins. The sunlit side has day; the other side has night.", ["Name rotation", "Explain day and night"]),
    ],
  },
  {
    id: "science-rocks",
    title: "Rocks & Minerals",
    subject: "science",
    category: "Earth & Space",
    grades: G56,
    hook: "Rocks are made of minerals; they are not all the same.",
    concepts: [
      C("science-rock-types", "Looking at Rocks", G56, "Why is chalk different from granite?", "Compare hardness and uses of rocks.", "Some rocks are soft (chalk). Some are hard (granite). People use them for writing or building.", ["Compare two rocks", "Name a use"]),
    ],
  },
  {
    id: "science-soil",
    title: "Soil",
    subject: "science",
    category: "Earth & Space",
    grades: G45,
    hook: "Soil is more than dirt — it is a home and a store of water.",
    concepts: [
      C("science-soil-layers", "What Soil Holds", G45, "Why do plants grow better in some soils?", "Describe soil as bits of rock, air, water, and remains of living things.", "Sandy soil drains fast. Clay holds water. Loam is a mix many plants like.", ["Name what soil contains", "Compare sandy and clay soils"]),
    ],
  },
  {
    id: "science-water",
    title: "Water",
    subject: "science",
    category: "Earth & Space",
    grades: G456,
    hook: "Water is essential, limited, and always on the move.",
    concepts: [
      C("science-wat-uses", "Uses of Water", G4, "How many ways did you use water today?", "List uses of water.", "We drink, wash, grow food, and cook. Water is a resource, not endless from the tap.", ["List uses", "Value water"]),
      C("science-wat-cycle", "Water Cycle", G56, "Where does rain come from?", "Describe evaporation, condensation, and precipitation.", "Sun heats water. Vapour rises, cools into clouds, then falls as rain. The cycle repeats.", ["Name evaporation", "Name precipitation"]),
      C("science-wat-safe", "Safe Water", G45, "Why boil water sometimes?", "Explain that not all water is safe to drink.", "Germs can live in water. Boiling or treating can make it safer.", ["Give a safety habit", "Explain boiling"]),
    ],
  },
  {
    id: "science-air",
    title: "Air",
    subject: "science",
    category: "Earth & Space",
    grades: G456,
    hook: "Air is a mixture of gases around us.",
    concepts: [
      C("science-air-occupy", "Air Occupies Space", G4, "Can you squash an 'empty' bottle closed under water?", "Show that air takes space.", "Bubbles show air was inside. Empty of water is not empty of air.", ["Show air occupies space", "Explain bubbles"]),
      C("science-air-oxygen", "Oxygen in Air", G56, "What gas do we need from air to live?", "State that air contains oxygen and other gases.", "We use oxygen. Air also has nitrogen and carbon dioxide. Burning also uses oxygen.", ["Name oxygen", "Name another gas"]),
    ],
  },
  {
    id: "science-climate",
    title: "Climate",
    subject: "science",
    category: "Earth & Space",
    grades: G56,
    hook: "Climate is the usual weather of a place across many years.",
    concepts: [
      C("science-cli-vs-weather", "Climate vs a Single Day", G56, "Does one cold day mean a cold climate?", "Separate climate from weather.", "Weather is today. Climate is the usual pattern. One chilly day is not a new climate.", ["Define climate", "Contrast with weather"]),
      C("science-cli-monsoon", "Seasons & Monsoon", G6, "Why do many parts of India expect a wet season?", "Describe seasonal climate patterns.", "A monsoon is a seasonal wind that often brings rain. It is a climate pattern, not one storm.", ["Name a season pattern", "Link wind and rain"]),
    ],
  },
  {
    id: "science-space",
    title: "Space",
    subject: "science",
    category: "Earth & Space",
    grades: G456,
    hook: "Earth is one world among the Sun's family.",
    concepts: [
      C("science-spa-sun", "The Sun", G4, "Why do we not look straight at the Sun?", "Describe the Sun as a star that gives light and heat.", "The Sun is a star, close enough to warm Earth. Looking directly can harm eyes.", ["Name the Sun as a star", "Give a safety rule"]),
      C("science-spa-moon", "The Moon", G45, "Why does the Moon seem to change shape?", "Explain phases as how we see sunlight on the Moon.", "The Moon does not make its own light. We see different lit parts as it orbits Earth.", ["Say the Moon reflects", "Name a phase"]),
      C("science-spa-solar", "Solar System", G56, "What do planets do around the Sun?", "Name the Sun and planets in order at a simple level.", "Planets orbit the Sun. Earth is third. They do not give their own starlight like the Sun.", ["Name Earth's place", "Say planets orbit"]),
      C("science-spa-stars", "Stars", G56, "Why do stars look tiny?", "Explain that stars are distant suns.", "Stars are huge but far. They look like points. The Sun is our nearest star.", ["Contrast Sun and night stars", "Explain distance"]),
    ],
  },
  {
    id: "science-environment",
    title: "Environment",
    subject: "science",
    category: "Environment",
    grades: G456,
    hook: "The environment is everything around us that we share.",
    concepts: [
      C("science-env-what", "Our Environment", G4, "What is around you that living things need?", "Describe environment as living and non-living surroundings.", "Air, water, soil, plants, and animals together make the environment we depend on.", ["Name living parts", "Name non-living parts"]),
      C("science-env-pollution", "Pollution", G45, "How can dirty air or water harm us?", "Give examples of air, water, and land pollution.", "Smoke, plastic waste, and dirty water harm living things. Pollution is unwanted harmful stuff in the environment.", ["Name a pollution type", "Give a harm"]),
      C("science-env-conserve", "Conservation", G56, "What does 'reduce, reuse, recycle' ask you to do first?", "Explain reducing waste and saving resources.", "Reduce first — use less. Then reuse. Recycle when you can. Saving water and trees is conservation.", ["Order 3 Rs", "Give a save-water action"]),
      C("science-env-resources", "Natural Resources", G56, "Is sunlight a resource we can use up like coal?", "Contrast renewable and non-renewable resources.", "Sunlight and wind keep coming. Coal and oil take millions of years to form.", ["Name renewable", "Name non-renewable"]),
      C("science-env-sustain", "Sustainability", G6, "How can we meet today's needs without spoiling tomorrow's?", "Describe sustainability in child language.", "Use what we need without wasting so much that future children cannot have water, soil, and clean air.", ["Give a sustainable habit", "Explain future needs"]),
    ],
  },
  {
    id: "science-inquiry",
    title: "Scientific Method",
    subject: "science",
    category: "Inquiry",
    grades: G456,
    hook: "Science is a way of asking, testing, and checking — not just a pile of facts.",
    concepts: [
      C("science-inq-observe", "Observation", G4, "What can you notice about a leaf without picking it?", "Observe with senses and record.", "Observation is noticing. Draw, measure, or write. Do not invent what you did not see.", ["Make an observation", "Record it"]),
      C("science-inq-predict", "Prediction", G45, "What do you think will happen if ice sits in the sun?", "Make a prediction and say why.", "A prediction is a thoughtful guess based on what you already know. Ice will likely melt.", ["Make a prediction", "Give a because"]),
      C("science-inq-hypothesis", "Hypothesis", G56, "How is a hypothesis different from a wild guess?", "Write a testable because-statement.", "A hypothesis can be tested. 'Plants grow taller with more light because they make more food' can be tested.", ["Write a testable idea", "Plan a fair test"]),
      C("science-inq-experiment", "Experiments", G56, "Why change only one thing in a test?", "Describe a fair test.", "Change one variable. Keep others the same. That way you know what caused the difference.", ["Name the one change", "Keep controls"]),
      C("science-inq-evidence", "Evidence", G56, "Why is 'I feel it is true' not enough?", "Use evidence to support a claim.", "Evidence is what you measured or observed. Claims need evidence, not only opinions.", ["Point to evidence", "Separate opinion"]),
      C("science-inq-measure", "Measurement in Inquiry", G45, "Why measure the melt time instead of saying 'fast'?", "Use numbers in investigations.", "Measurement lets others compare. 'Melted in 8 minutes' is clearer than 'fast'.", ["Choose a unit", "Record a number"]),
      C("science-inq-conclude", "Drawing Conclusions", G6, "What if the result is not what you predicted?", "Draw a conclusion from results.", "A conclusion answers the question using the data. Unexpected results still teach you.", ["Answer from data", "Accept surprise results"]),
    ],
  },
];

export const SCIENCE_EXTRA_WORLDS = compileWorlds(SCIENCE);
