import { compileWorlds } from "@/content/curriculum/build";
import { NCERT_BOOKS, ncertBookWorld } from "@/content/curriculum/ncert-books";

export const SCIENCE_NCERT_WORLDS = compileWorlds([
  ncertBookWorld({
    id: "ncert-g6-curiosity",
    title: "Curiosity",
    subject: "science",
    category: "NCERT Science",
    grade: 6,
    book: NCERT_BOOKS.curiosity6,
    status: "official",
    hook: "Grade 6 science: living diversity, food, magnets, motion, materials, water, separation, and beyond Earth.",
    chapters: [
      { slug: "wonderful-world", title: "The Wonderful World of Science", about: "See science as asking, observing, and testing — not only memorising.", skills: ["Ask a testable question", "Make an observation"] },
      { slug: "diversity-living", title: "Diversity in the Living World", about: "Notice variety among plants and animals and how we group them.", skills: ["Give a grouping feature", "Name a diverse example"] },
      { slug: "mindful-eating", title: "Mindful Eating", about: "Connect food, nutrients, and mindful eating habits.", skills: ["Name a food group idea", "Choose a balanced habit"] },
      { slug: "exploring-magnets", title: "Exploring Magnets", about: "Investigate magnets, poles, and what magnets attract.", skills: ["Name the poles", "Test attraction"] },
      { slug: "measurement-length-motion", title: "Measurement of Length and Motion", about: "Measure length and describe motion along a path.", skills: ["Measure a length", "Describe a motion"] },
      { slug: "materials-around-us", title: "Materials Around Us", about: "Sort materials by properties such as hardness, shine, and solubility.", skills: ["Sort by a property", "Name a material"] },
      { slug: "temperature-measurement", title: "Temperature and its Measurement", about: "Measure temperature and use it to compare hot and cold.", skills: ["Read a thermometer idea", "Compare temperatures"] },
      { slug: "states-of-water", title: "A Journey through States of Water", about: "Follow water as ice, liquid, and vapour in everyday life.", skills: ["Name a change of state", "Give an everyday example"] },
      { slug: "methods-of-separation", title: "Methods of Separation in Everyday Life", about: "Use sieving, filtration, evaporation, and other separations.", skills: ["Choose a separation method", "Explain why it works"] },
      { slug: "living-creatures", title: "Living Creatures: Exploring their Characteristics", about: "Explore characteristics that living creatures share and how they differ.", skills: ["List a life characteristic", "Compare two creatures"] },
      { slug: "natures-treasures", title: "Nature’s Treasures", about: "Value air, water, soil, forests, and other natural treasures.", skills: ["Name a natural treasure", "Give a care action"] },
      { slug: "beyond-earth", title: "Beyond Earth", about: "Look beyond Earth to the Moon, Sun, and night sky.", skills: ["Name a sky object", "Give a safety rule for the Sun"] },
    ],
  }),
  ncertBookWorld({
    id: "ncert-g7-curiosity",
    title: "Curiosity",
    subject: "science",
    category: "NCERT Science",
    grade: 7,
    book: NCERT_BOOKS.curiosity7,
    status: "official",
    hook: "Grade 7 science: acids and bases, circuits, metals, changes, adolescence, heat, motion, life processes, light, and Earth–Moon–Sun.",
    chapters: [
      { slug: "ever-evolving", title: "The Ever-Evolving World of Science", about: "See science as a way of thinking that connects every later chapter.", skills: ["Ask a scientific question", "Connect two science ideas"] },
      { slug: "acidic-basic-neutral", title: "Exploring Substances: Acidic, Basic, and Neutral", about: "Test and classify acidic, basic, and neutral substances.", skills: ["Classify acid/base/neutral", "Use an indicator idea"] },
      { slug: "electricity-circuits", title: "Electricity: Circuits and their Components", about: "Build simple circuits and name their components.", skills: ["Name a circuit part", "Explain an open vs closed circuit"] },
      { slug: "metals-non-metals", title: "The World of Metals and Non-metals", about: "Compare properties of metals and non-metals.", skills: ["Give a metal property", "Give a non-metal property"] },
      { slug: "physical-chemical", title: "Changes Around Us: Physical and Chemical", about: "Tell physical changes from chemical changes.", skills: ["Spot a physical change", "Spot a chemical change"] },
      { slug: "adolescence", title: "Adolescence: A Stage of Growth and Change", about: "Understand adolescence as a stage of growth, change, and care.", skills: ["Name a change in adolescence", "Describe a healthy habit"] },
      { slug: "heat-transfer", title: "Heat Transfer in Nature", about: "Explore conduction, convection, and radiation in nature.", skills: ["Name a heat-transfer way", "Give a nature example"] },
      { slug: "time-and-motion", title: "Measurement of Time and Motion", about: "Measure time and describe motion more carefully.", skills: ["Measure a time interval", "Describe speed in words"] },
      { slug: "life-processes-animals", title: "Life Processes in Animals", about: "Explore nutrition, breathing, and other animal life processes.", skills: ["Name a life process", "Link it to an organ"] },
      { slug: "life-processes-plants", title: "Life Processes in Plants", about: "Explore how plants make food, transport materials, and grow.", skills: ["Name a plant process", "Link it to a plant part"] },
      { slug: "light-shadows", title: "Light: Shadows and Reflections", about: "Investigate shadows, reflection, and how we see.", skills: ["Explain a shadow", "Describe reflection"] },
      { slug: "earth-moon-sun", title: "Earth, Moon, and the Sun", about: "Relate Earth, Moon, and Sun to day, night, and sky patterns.", skills: ["Explain day and night", "Describe a moon or sun idea"] },
    ],
  }),
  ncertBookWorld({
    id: "ncert-g8-curiosity",
    title: "Curiosity",
    subject: "science",
    category: "NCERT Science",
    grade: 8,
    book: NCERT_BOOKS.curiosity8,
    status: "official",
    note: "Titles match official NCERT chapter PDFs (hecu101–) and consistent 2026 Curiosity Grade 8 listings. Re-check the full official TOC PDF if a later reprint renames a chapter.",
    hook: "Grade 8 science: cells and microbes, health, electricity, force, pressure, matter, solutions, light, sky time, and Earth systems.",
    chapters: [
      { slug: "investigative-world", title: "Exploring the Investigative World of Science", about: "Practise investigation: questions, experiments, and clearer explanations.", skills: ["Design a simple test", "Use evidence"] },
      { slug: "invisible-living", title: "The Invisible Living World: Beyond Our Naked Eye", about: "Meet cells and microorganisms beyond unaided sight.", skills: ["Say what a cell is", "Give a microbe example"] },
      { slug: "health-treasure", title: "Health: The Ultimate Treasure", about: "See health as more than not being sick, and learn about disease types.", skills: ["Define health broadly", "Contrast communicable and non-communicable"] },
      { slug: "electricity-magnetic-heating", title: "Electricity: Magnetic and Heating Effects", about: "Explore heating and magnetic effects of electric current.", skills: ["Describe a heating effect", "Describe a magnetic effect"] },
      { slug: "exploring-forces", title: "Exploring Forces", about: "Investigate contact and non-contact forces and their effects.", skills: ["Name a force", "Describe an effect of force"] },
      { slug: "pressure-winds-storms", title: "Pressure, Winds, Storms, and Cyclones", about: "Connect pressure to winds, storms, and safety.", skills: ["Relate pressure to wind", "Give a storm safety rule"] },
      { slug: "particulate-nature", title: "Particulate Nature of Matter", about: "Use the particle idea to explain states of matter.", skills: ["Describe particles in a solid", "Contrast particle spacing"] },
      { slug: "elements-compounds-mixtures", title: "Nature of Matter: Elements, Compounds, and Mixtures", about: "Distinguish elements, compounds, and mixtures.", skills: ["Give an element example", "Give a mixture example"] },
      { slug: "solutes-solvents", title: "The Amazing World of Solutes, Solvents, and Solutions", about: "Explore solutions, solutes, solvents, and dissolving.", skills: ["Name solute and solvent", "Describe a solution"] },
      { slug: "light-mirrors-lenses", title: "Light: Mirrors and Lenses", about: "Investigate mirrors, lenses, and how they form images.", skills: ["Describe a mirror image", "Describe a lens idea"] },
      { slug: "keeping-time-skies", title: "Keeping Time with the Skies", about: "See how the sky has helped people keep time.", skills: ["Link sky patterns to time", "Name a timekeeping idea"] },
      { slug: "nature-harmony", title: "How Nature Works in Harmony", about: "Explore ecosystems, food relations, and balance in nature.", skills: ["Read who-eats-whom", "Describe an ecosystem balance"] },
      { slug: "earth-unique-planet", title: "Our Home: Earth, a Unique Life-Sustaining Planet", about: "See why Earth can sustain life and how we protect it.", skills: ["Name a life-supporting feature", "Give a protect-Earth action"] },
    ],
  }),
]);
