import type { GrammarDomain, GrammarTopic } from "@/content/grammar/types";

export const GRAMMAR_DOMAINS: GrammarDomain[] = [
  {
    id: "grammar-domain-nouns",
    title: "Nouns",
    summary: "Naming words, kinds of nouns, and noun phrases that carry meaning.",
    topicIds: ["grammar-topic-noun-kinds", "grammar-topic-noun-phrases"],
  },
  {
    id: "grammar-domain-pronouns",
    title: "Pronouns",
    summary: "Words that stand for nouns, with clear reference and agreement.",
    topicIds: ["grammar-topic-pronoun-forms", "grammar-topic-pronoun-reference"],
  },
  {
    id: "grammar-domain-verbs",
    title: "Verbs",
    summary: "Action, state, helpers, and verb forms that carry the sentence.",
    topicIds: ["grammar-topic-verb-kinds"],
  },
  {
    id: "grammar-domain-sva",
    title: "Subject–Verb Agreement",
    summary: "Matching the verb to the real subject as sentences grow longer.",
    topicIds: ["grammar-topic-sva"],
  },
  {
    id: "grammar-domain-tenses",
    title: "Tenses",
    summary: "How English shows time, aspect, and time relations.",
    topicIds: [
      "grammar-topic-present",
      "grammar-topic-past",
      "grammar-topic-future",
    ],
  },
  {
    id: "grammar-domain-modals",
    title: "Modals",
    summary: "Ability, permission, advice, and necessity with modal verbs.",
    topicIds: ["grammar-topic-modals"],
  },
  {
    id: "grammar-domain-determiners",
    title: "Articles & Determiners",
    summary: "Tiny words that show which, how many, or how known a noun is.",
    topicIds: ["grammar-topic-articles", "grammar-topic-other-determiners"],
  },
  {
    id: "grammar-domain-adjectives",
    title: "Adjectives",
    summary: "Words that describe nouns and compare qualities.",
    topicIds: ["grammar-topic-adjectives", "grammar-topic-comparison"],
  },
  {
    id: "grammar-domain-adverbs",
    title: "Adverbs",
    summary: "How, when, where, and how much — and adjective vs adverb choices.",
    topicIds: ["grammar-topic-adverbs"],
  },
  {
    id: "grammar-domain-prepositions",
    title: "Prepositions",
    summary: "Place, time, and dependent preposition partnerships.",
    topicIds: ["grammar-topic-prepositions"],
  },
  {
    id: "grammar-domain-conjunctions",
    title: "Conjunctions",
    summary: "Joining words and ideas with the right relationship.",
    topicIds: ["grammar-topic-conjunctions"],
  },
  {
    id: "grammar-domain-interjections",
    title: "Interjections",
    summary: "Feeling-words that stand apart from the sentence core.",
    topicIds: ["grammar-topic-interjections"],
  },
  {
    id: "grammar-domain-sentence-structure",
    title: "Sentence Structure",
    summary: "Complete thoughts, sentence jobs, subjects, objects, and joins.",
    topicIds: [
      "grammar-topic-sentence-basics",
      "grammar-topic-sentence-parts",
      "grammar-topic-sentence-joins",
      "grammar-topic-questions-negatives",
    ],
  },
  {
    id: "grammar-domain-phrases-clauses",
    title: "Phrases & Clauses",
    summary: "Groups of words that belong together, including clause types.",
    topicIds: ["grammar-topic-phrases", "grammar-topic-clauses"],
  },
  {
    id: "grammar-domain-voice",
    title: "Active & Passive Voice",
    summary: "Choosing whether the doer or the receiver leads the sentence.",
    topicIds: ["grammar-topic-voice"],
  },
  {
    id: "grammar-domain-speech",
    title: "Direct & Indirect Speech",
    summary: "Quoting exact words and reporting them accurately.",
    topicIds: ["grammar-topic-speech"],
  },
  {
    id: "grammar-domain-conditionals",
    title: "Conditionals",
    summary: "If-patterns for real and imaginary situations.",
    topicIds: ["grammar-topic-conditionals"],
  },
  {
    id: "grammar-domain-non-finite",
    title: "Non-finite Verbs",
    summary: "Gerunds and related -ing forms that name activities.",
    topicIds: ["grammar-topic-non-finite"],
  },
  {
    id: "grammar-domain-punctuation",
    title: "Punctuation",
    summary: "End marks, commas, apostrophes, and stronger joins.",
    topicIds: ["grammar-topic-punctuation"],
  },
  {
    id: "grammar-domain-capitalization",
    title: "Capitalization",
    summary: "Capitals for starts, the pronoun I, names, and titles.",
    topicIds: ["grammar-topic-capitalization"],
  },
  {
    id: "grammar-domain-usage-editing",
    title: "Usage & Editing",
    summary: "Common mix-ups, agreement slip-ups, and careful revision.",
    topicIds: ["grammar-topic-usage", "grammar-topic-editing"],
  },
];

export const GRAMMAR_TOPICS: GrammarTopic[] = [
  {
    id: "grammar-topic-noun-kinds",
    title: "Kinds of Nouns",
    domainId: "grammar-domain-nouns",
    summary: "Common, proper, countable, collective, abstract, and possessive nouns.",
  },
  {
    id: "grammar-topic-noun-phrases",
    title: "Noun Phrases",
    domainId: "grammar-domain-nouns",
    summary: "Expanding a head noun with determiners and modifiers.",
  },
  {
    id: "grammar-topic-pronoun-forms",
    title: "Pronoun Forms",
    domainId: "grammar-domain-pronouns",
    summary: "Personal, possessive, reflexive, and relative pronoun forms.",
  },
  {
    id: "grammar-topic-pronoun-reference",
    title: "Pronoun Reference",
    domainId: "grammar-domain-pronouns",
    summary: "Clear antecedents and pronoun agreement in longer writing.",
  },
  {
    id: "grammar-topic-verb-kinds",
    title: "Verb Kinds & Forms",
    domainId: "grammar-domain-verbs",
    summary: "Action, main, helping, irregular, and state verbs.",
  },
  {
    id: "grammar-topic-sva",
    title: "Agreement Progression",
    domainId: "grammar-domain-sva",
    summary: "From basic singular/plural match to intervening phrases and indefinites.",
  },
  {
    id: "grammar-topic-present",
    title: "Present Forms",
    domainId: "grammar-domain-tenses",
    summary: "Simple present, present continuous, and present perfect.",
  },
  {
    id: "grammar-topic-past",
    title: "Past Forms",
    domainId: "grammar-domain-tenses",
    summary: "Simple past, past continuous, and past perfect.",
  },
  {
    id: "grammar-topic-future",
    title: "Future Forms",
    domainId: "grammar-domain-tenses",
    summary: "Will, going to, and present continuous for arrangements.",
  },
  {
    id: "grammar-topic-modals",
    title: "Modal Verbs",
    domainId: "grammar-domain-modals",
    summary: "Can, could, must, should, and may with the right force.",
  },
  {
    id: "grammar-topic-articles",
    title: "Articles",
    domainId: "grammar-domain-determiners",
    summary: "A, an, the, and the zero article.",
  },
  {
    id: "grammar-topic-other-determiners",
    title: "Other Determiners",
    domainId: "grammar-domain-determiners",
    summary: "Demonstratives and quantifiers.",
  },
  {
    id: "grammar-topic-adjectives",
    title: "Describing with Adjectives",
    domainId: "grammar-domain-adjectives",
    summary: "Placement and natural adjective order.",
  },
  {
    id: "grammar-topic-comparison",
    title: "Degrees of Comparison",
    domainId: "grammar-domain-adjectives",
    summary: "Comparatives and superlatives with -er/-est and more/most.",
  },
  {
    id: "grammar-topic-adverbs",
    title: "Adverb Use",
    domainId: "grammar-domain-adverbs",
    summary: "Manner, time, place, degree, and adjective–adverb choices.",
  },
  {
    id: "grammar-topic-prepositions",
    title: "Preposition Use",
    domainId: "grammar-domain-prepositions",
    summary: "Place, time, relation, and dependent prepositions.",
  },
  {
    id: "grammar-topic-conjunctions",
    title: "Joining with Conjunctions",
    domainId: "grammar-domain-conjunctions",
    summary: "Coordinating and subordinating joins.",
  },
  {
    id: "grammar-topic-interjections",
    title: "Interjections",
    domainId: "grammar-domain-interjections",
    summary: "Sudden feeling-words with the right tone.",
  },
  {
    id: "grammar-topic-sentence-basics",
    title: "Sentence Basics",
    domainId: "grammar-domain-sentence-structure",
    summary: "Complete sentences and sentence types.",
  },
  {
    id: "grammar-topic-sentence-parts",
    title: "Subjects, Predicates & Objects",
    domainId: "grammar-domain-sentence-structure",
    summary: "Who or what, what is said about it, and what receives the action.",
  },
  {
    id: "grammar-topic-sentence-joins",
    title: "Simple to Compound-Complex",
    domainId: "grammar-domain-sentence-structure",
    summary: "Building and transforming sentence structures.",
  },
  {
    id: "grammar-topic-questions-negatives",
    title: "Questions, Negatives & Tags",
    domainId: "grammar-domain-sentence-structure",
    summary: "Asking, negating, and checking with tags.",
  },
  {
    id: "grammar-topic-phrases",
    title: "Phrases",
    domainId: "grammar-domain-phrases-clauses",
    summary: "Prepositional and noun phrases.",
  },
  {
    id: "grammar-topic-clauses",
    title: "Clauses",
    domainId: "grammar-domain-phrases-clauses",
    summary: "Independent, dependent, relative, noun, and adverbial clauses.",
  },
  {
    id: "grammar-topic-voice",
    title: "Voice",
    domainId: "grammar-domain-voice",
    summary: "Forming and choosing active and passive.",
  },
  {
    id: "grammar-topic-speech",
    title: "Speech",
    domainId: "grammar-domain-speech",
    summary: "Direct speech and reported statements, questions, and commands.",
  },
  {
    id: "grammar-topic-conditionals",
    title: "Conditionals",
    domainId: "grammar-domain-conditionals",
    summary: "Real and imaginary if-patterns.",
  },
  {
    id: "grammar-topic-non-finite",
    title: "Non-finite Forms",
    domainId: "grammar-domain-non-finite",
    summary: "Gerunds as nouns and related activity names.",
  },
  {
    id: "grammar-topic-punctuation",
    title: "Punctuation Marks",
    domainId: "grammar-domain-punctuation",
    summary: "End marks through semicolons and quotation punctuation.",
  },
  {
    id: "grammar-topic-capitalization",
    title: "Capital Letters",
    domainId: "grammar-domain-capitalization",
    summary: "Sentence starts, I, names, titles, and places.",
  },
  {
    id: "grammar-topic-usage",
    title: "Common Usage Mix-ups",
    domainId: "grammar-domain-usage-editing",
    summary: "Homophone pairs and agreement slip-ups learners often meet.",
  },
  {
    id: "grammar-topic-editing",
    title: "Editing Passes",
    domainId: "grammar-domain-usage-editing",
    summary: "Second-pass revision for agreement, tense, and clarity.",
  },
];
