import {
  defineGrammarConcept,
  hosted,
  G4_HOST,
  G5_HOST,
  G6_HOST,
  G8_HOST,
} from "@/content/grammar/define";

export const MODIFIERS_JOINS_CONCEPTS = [
  defineGrammarConcept({
    id: "grammar-articles",
    title: "Articles",
    domainId: "grammar-domain-determiners",
    topicId: "grammar-topic-articles",
    difficulty: "foundational",
    understand: "A, an, and the — and sometimes no article — mark how known a noun is.",
    ableToDo: "Choose a/an/the or the zero article with the right reason.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "Articles", topic: "A, An, The" },
    grammarInUse: { level: "essential", unitTheme: "A/an/the and zero article" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Choose a or an by sound; the points to something known or unique.",
        ableToDo: "Choose a/an by sound and use the for a known noun.",
        skills: [
          { title: "A or an", ableToDo: "Choose a or an by the starting sound" },
          { title: "Use the", ableToDo: "Mark a known or unique noun with the" },
        ],
        catalogueConceptIds: ["english-art-a-an", "english-art-the"],
        lessonHost: hosted(G4_HOST.braille, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "The tracks something already in the shared picture.",
        ableToDo: "Use the for known and unique referents.",
        skills: [
          { title: "Known noun", ableToDo: "Decide when the fits a second mention" },
        ],
        catalogueConceptIds: ["english-art-the"],
        lessonHost: hosted(G5_HOST.frog, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "General ideas and plural kinds often take no article.",
        ableToDo: "Omit articles with many general ideas and keep the for specific.",
        skills: [
          { title: "Zero article", ableToDo: "Drop a wrong the on a general idea" },
        ],
        catalogueConceptIds: ["english-art-zero"],
        lessonHost: hosted(G6_HOST.neem, "ready"),
      },
      {
        grade: 8,
        difficulty: "advanced",
        understand: "Zero article control separates generic kinds from specific sets.",
        ableToDo: "Use no article with generic uncountables and plural kinds.",
        skills: [
          { title: "Generic vs specific", ableToDo: "Choose zero article or the for meaning" },
        ],
        catalogueConceptIds: ["english-g78-zero-article"],
        lessonHost: hosted(G8_HOST.harvest, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-determiners",
    title: "Determiners",
    domainId: "grammar-domain-determiners",
    topicId: "grammar-topic-other-determiners",
    difficulty: "foundational",
    prerequisites: ["grammar-articles"],
    understand: "Determiners sit before a noun to show which or how many.",
    ableToDo: "Use demonstratives and quantifiers that fit count and distance.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "Determiners", topic: "Demonstratives and Quantifiers" },
    grammarInUse: { level: "essential", unitTheme: "This/that and some/any/many/much" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "This/these near; that/those farther — match singular and plural.",
        ableToDo: "Point near and far with demonstratives.",
        skills: [
          { title: "Point near/far", ableToDo: "Choose this/that/these/those" },
        ],
        catalogueConceptIds: ["english-det-this-that"],
        lessonHost: hosted(G4_HOST.smart, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Many/few with countables; much/little with uncountables.",
        ableToDo: "Choose quantity words that fit the noun.",
        skills: [
          { title: "Many or much", ableToDo: "Choose many/much or some/any" },
        ],
        catalogueConceptIds: ["english-det-quant"],
        lessonHost: hosted(G5_HOST.frog, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Quantifiers stay precise as writing gets denser.",
        ableToDo: "Use some/any/many/much accurately in context.",
        skills: [
          { title: "Quantity fit", ableToDo: "Pick a quantifier that matches the noun type" },
        ],
        catalogueConceptIds: ["english-det-quant"],
        lessonHost: hosted(G6_HOST.neem, "ready"),
      },
      {
        grade: 7,
        difficulty: "secure",
        understand: "Few/little and each/every need careful pairing.",
        ableToDo: "Choose few/little, many/much, each/every for journeys and places.",
        skills: [
          { title: "Quantifier craft", ableToDo: "Choose few or little; many or much" },
        ],
        catalogueConceptIds: ["english-g78-quantifiers"],
        lessonHost: hosted(
          "ncert-g7-poorvi-north-south-east-west-core",
          "ready",
        ),
      },
      {
        grade: 8,
        difficulty: "advanced",
        understand: "Quantifier choice signals countability and agreement habits.",
        ableToDo: "Control quantifiers in denser informational writing.",
        skills: [
          { title: "Precise quantity", ableToDo: "Revise a mismatched quantifier" },
        ],
        catalogueConceptIds: ["english-g78-quantifiers"],
        lessonHost: hosted(G8_HOST.rain, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-adjectives",
    title: "Adjectives",
    domainId: "grammar-domain-adjectives",
    topicId: "grammar-topic-adjectives",
    difficulty: "foundational",
    understand: "Adjectives describe nouns and often follow a natural English order.",
    ableToDo: "Place adjectives before nouns or after be, and order stacked adjectives.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Adjective", topic: "Position and Order" },
    grammarInUse: { level: "essential", unitTheme: "Describing nouns" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Adjectives paint size, colour, and feeling onto nouns.",
        ableToDo: "Find adjectives and add two before a noun.",
        skills: [
          { title: "Find adjective", ableToDo: "Spot an adjective in a sentence" },
          { title: "Add detail", ableToDo: "Add two adjectives before a noun" },
        ],
        catalogueConceptIds: ["english-adj-describe"],
        lessonHost: hosted(G4_HOST.bells, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Opinion, size, age, shape, colour often follow a path.",
        ableToDo: "Order size then colour and rewrite a jumbled list.",
        skills: [
          { title: "Adjective order", ableToDo: "Reorder stacked adjectives naturally" },
        ],
        catalogueConceptIds: ["english-adj-order"],
        lessonHost: hosted(G5_HOST.rainbow, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Natural order keeps description smooth in longer phrases.",
        ableToDo: "Stack adjectives in a sensible English order.",
        skills: [
          { title: "Smooth stack", ableToDo: "Rewrite a jumbled adjective string" },
        ],
        catalogueConceptIds: ["english-adj-order"],
        lessonHost: hosted(G6_HOST.prayer, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-comparison",
    title: "Degrees of Comparison",
    domainId: "grammar-domain-adjectives",
    topicId: "grammar-topic-comparison",
    difficulty: "foundational",
    prerequisites: ["grammar-adjectives"],
    understand: "Comparatives and superlatives compare two things or pick the top of a group.",
    ableToDo: "Form -er/-est and more/most comparisons, including common irregulars.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Adjective", topic: "Comparison of Adjectives" },
    grammarInUse: { level: "essential", unitTheme: "Comparatives and superlatives" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Tall, taller, tallest — use than with comparatives.",
        ableToDo: "Write comparative and superlative for short adjectives.",
        skills: [
          { title: "Comparative", ableToDo: "Write an -er comparative with than" },
          { title: "Superlative", ableToDo: "Write an -est superlative" },
        ],
        catalogueConceptIds: ["english-deg-er-est"],
        lessonHost: hosted(G4_HOST.lagori, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Longer adjectives take more/most; good → better → best.",
        ableToDo: "Use -er/-est and more/most where each fits.",
        skills: [
          { title: "More/most", ableToDo: "Form more/most with a longer adjective" },
          { title: "Short forms", ableToDo: "Keep -er/-est for short adjectives" },
        ],
        catalogueConceptIds: ["english-deg-er-est", "english-deg-more-most"],
        lessonHost: hosted(G5_HOST.rainbow, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Choose the comparison pattern that fits adjective length.",
        ableToDo: "Use more/most and irregular better/best accurately.",
        skills: [
          { title: "Choose pattern", ableToDo: "Pick -er or more for the adjective" },
        ],
        catalogueConceptIds: ["english-deg-more-most"],
        lessonHost: hosted(G6_HOST.prayer, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-adverbs",
    title: "Adverbs",
    domainId: "grammar-domain-adverbs",
    topicId: "grammar-topic-adverbs",
    difficulty: "foundational",
    understand: "Adverbs tell how, when, where, or how much — and differ from adjectives.",
    ableToDo: "Identify adverb jobs and choose adjective vs adverb carefully.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Adverb", topic: "Kinds of Adverbs" },
    grammarInUse: { level: "essential", unitTheme: "Manner, time, place, degree" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Slowly = how; yesterday = when; outside = where.",
        ableToDo: "Spot manner, time, and place adverbs.",
        skills: [
          { title: "How/when/where", ableToDo: "Label an adverb's job" },
        ],
        catalogueConceptIds: ["english-adv-how"],
        lessonHost: hosted(G4_HOST.swing, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Very strengthens; too often means more than wanted; enough follows.",
        ableToDo: "Use manner adverbs and degree words carefully.",
        skills: [
          { title: "Manner", ableToDo: "Add a manner adverb to a verb" },
          { title: "Degree", ableToDo: "Contrast too, very, and enough" },
        ],
        catalogueConceptIds: ["english-adv-how", "english-adv-degree"],
        lessonHost: hosted(G5_HOST.rainbow, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Degree adverbs fine-tune force without changing the verb's meaning.",
        ableToDo: "Place degree adverbs accurately.",
        skills: [
          { title: "Place enough", ableToDo: "Place enough after an adjective" },
        ],
        catalogueConceptIds: ["english-adv-degree"],
        lessonHost: hosted(G6_HOST.prayer, "ready"),
      },
      {
        grade: 7,
        difficulty: "secure",
        understand: "After linking verbs, adjectives describe state; manner needs an adverb.",
        ableToDo: "Choose adjective after linking verbs and adverb for manner.",
        skills: [
          { title: "Adj or adv", ableToDo: "Choose bad/badly or similar pairs correctly" },
        ],
        catalogueConceptIds: ["english-g78-adv-vs-adj"],
        lessonHost: hosted(
          "ncert-g7-poorvi-animals-birds-dolittle-core",
          "ready",
        ),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-prepositions",
    title: "Prepositions",
    domainId: "grammar-domain-prepositions",
    topicId: "grammar-topic-prepositions",
    difficulty: "foundational",
    understand: "Prepositions show place, time, relation, and fixed partnerships.",
    ableToDo: "Use place/time prepositions and common dependent pairs.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Preposition", topic: "Relations of Place and Time" },
    grammarInUse: { level: "essential", unitTheme: "In, on, at and dependent prepositions" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Place and time prepositions locate nouns in space and on the clock.",
        ableToDo: "Choose common place and time prepositions.",
        skills: [
          { title: "Place prep", ableToDo: "Choose in/on/under/between" },
          { title: "Time prep", ableToDo: "Use at/on/in for time" },
        ],
        catalogueConceptIds: ["english-prep-place", "english-prep-time"],
        lessonHost: hosted(G4_HOST.mountains, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "At a clock time, on a day, in a month — plus for/with/from/about.",
        ableToDo: "Use time prepositions and other common relation words.",
        skills: [
          { title: "Time prep", ableToDo: "Use at/on/in for time" },
          { title: "Other prep", ableToDo: "Choose for/with/from/about" },
        ],
        catalogueConceptIds: ["english-prep-time", "english-prep-other"],
        lessonHost: hosted(G5_HOST.vocation, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Relation prepositions connect purpose, company, and source.",
        ableToDo: "Choose for/with/from/about in context.",
        skills: [
          { title: "Relation", ableToDo: "Pick the preposition that fits the relationship" },
        ],
        catalogueConceptIds: ["english-prep-other"],
        lessonHost: hosted(G6_HOST.bharat, "ready"),
      },
      {
        grade: 8,
        difficulty: "advanced",
        understand: "Some verbs and adjectives want a particular preposition partner.",
        ableToDo: "Use common verb/adjective + preposition chunks.",
        skills: [
          { title: "Dependent prep", ableToDo: "Choose interested in, famous for, and similar pairs" },
        ],
        catalogueConceptIds: ["english-g78-dep-prep"],
        lessonHost: hosted(G8_HOST.glass, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-conjunctions",
    title: "Conjunctions",
    domainId: "grammar-domain-conjunctions",
    topicId: "grammar-topic-conjunctions",
    difficulty: "foundational",
    understand: "Conjunctions join words and clauses with the right relationship.",
    ableToDo: "Join with and/but/or, because/so, and although/if.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Conjunction", topic: "Coordinating and Subordinating" },
    grammarInUse: { level: "essential", unitTheme: "And, but, because, although" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "And adds; but contrasts; or offers a choice; because/so link reason and result.",
        ableToDo: "Join with and/but/or and link cause with because/so.",
        skills: [
          { title: "And/but/or", ableToDo: "Join ideas with and, but, or" },
          { title: "Because/so", ableToDo: "Give a reason or a result" },
        ],
        catalogueConceptIds: [
          "english-conj-and-but-or",
          "english-conj-because-so",
        ],
        lessonHost: hosted(G4_HOST.together, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Because gives a reason; so gives a result; although flips expectation.",
        ableToDo: "Link cause, result, and contrast between clauses.",
        skills: [
          { title: "Because/so", ableToDo: "Give a reason or a result" },
          { title: "Although/if", ableToDo: "Write although or if to join clauses" },
        ],
        catalogueConceptIds: ["english-conj-because-so", "english-conj-although"],
        lessonHost: hosted(G5_HOST.parrot, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Subordinators shape how two ideas depend on each other.",
        ableToDo: "Use although and if for contrast and condition.",
        skills: [
          { title: "Subordinate join", ableToDo: "Write an although or if sentence" },
        ],
        catalogueConceptIds: ["english-conj-although"],
        lessonHost: hosted(G6_HOST.friends, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-interjections",
    title: "Interjections",
    domainId: "grammar-domain-interjections",
    topicId: "grammar-topic-interjections",
    difficulty: "foundational",
    understand: "Interjections are sudden feeling-words that stand apart from the sentence core.",
    ableToDo: "Match feeling to interjection and punctuate an exclamation.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Interjection", topic: "Exclamations" },
    grammarInUse: { level: "essential", unitTheme: "Oh, wow, oops" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Wow shows surprise; oops shows a small mistake.",
        ableToDo: "Use common interjections with the right tone.",
        skills: [
          { title: "Feeling word", ableToDo: "Match a feeling to oh/wow/oops" },
        ],
        catalogueConceptIds: ["english-int-feel"],
        lessonHost: hosted(G4_HOST.hekko, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-modals",
    title: "Modals",
    domainId: "grammar-domain-modals",
    topicId: "grammar-topic-modals",
    difficulty: "foundational",
    prerequisites: ["grammar-verb-main-helping"],
    understand: "Modals colour ability, permission, advice, and necessity.",
    ableToDo: "Use can/could and must/should/may with the right force.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "Modal Auxiliaries" },
    grammarInUse: { level: "essential", unitTheme: "Can, must, should, may" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Can shows ability; could softens a request.",
        ableToDo: "Show ability and make a polite request with can/could.",
        skills: [
          { title: "Can/could", ableToDo: "Use can for ability and could for a polite ask" },
        ],
        catalogueConceptIds: ["english-mod-can"],
        lessonHost: hosted(G4_HOST.fit, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Must is strong necessity; should is advice; may is permission or possibility.",
        ableToDo: "Choose can/could and must/should/may with the right force.",
        skills: [
          { title: "Ability", ableToDo: "Use can/could accurately" },
          { title: "Advice/rule", ableToDo: "Give advice with should or a rule with must" },
        ],
        catalogueConceptIds: ["english-mod-can", "english-mod-must-should"],
        lessonHost: hosted(G5_HOST.parrot, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Modal force shapes how strong a claim or rule sounds.",
        ableToDo: "Choose must, should, and may carefully.",
        skills: [
          { title: "Force", ableToDo: "Pick must/should/may for the situation" },
        ],
        catalogueConceptIds: ["english-mod-must-should"],
        lessonHost: hosted(G6_HOST.heart, "ready"),
      },
    ],
  }),
];
