import {
  defineGrammarConcept,
  hosted,
  G4_HOST,
  G5_HOST,
  G6_HOST,
  G7_HOST,
  G8_HOST,
} from "@/content/grammar/define";

export const NOUNS_PRONOUNS_CONCEPTS = [
  defineGrammarConcept({
    id: "grammar-nouns-common-proper",
    title: "Common & Proper Nouns",
    domainId: "grammar-domain-nouns",
    topicId: "grammar-topic-noun-kinds",
    difficulty: "foundational",
    understand: "Common nouns name kinds; proper nouns name particulars and take capitals.",
    ableToDo: "Tell common from proper nouns and capitalise proper names.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Noun", topic: "Common and Proper Nouns" },
    grammarInUse: { level: "essential", unitTheme: "Names and capitals" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "A city is common; Delhi is proper.",
        ableToDo: "Spot common vs proper and capitalise the proper one.",
        skills: [
          { title: "Spot common", ableToDo: "Name a common noun in a sentence" },
          { title: "Spot proper", ableToDo: "Capitalise a particular name" },
        ],
        catalogueConceptIds: ["english-nouns-common-proper"],
        lessonHost: hosted(G4_HOST.together, "planned"),
      },
      {
        grade: 5,
        difficulty: "foundational",
        understand: "Stories mix kinds of things with named people and places.",
        ableToDo: "Sort and capitalise common vs proper nouns in a short text.",
        skills: [
          { title: "Sort nouns", ableToDo: "Label common and proper in a paragraph" },
        ],
        catalogueConceptIds: ["english-nouns-common-proper"],
        lessonHost: hosted(G5_HOST.frog, "ready"),
      },
      {
        grade: 6,
        difficulty: "developing",
        understand: "Longer texts still mark particular names with capitals.",
        ableToDo: "Keep proper nouns consistent in informational writing.",
        skills: [
          { title: "Capitalise names", ableToDo: "Fix missing capitals on proper nouns" },
        ],
        catalogueConceptIds: ["english-nouns-common-proper"],
        lessonHost: hosted(G6_HOST.neem, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-nouns-count",
    title: "Countable & Uncountable Nouns",
    domainId: "grammar-domain-nouns",
    topicId: "grammar-topic-noun-kinds",
    difficulty: "foundational",
    prerequisites: ["grammar-nouns-common-proper"],
    understand: "Some nouns count as units; others need a measure word.",
    ableToDo: "Sort countable and uncountable nouns and use a measure phrase.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Noun", topic: "Countable and Uncountable Nouns" },
    grammarInUse: { level: "essential", unitTheme: "Count and uncount nouns" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Cups count; water usually does not.",
        ableToDo: "Sort countable vs uncountable and say a glass of water.",
        skills: [
          { title: "Sort count", ableToDo: "Sort countable and uncountable nouns" },
          { title: "Measure word", ableToDo: "Use a measure phrase for an uncountable" },
        ],
        catalogueConceptIds: ["english-nouns-count"],
        lessonHost: hosted(G4_HOST.bells, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Quantity words depend on whether the noun counts.",
        ableToDo: "Choose count/uncount forms that fit the noun.",
        skills: [
          { title: "Fit the noun", ableToDo: "Match a noun to a sensible quantity pattern" },
        ],
        catalogueConceptIds: ["english-nouns-count"],
        lessonHost: hosted(G5_HOST.frog, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-nouns-collective",
    title: "Collective Nouns",
    domainId: "grammar-domain-nouns",
    topicId: "grammar-topic-noun-kinds",
    difficulty: "foundational",
    prerequisites: ["grammar-nouns-common-proper"],
    understand: "One word can name a whole group as a unit.",
    ableToDo: "Use collective nouns for groups of people, animals, or things.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Noun", topic: "Collective Nouns" },
    grammarInUse: { level: "essential", unitTheme: "Group names" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "A team or flock names the group as one idea.",
        ableToDo: "Match groups to collective nouns.",
        skills: [
          { title: "Name the group", ableToDo: "Choose a collective noun for a group" },
        ],
        catalogueConceptIds: ["english-nouns-collective"],
        lessonHost: hosted(G4_HOST.lagori, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Collectives keep stories precise without listing every member.",
        ableToDo: "Use a collective noun naturally in a sentence.",
        skills: [
          { title: "Use in a sentence", ableToDo: "Write a sentence with a collective noun" },
        ],
        catalogueConceptIds: ["english-nouns-collective"],
        lessonHost: hosted(G5_HOST.frog, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-nouns-abstract",
    title: "Abstract Nouns",
    domainId: "grammar-domain-nouns",
    topicId: "grammar-topic-noun-kinds",
    difficulty: "developing",
    prerequisites: ["grammar-nouns-common-proper"],
    understand: "Some nouns name ideas and feelings you cannot touch.",
    ableToDo: "Identify abstract nouns and contrast them with concrete ones.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Noun", topic: "Abstract Nouns" },
    grammarInUse: { level: "basic", unitTheme: "Ideas and feelings as nouns" },
    slices: [
      {
        grade: 5,
        difficulty: "developing",
        understand: "Honesty and fear name ideas, not objects.",
        ableToDo: "Spot abstract nouns beside concrete ones.",
        skills: [
          { title: "Spot abstract", ableToDo: "Identify an abstract noun in a sentence" },
        ],
        catalogueConceptIds: ["english-nouns-abstract"],
        lessonHost: hosted(G5_HOST.frog, "ready"),
      },
      {
        grade: 6,
        difficulty: "developing",
        understand: "Abstract nouns carry theme in stories and essays.",
        ableToDo: "Choose an abstract noun that fits a theme.",
        skills: [
          { title: "Theme noun", ableToDo: "Name an abstract noun that fits a passage theme" },
        ],
        catalogueConceptIds: ["english-nouns-abstract"],
        lessonHost: hosted(G6_HOST.chair, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-nouns-possessive",
    title: "Possessive Nouns",
    domainId: "grammar-domain-nouns",
    topicId: "grammar-topic-noun-kinds",
    difficulty: "developing",
    prerequisites: ["grammar-nouns-common-proper"],
    understand: "Apostrophes mark what belongs to a noun.",
    ableToDo: "Form singular and plural possessives accurately.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Noun", topic: "Possessive Case" },
    grammarInUse: { level: "basic", unitTheme: "Possession with nouns" },
    slices: [
      {
        grade: 5,
        difficulty: "developing",
        understand: "Add 's to a singular; for plurals ending in s, add only '.",
        ableToDo: "Write singular and plural possessives.",
        skills: [
          { title: "Singular possessive", ableToDo: "Write a singular possessive with 's" },
          { title: "Plural possessive", ableToDo: "Write a plural possessive ending in s'" },
        ],
        catalogueConceptIds: ["english-nouns-possessive"],
        lessonHost: hosted(G5_HOST.bangles, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Possessives stay clear when the owner is a longer noun phrase.",
        ableToDo: "Form possessives without confusing plurals.",
        skills: [
          { title: "Owner clear", ableToDo: "Choose the correct possessive form for the owner" },
        ],
        catalogueConceptIds: ["english-nouns-possessive"],
        lessonHost: hosted(G6_HOST.neem, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-noun-phrases",
    title: "Noun Phrases",
    domainId: "grammar-domain-nouns",
    topicId: "grammar-topic-noun-phrases",
    difficulty: "developing",
    prerequisites: ["grammar-nouns-common-proper"],
    understand: "A head noun can grow into a richer phrase with determiners and modifiers.",
    ableToDo: "Find the head noun and expand a noun phrase with precise detail.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Noun", topic: "The Noun Phrase" },
    grammarInUse: { level: "intermediate", unitTheme: "Building noun phrases" },
    slices: [
      {
        grade: 6,
        difficulty: "developing",
        understand: "Determiners and adjectives build around the head noun.",
        ableToDo: "Find the head and expand a short noun phrase.",
        skills: [
          { title: "Find the head", ableToDo: "Identify the head noun in a phrase" },
          { title: "Expand", ableToDo: "Expand a noun into a noun phrase" },
        ],
        catalogueConceptIds: ["english-phr-noun"],
        lessonHost: hosted(G6_HOST.bird, "ready"),
      },
      {
        grade: 7,
        difficulty: "secure",
        understand: "Packed noun phrases sharpen sensory and informational writing.",
        ableToDo: "Expand a noun phrase to specify which thing you mean.",
        skills: [
          { title: "Sharpen detail", ableToDo: "Expand a noun phrase for clearer description" },
        ],
        catalogueConceptIds: ["english-g78-noun-phrases"],
        lessonHost: hosted(G7_HOST.three, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-pro-personal",
    title: "Personal Pronouns",
    domainId: "grammar-domain-pronouns",
    topicId: "grammar-topic-pronoun-forms",
    difficulty: "foundational",
    understand: "Personal pronouns stand in for people and things without repeating names.",
    ableToDo: "Replace nouns with I, you, he, she, it, we, they.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Pronoun", topic: "Personal Pronouns" },
    grammarInUse: { level: "essential", unitTheme: "Subject and object pronouns" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Riya becomes she; the children become they.",
        ableToDo: "Choose a personal pronoun that matches person and number.",
        skills: [
          { title: "Replace a noun", ableToDo: "Swap a repeated name for a pronoun" },
          { title: "He or she", ableToDo: "Choose he or she for a named person" },
        ],
        catalogueConceptIds: ["english-pro-personal"],
        lessonHost: hosted(G4_HOST.smart, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-pro-possessive",
    title: "Possessive Pronouns",
    domainId: "grammar-domain-pronouns",
    topicId: "grammar-topic-pronoun-forms",
    difficulty: "foundational",
    prerequisites: ["grammar-pro-personal"],
    understand: "Mine, yours, and theirs stand alone to show ownership.",
    ableToDo: "Use possessive pronouns and contrast them with my/your.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Pronoun", topic: "Possessive Pronouns" },
    grammarInUse: { level: "essential", unitTheme: "Mine, yours, theirs" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "My is a determiner; mine stands alone.",
        ableToDo: "Use mine/yours and contrast my with mine.",
        skills: [
          { title: "Use mine", ableToDo: "Complete a sentence with mine or yours" },
        ],
        catalogueConceptIds: ["english-pro-possessive"],
        lessonHost: hosted(G4_HOST.one, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Possessive pronouns keep ownership clear without repeating the noun.",
        ableToDo: "Choose the right possessive pronoun in context.",
        skills: [
          { title: "Choose form", ableToDo: "Pick mine/yours/theirs for the owner" },
        ],
        catalogueConceptIds: ["english-pro-possessive"],
        lessonHost: hosted(G5_HOST.vocation, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-pro-reflexive",
    title: "Reflexive Pronouns",
    domainId: "grammar-domain-pronouns",
    topicId: "grammar-topic-pronoun-forms",
    difficulty: "developing",
    prerequisites: ["grammar-pro-personal"],
    understand: "Reflexives mark when the same person does and receives the action.",
    ableToDo: "Use myself, yourself, himself, herself, itself, ourselves, themselves.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Pronoun", topic: "Reflexive Pronouns" },
    grammarInUse: { level: "basic", unitTheme: "Myself and themselves" },
    slices: [
      {
        grade: 5,
        difficulty: "developing",
        understand: "She taught herself — same person both sides.",
        ableToDo: "Choose a reflexive and avoid a wrong extra myself.",
        skills: [
          { title: "Choose reflexive", ableToDo: "Pick the matching reflexive pronoun" },
        ],
        catalogueConceptIds: ["english-pro-reflexive"],
        lessonHost: hosted(G5_HOST.vocation, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Reflexives emphasise or show self-directed action.",
        ableToDo: "Use reflexives accurately in longer sentences.",
        skills: [
          { title: "Self-action", ableToDo: "Write a sentence where subject and object match" },
        ],
        catalogueConceptIds: ["english-pro-reflexive"],
        lessonHost: hosted(G6_HOST.kites, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-pro-relative",
    title: "Relative Pronouns",
    domainId: "grammar-domain-pronouns",
    topicId: "grammar-topic-pronoun-forms",
    difficulty: "developing",
    prerequisites: ["grammar-pro-personal"],
    understand: "Who, which, that, and whose join extra information to a noun.",
    ableToDo: "Join clauses with relative pronouns for people and things.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Pronoun", topic: "Relative Pronouns" },
    grammarInUse: { level: "intermediate", unitTheme: "Who, which, that" },
    slices: [
      {
        grade: 6,
        difficulty: "developing",
        understand: "Who is for people; which/that often add facts about things.",
        ableToDo: "Join with who or which to hang detail on a noun.",
        skills: [
          { title: "Join with who", ableToDo: "Add a who-clause about a person" },
          { title: "Join with which", ableToDo: "Add a which-clause about a thing" },
        ],
        catalogueConceptIds: ["english-pro-relative"],
        lessonHost: hosted(G6_HOST.kites, "ready"),
      },
      {
        grade: 7,
        difficulty: "secure",
        understand: "Relative pronouns weave travel and story detail into one sentence.",
        ableToDo: "Use a relative pronoun to add a precise detail.",
        skills: [
          { title: "Add detail", ableToDo: "Attach a relative clause to a noun" },
        ],
        catalogueConceptIds: ["english-g78-relative"],
        lessonHost: hosted(G7_HOST.travel, "ready"),
      },
      {
        grade: 8,
        difficulty: "advanced",
        understand: "Relative choice (who/whom/which/whose/that) tracks role and referent.",
        ableToDo: "Choose the relative pronoun that fits people vs things.",
        skills: [
          { title: "Choose relative", ableToDo: "Pick who/which/whose/that for the referent" },
        ],
        catalogueConceptIds: ["english-g78-relative"],
        lessonHost: hosted(G8_HOST.wisdom, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-pronoun-agree",
    title: "Pronoun Agreement & Reference",
    domainId: "grammar-domain-pronouns",
    topicId: "grammar-topic-pronoun-reference",
    difficulty: "secure",
    prerequisites: ["grammar-pro-personal", "grammar-pro-relative"],
    understand: "A pronoun must point to a clear antecedent and agree in careful writing.",
    ableToDo: "Keep pronoun reference clear and rewrite for standard agreement.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Pronoun", topic: "Agreement and Reference" },
    grammarInUse: { level: "intermediate", unitTheme: "Clear pronoun reference" },
    slices: [
      {
        grade: 7,
        difficulty: "secure",
        understand: "Everyone and similar words need careful matching in school English.",
        ableToDo: "Find the antecedent and rewrite for clear agreement.",
        skills: [
          { title: "Find antecedent", ableToDo: "Name what a pronoun refers to" },
          { title: "Rewrite agree", ableToDo: "Rewrite a mismatch for standard agreement" },
        ],
        catalogueConceptIds: ["english-g78-pronoun-agree"],
        lessonHost: hosted(G7_HOST.tunnel, "ready"),
      },
    ],
  }),
];
