import {
  defineGrammarConcept,
  hosted,
  standalone,
  G4_HOST,
  G5_HOST,
  G6_HOST,
  G8_HOST,
  SVA_GOLD,
} from "@/content/grammar/define";

export const SENTENCES_CLAUSES_CONCEPTS = [
  defineGrammarConcept({
    id: "grammar-sentence-basics",
    title: "Sentence Basics",
    domainId: "grammar-domain-sentence-structure",
    topicId: "grammar-topic-sentence-basics",
    difficulty: "foundational",
    understand: "A sentence is a complete thought with a job: tell, ask, command, or exclaim.",
    ableToDo: "Write complete sentences and identify statement, question, command, exclamation.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Sentence", topic: "Kinds of Sentences" },
    grammarInUse: { level: "essential", unitTheme: "Complete sentences and sentence types" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Fragments leave you hanging; end marks signal the job.",
        ableToDo: "Finish a fragment and write each sentence type.",
        skills: [
          { title: "Complete thought", ableToDo: "Spot a fragment and finish the sentence" },
          { title: "Four jobs", ableToDo: "Write statement, question, command, exclamation" },
        ],
        catalogueConceptIds: ["english-sent-complete", "english-sent-types"],
        lessonHost: hosted(G4_HOST.one, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Punctuation and word order mark the sentence's job.",
        ableToDo: "Identify and write the four sentence jobs.",
        skills: [
          { title: "Match the job", ableToDo: "Match a sentence to its type and end mark" },
        ],
        catalogueConceptIds: ["english-sent-types"],
        lessonHost: hosted(G5_HOST.gilli, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-subject-finding",
    title: "Finding the Subject",
    domainId: "grammar-domain-sentence-structure",
    topicId: "grammar-topic-sentence-parts",
    difficulty: "foundational",
    prerequisites: ["grammar-sentence-basics"],
    understand: "The subject is who or what the sentence is about; the predicate tells about it.",
    ableToDo: "Name subjects and split complete subject from complete predicate.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Sentence", topic: "Subject and Predicate" },
    grammarInUse: { level: "essential", unitTheme: "Who or what the sentence is about" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Ask who or what the sentence is about.",
        ableToDo: "Underline the subject and the predicate.",
        skills: [
          { title: "Find subject", ableToDo: "Name the subject of a simple sentence" },
        ],
        catalogueConceptIds: ["english-sub-who"],
        lessonHost: standalone(SVA_GOLD, "ready"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "All describing words before the verb belong to the complete subject.",
        ableToDo: "Bracket complete subject and complete predicate.",
        skills: [
          { title: "Complete split", ableToDo: "Split complete subject from predicate" },
        ],
        catalogueConceptIds: ["english-sub-complete"],
        lessonHost: standalone(SVA_GOLD, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Longer subjects still separate cleanly from what is said about them.",
        ableToDo: "Split complete subject and predicate in denser sentences.",
        skills: [
          { title: "Longer subject", ableToDo: "Bracket a multi-word complete subject" },
        ],
        catalogueConceptIds: ["english-sub-complete"],
        lessonHost: standalone(SVA_GOLD, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-objects",
    title: "Direct & Indirect Objects",
    domainId: "grammar-domain-sentence-structure",
    topicId: "grammar-topic-sentence-parts",
    difficulty: "developing",
    prerequisites: ["grammar-subject-finding", "grammar-verb-action"],
    understand: "Objects receive the action — sometimes a thing, sometimes a person who receives it.",
    ableToDo: "Find direct objects and indirect objects (receivers).",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Sentence", topic: "Objects" },
    grammarInUse: { level: "basic", unitTheme: "Direct and indirect objects" },
    slices: [
      {
        grade: 5,
        difficulty: "developing",
        understand: "Ask subject + verb + what/whom for the direct object.",
        ableToDo: "Name the direct object.",
        skills: [
          { title: "Direct object", ableToDo: "Ask what/whom to find the object" },
        ],
        catalogueConceptIds: ["english-obj-direct"],
        lessonHost: hosted(G5_HOST.vocation, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Riya can be the receiver while gift is the thing given.",
        ableToDo: "Name indirect and direct objects in the same sentence.",
        skills: [
          { title: "Receiver", ableToDo: "Name the indirect object" },
          { title: "Thing given", ableToDo: "Name the direct object beside it" },
        ],
        catalogueConceptIds: ["english-obj-direct", "english-obj-indirect"],
        lessonHost: hosted(G6_HOST.chair, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-phrases",
    title: "Phrases",
    domainId: "grammar-domain-phrases-clauses",
    topicId: "grammar-topic-phrases",
    difficulty: "developing",
    prerequisites: ["grammar-prepositions", "grammar-sentence-basics"],
    understand: "A phrase belongs together but is not a full sentence on its own.",
    ableToDo: "Identify prepositional phrases and say what extra information they add.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "Phrases", topic: "Prepositional Phrases" },
    grammarInUse: { level: "basic", unitTheme: "Prepositional phrases" },
    slices: [
      {
        grade: 5,
        difficulty: "developing",
        understand: "On the roof adds place without a finite verb of its own.",
        ableToDo: "Box a prepositional phrase and say what it tells.",
        skills: [
          { title: "Prep phrase", ableToDo: "Identify a prepositional phrase" },
        ],
        catalogueConceptIds: ["english-phr-prep"],
        lessonHost: hosted(G5_HOST.vocation, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Phrases tuck detail beside the sentence core.",
        ableToDo: "Identify prepositional phrases in denser lines.",
        skills: [
          { title: "Box the phrase", ableToDo: "Find and explain a prepositional phrase" },
        ],
        catalogueConceptIds: ["english-phr-prep"],
        lessonHost: hosted(G6_HOST.bird, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-clauses",
    title: "Independent & Dependent Clauses",
    domainId: "grammar-domain-phrases-clauses",
    topicId: "grammar-topic-clauses",
    difficulty: "developing",
    prerequisites: ["grammar-sentence-basics", "grammar-conjunctions"],
    understand: "A clause has a subject and a verb; some stand alone, some need a partner.",
    ableToDo: "Recognise independent and dependent clauses and attach them.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "Clauses", topic: "Principal and Subordinate Clauses" },
    grammarInUse: { level: "intermediate", unitTheme: "Independent vs dependent clauses" },
    slices: [
      {
        grade: 5,
        difficulty: "developing",
        understand: "An independent clause can stand as a sentence.",
        ableToDo: "Spot an independent clause and punctuate it.",
        skills: [
          { title: "Independent", ableToDo: "Recognise a clause that can stand alone" },
        ],
        catalogueConceptIds: ["english-cl-independent"],
        lessonHost: hosted(G5_HOST.panchayat, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Because/when/if make a clause dependent until it finds a main partner.",
        ableToDo: "Spot dependent clauses and attach them to a main clause.",
        skills: [
          { title: "Independent", ableToDo: "Spot a stand-alone clause" },
          { title: "Dependent", ableToDo: "Attach a because/when/if clause to a main clause" },
        ],
        catalogueConceptIds: ["english-cl-independent", "english-cl-dependent"],
        lessonHost: hosted(G6_HOST.winner, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-clause-types",
    title: "Relative, Noun & Adverbial Clauses",
    domainId: "grammar-domain-phrases-clauses",
    topicId: "grammar-topic-clauses",
    difficulty: "secure",
    prerequisites: ["grammar-clauses", "grammar-pro-relative"],
    understand: "Clauses can describe nouns, act as nouns, or tell when/why/if.",
    ableToDo: "Use defining/non-defining relatives, noun clauses, and adverbial clauses.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "Clauses", topic: "Adjective, Noun, and Adverb Clauses" },
    grammarInUse: { level: "intermediate", unitTheme: "Clause types in longer sentences" },
    slices: [
      {
        grade: 7,
        difficulty: "secure",
        understand: "Adverbial clauses deepen time, reason, and condition.",
        ableToDo: "Write because/when/if clauses that need a main partner.",
        skills: [
          { title: "Adverbial clause", ableToDo: "Add an adverbial clause of time or reason" },
        ],
        catalogueConceptIds: ["english-g78-adv-clause"],
        lessonHost: hosted("ncert-g7-poorvi-paper-boats-core", "ready"),
      },
      {
        grade: 8,
        difficulty: "advanced",
        understand: "Defining relatives identify; extras take commas; noun clauses can be objects.",
        ableToDo: "Write defining and non-defining relatives and use that/what noun clauses.",
        skills: [
          { title: "Defining relative", ableToDo: "Write a defining relative clause" },
          { title: "Extra relative", ableToDo: "Write a non-defining clause with commas" },
          { title: "Noun clause", ableToDo: "Use a that/what clause as a noun" },
        ],
        catalogueConceptIds: [
          "english-g78-rel-define",
          "english-g78-noun-clause",
        ],
        lessonHost: hosted(G8_HOST.mother, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-simple-sentences",
    title: "Simple Sentences",
    domainId: "grammar-domain-sentence-structure",
    topicId: "grammar-topic-sentence-joins",
    difficulty: "foundational",
    prerequisites: ["grammar-sentence-basics"],
    understand: "A simple sentence is one independent clause — still one main thought.",
    ableToDo: "Write a simple sentence and add detail without extra clauses.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Sentence", topic: "Simple Sentences" },
    grammarInUse: { level: "essential", unitTheme: "One complete thought" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "One clause can still hold two nouns sharing one verb idea.",
        ableToDo: "Write a short simple sentence with optional adjectives.",
        skills: [
          { title: "One clause", ableToDo: "Write a simple sentence with one main clause" },
        ],
        catalogueConceptIds: ["english-simple-one"],
        lessonHost: hosted(G4_HOST.one, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-compound-sentences",
    title: "Compound Sentences",
    domainId: "grammar-domain-sentence-structure",
    topicId: "grammar-topic-sentence-joins",
    difficulty: "foundational",
    prerequisites: ["grammar-simple-sentences", "grammar-conjunctions"],
    understand: "Compound sentences join two equal thoughts with a coordinating conjunction.",
    ableToDo: "Build compounds with and/but/or/so and fix run-ons.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Sentence", topic: "Compound Sentences" },
    grammarInUse: { level: "basic", unitTheme: "Joining equal clauses" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Two complete sentences need a joiner, not a glue of silence.",
        ableToDo: "Join with and/but and avoid a bare smash of two sentences.",
        skills: [
          { title: "Join equals", ableToDo: "Build a compound with and or but" },
        ],
        catalogueConceptIds: ["english-comp-fanboys"],
        lessonHost: hosted(G4_HOST.together, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "A comma alone is not strong enough glue between two sentences.",
        ableToDo: "Build compounds and fix run-ons with a conjunction or full stop.",
        skills: [
          { title: "FANBOYS join", ableToDo: "Join two clauses with a coordinating conjunction" },
          { title: "Fix run-on", ableToDo: "Repair a run-on with a joiner or stop" },
        ],
        catalogueConceptIds: ["english-comp-fanboys", "english-comp-comma"],
        lessonHost: hosted(G5_HOST.panchayat, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Run-ons hide in confident drafting — second passes catch them.",
        ableToDo: "Fix run-ons cleanly in longer writing.",
        skills: [
          { title: "No comma splice", ableToDo: "Fix a comma splice or run-on" },
        ],
        catalogueConceptIds: ["english-comp-comma"],
        lessonHost: hosted(G6_HOST.bharat, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-complex-sentences",
    title: "Complex & Compound-Complex Sentences",
    domainId: "grammar-domain-sentence-structure",
    topicId: "grammar-topic-sentence-joins",
    difficulty: "developing",
    prerequisites: ["grammar-clauses", "grammar-compound-sentences"],
    understand: "Complex sentences hang a dependent clause on a main one; compound-complex does both.",
    ableToDo: "Write complex sentences and clear compound-complex joins; transform forms.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Sentence", topic: "Complex Sentences" },
    grammarInUse: { level: "intermediate", unitTheme: "Subordinate clauses and longer joins" },
    slices: [
      {
        grade: 5,
        difficulty: "developing",
        understand: "When/because/if/although open dependent clauses that need a main partner.",
        ableToDo: "Write a complex sentence with a subordinating conjunction.",
        skills: [
          { title: "Start with when", ableToDo: "Open with when/if and use a comma" },
        ],
        catalogueConceptIds: ["english-cpx-when"],
        lessonHost: hosted(G5_HOST.parrot, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Clause order changes comma habits but not the dependency.",
        ableToDo: "Put the dependent clause first or second with correct punctuation.",
        skills: [
          { title: "Clause second", ableToDo: "Attach a dependent clause after the main clause" },
        ],
        catalogueConceptIds: ["english-cpx-when"],
        lessonHost: hosted(G6_HOST.friends, "ready"),
      },
      {
        grade: 8,
        difficulty: "advanced",
        understand: "Long sentences stay clear when joins stay intentional.",
        ableToDo: "Write compound-complex sentences and transform form without losing meaning.",
        skills: [
          { title: "Compound-complex", ableToDo: "Write one clear compound-complex sentence" },
          { title: "Transform", ableToDo: "Rewrite as complex or negative keeping the facts" },
        ],
        catalogueConceptIds: [
          "english-g78-compound-complex",
          "english-g78-transformation",
        ],
        lessonHost: hosted(G8_HOST.brush, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-questions-negatives",
    title: "Questions, Negatives & Tags",
    domainId: "grammar-domain-sentence-structure",
    topicId: "grammar-topic-questions-negatives",
    difficulty: "foundational",
    prerequisites: ["grammar-sentence-basics", "grammar-verb-main-helping"],
    understand: "Questions ask, negatives deny, and tags check — helpers do much of the work.",
    ableToDo: "Form yes/no and wh- questions, single negatives, and matching tags.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "Interrogative and Negative Forms" },
    grammarInUse: { level: "essential", unitTheme: "Questions, negatives, and tags" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Helpers move or appear to ask; not / n't denies.",
        ableToDo: "Form yes/no and wh- questions and simple negatives.",
        skills: [
          { title: "Yes/no", ableToDo: "Invert be or add do/does/did" },
          { title: "Wh- ask", ableToDo: "Ask who/what/where/when/why/how" },
          { title: "Add not", ableToDo: "Make a sentence negative with not/n't" },
        ],
        catalogueConceptIds: [
          "english-q-yesno",
          "english-q-wh",
          "english-neg-not",
        ],
        lessonHost: hosted(G4_HOST.smart, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Wh- questions seek specific information; one negative is enough.",
        ableToDo: "Ask clear wh- questions and avoid double negatives.",
        skills: [
          { title: "Wh- detail", ableToDo: "Ask why/how with clear word order" },
          { title: "One negative", ableToDo: "Rewrite a double negative in standard English" },
        ],
        catalogueConceptIds: ["english-q-wh", "english-neg-double"],
        lessonHost: hosted(G5_HOST.gilli, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Double negatives confuse meaning in careful writing.",
        ableToDo: "Keep a single negative with anything/anybody.",
        skills: [
          { title: "Single negative", ableToDo: "Choose anything/anybody after a negative" },
        ],
        catalogueConceptIds: ["english-neg-double"],
        lessonHost: hosted(G6_HOST.winner, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-question-tags",
    title: "Question Tags",
    domainId: "grammar-domain-sentence-structure",
    topicId: "grammar-topic-questions-negatives",
    difficulty: "secure",
    prerequisites: ["grammar-questions-negatives", "grammar-sva"],
    understand: "A tag turns a statement into a checking question with a matching helper.",
    ableToDo: "Add a tag with the opposite positive/negative while the helper matches.",
    lessonStrategy: "standalone",
    wrenMartin: { section: "The Verb", topic: "Question Tags" },
    grammarInUse: { level: "intermediate", unitTheme: "Question tags" },
    slices: [
      {
        grade: 6,
        difficulty: "secure",
        understand: "You are ready, aren't you? — helper matches; +/− flips.",
        ableToDo: "Add negative and positive tags that match the statement.",
        skills: [
          { title: "Tag match", ableToDo: "Add a tag with flipped positive/negative" },
        ],
        catalogueConceptIds: ["english-tag-match"],
        lessonHost: standalone(SVA_GOLD, "ready"),
      },
    ],
  }),
];
