import {
  defineGrammarConcept,
  hosted,
  standalone,
  G4_HOST,
  G5_HOST,
  G6_HOST,
  G7_HOST,
  G8_HOST,
  SVA_GOLD,
} from "@/content/grammar/define";

export const VERBS_SVA_TENSES_CONCEPTS = [
  defineGrammarConcept({
    id: "grammar-verb-action",
    title: "Action Verbs",
    domainId: "grammar-domain-verbs",
    topicId: "grammar-topic-verb-kinds",
    difficulty: "foundational",
    understand: "Action verbs name what someone or something does.",
    ableToDo: "Find action verbs and use them to move a sentence.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "Transitive and Intransitive Verbs" },
    grammarInUse: { level: "essential", unitTheme: "Doing words" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Flew, cooked, whispered are doing words.",
        ableToDo: "Spot an action verb in a short sentence.",
        skills: [
          { title: "Spot action", ableToDo: "Underline the action verb" },
        ],
        catalogueConceptIds: ["english-verb-action"],
        lessonHost: hosted(G4_HOST.stag, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-verb-main-helping",
    title: "Main & Helping Verbs",
    domainId: "grammar-domain-verbs",
    topicId: "grammar-topic-verb-kinds",
    difficulty: "foundational",
    prerequisites: ["grammar-verb-action"],
    understand: "The main verb holds meaning; helpers sit beside it to show time or voice.",
    ableToDo: "Split helping and main verbs in a verb group.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "Auxiliary Verbs" },
    grammarInUse: { level: "essential", unitTheme: "Be, have, do as helpers" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "In is running, running is the main verb; is helps.",
        ableToDo: "Name the main verb and a common helper.",
        skills: [
          { title: "Find main", ableToDo: "Identify the main verb in a group" },
          { title: "Name helper", ableToDo: "Point to is/have/will as a helper" },
        ],
        catalogueConceptIds: ["english-verb-main", "english-verb-helping"],
        lessonHost: hosted(G4_HOST.fit, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Helpers and mains team up across tenses.",
        ableToDo: "Split helper and main in longer verb groups.",
        skills: [
          { title: "Split group", ableToDo: "Label helping and main verbs" },
        ],
        catalogueConceptIds: ["english-verb-main", "english-verb-helping"],
        lessonHost: hosted(G5_HOST.vocation, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-verb-irregular",
    title: "Regular & Irregular Verbs",
    domainId: "grammar-domain-verbs",
    topicId: "grammar-topic-verb-kinds",
    difficulty: "developing",
    prerequisites: ["grammar-verb-action"],
    understand: "Regular verbs add -ed; irregular verbs change in their own ways.",
    ableToDo: "Form regular -ed pasts and common irregular pasts.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "Strong and Weak Verbs" },
    grammarInUse: { level: "basic", unitTheme: "Irregular past forms" },
    slices: [
      {
        grade: 5,
        difficulty: "developing",
        understand: "Go/went and eat/ate do not take -ed.",
        ableToDo: "Use common irregular past forms in a short story.",
        skills: [
          { title: "Irregular past", ableToDo: "Use went/saw/ate correctly" },
        ],
        catalogueConceptIds: ["english-verb-irregular"],
        lessonHost: hosted(G5_HOST.vocation, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "A growing bank of irregulars supports past and perfect forms.",
        ableToDo: "Choose regular vs irregular past forms accurately.",
        skills: [
          { title: "Choose form", ableToDo: "Pick the correct past of a common verb" },
        ],
        catalogueConceptIds: ["english-verb-irregular"],
        lessonHost: hosted(G6_HOST.yoga, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-verb-state",
    title: "Being & Sensing Verbs",
    domainId: "grammar-domain-verbs",
    topicId: "grammar-topic-verb-kinds",
    difficulty: "developing",
    prerequisites: ["grammar-verb-action"],
    understand: "Verbs can name a state — be, seem, feel, look — not only motion.",
    ableToDo: "Recognise being and sensing verbs and contrast them with action verbs.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "Verbs of Incomplete Predication" },
    grammarInUse: { level: "basic", unitTheme: "State verbs" },
    slices: [
      {
        grade: 5,
        difficulty: "developing",
        understand: "Is and seems still do a verb's job.",
        ableToDo: "Spot a being verb and contrast it with an action verb.",
        skills: [
          { title: "Spot state", ableToDo: "Identify a being or sensing verb" },
        ],
        catalogueConceptIds: ["english-verb-state"],
        lessonHost: hosted(G5_HOST.vocation, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "State verbs often prefer simple forms over continuous.",
        ableToDo: "Recognise state verbs in mixed sentences.",
        skills: [
          { title: "Contrast", ableToDo: "Label action vs state in a short text" },
        ],
        catalogueConceptIds: ["english-verb-state"],
        lessonHost: hosted(G6_HOST.yoga, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-sva",
    title: "Subject–Verb Agreement",
    domainId: "grammar-domain-sva",
    topicId: "grammar-topic-sva",
    difficulty: "foundational",
    prerequisites: ["grammar-verb-action", "grammar-subject-finding"],
    understand: "The verb matches the real subject as sentences grow longer.",
    ableToDo: "Make verbs agree with the head subject across phrases and indefinites.",
    lessonStrategy: "standalone",
    wrenMartin: { section: "The Verb", topic: "Agreement of the Verb with the Subject" },
    grammarInUse: { level: "essential", unitTheme: "Present simple — he/she/it forms" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "He/she/it takes -s in simple present; they do not.",
        ableToDo: "Make singular and plural subjects match the verb.",
        skills: [
          { title: "Match singular", ableToDo: "Add -s for he/she/it" },
          { title: "Match plural", ableToDo: "Keep the verb without -s for they" },
        ],
        catalogueConceptIds: ["english-sva-simple"],
        lessonHost: standalone(SVA_GOLD, "ready"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Agreement stays steady as subjects get a little longer.",
        ableToDo: "Keep present-tense verbs matched to the subject.",
        skills: [
          { title: "Keep the match", ableToDo: "Fix a simple agreement slip" },
        ],
        catalogueConceptIds: ["english-sva-simple"],
        lessonHost: standalone(SVA_GOLD, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "The head noun — not a nearby word — owns the verb; slip-ups hide in longer subjects.",
        ableToDo: "Agree with tricky subjects and fix agreement errors.",
        skills: [
          { title: "Find the head", ableToDo: "Locate the real subject before choosing is/are" },
          { title: "Fix a slip", ableToDo: "Correct an agreement error in a longer subject" },
        ],
        catalogueConceptIds: [
          "english-sva-simple",
          "english-sva-tricky",
          "english-err-agree",
        ],
        lessonHost: standalone(SVA_GOLD, "ready"),
      },
      {
        grade: 7,
        difficulty: "secure",
        understand: "Intervening phrases do not change the head subject.",
        ableToDo: "Keep agreement across phrases in setting descriptions.",
        skills: [
          { title: "Across phrases", ableToDo: "Agree the verb with the head, not a nearby noun" },
        ],
        catalogueConceptIds: ["english-g78-sva-phrases"],
        lessonHost: hosted(G7_HOST.tunnel, "ready"),
      },
      {
        grade: 8,
        difficulty: "advanced",
        understand: "Phrases and indefinite pronouns both test careful agreement.",
        ableToDo: "Agree across phrases and with each/everybody/nobody.",
        skills: [
          { title: "Phrase heads", ableToDo: "Match verb to head across of-phrases" },
          { title: "Indefinites", ableToDo: "Use singular verbs with each/everybody/nobody" },
        ],
        catalogueConceptIds: [
          "english-g78-sva-phrases",
          "english-g78-sva-indefinite",
        ],
        lessonHost: hosted(G8_HOST.fifth, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-simple-present",
    title: "Simple Present",
    domainId: "grammar-domain-tenses",
    topicId: "grammar-topic-present",
    difficulty: "foundational",
    prerequisites: ["grammar-verb-action"],
    understand: "Simple present carries habits, facts, and the third-person -s form.",
    ableToDo: "Write habits and facts, and add -s/-es for he/she/it.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "The Simple Present Tense" },
    grammarInUse: { level: "essential", unitTheme: "Present simple for habits" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Habits and truths live in simple present.",
        ableToDo: "Write a habit and a fact in simple present.",
        skills: [
          { title: "Write a habit", ableToDo: "Write a daily routine in simple present" },
          { title: "Write a fact", ableToDo: "Write a general truth in simple present" },
        ],
        catalogueConceptIds: ["english-sp-habits", "english-sp-s-form"],
        lessonHost: hosted(G4_HOST.hekko, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Third person singular takes -s or -es.",
        ableToDo: "Add -s/-es for he, she, it in simple present.",
        skills: [
          { title: "Add -s form", ableToDo: "Add -s or -es for he/she/it" },
        ],
        catalogueConceptIds: ["english-sp-s-form"],
        lessonHost: standalone(SVA_GOLD, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-present-continuous",
    title: "Present Continuous",
    domainId: "grammar-domain-tenses",
    topicId: "grammar-topic-present",
    difficulty: "foundational",
    prerequisites: ["grammar-verb-main-helping"],
    understand: "Am/is/are + -ing paints actions in progress — not every state verb.",
    ableToDo: "Describe now with -ing and avoid continuous with many state verbs.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "The Present Continuous Tense" },
    grammarInUse: { level: "essential", unitTheme: "Present continuous for now" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Right now uses am/is/are + -ing.",
        ableToDo: "Describe an action happening at this moment.",
        skills: [
          { title: "Describe now", ableToDo: "Write am/is/are + -ing for now" },
        ],
        catalogueConceptIds: ["english-pc-now"],
        lessonHost: hosted(G4_HOST.swing, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Know, like, belong often stay simple, not continuous.",
        ableToDo: "Spot a state verb and keep it simple present.",
        skills: [
          { title: "Not every -ing", ableToDo: "Avoid continuous with a common state verb" },
        ],
        catalogueConceptIds: ["english-pc-not-stative"],
        lessonHost: hosted(G5_HOST.vocation, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Choose continuous only when the verb allows progress meaning.",
        ableToDo: "Decide when continuous fits and when it does not.",
        skills: [
          { title: "Choose form", ableToDo: "Pick simple or continuous for a state/action pair" },
        ],
        catalogueConceptIds: ["english-pc-not-stative"],
        lessonHost: hosted(G6_HOST.yoga, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-present-perfect",
    title: "Present Perfect",
    domainId: "grammar-domain-tenses",
    topicId: "grammar-topic-present",
    difficulty: "developing",
    prerequisites: ["grammar-simple-past", "grammar-verb-irregular"],
    understand: "Have/has + past participle links a past action to now.",
    ableToDo: "Use present perfect for present results and common time words.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "The Present Perfect Tense" },
    grammarInUse: { level: "intermediate", unitTheme: "Present perfect vs past simple" },
    slices: [
      {
        grade: 5,
        difficulty: "developing",
        understand: "I have lost my pencil means the result still matters now.",
        ableToDo: "Choose have/has and a past participle for a present effect.",
        skills: [
          { title: "Present effect", ableToDo: "Explain a present result with have/has + participle" },
        ],
        catalogueConceptIds: ["english-pp-link"],
        lessonHost: hosted(G5_HOST.scooter, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Since, for, already, and yet partner with present perfect.",
        ableToDo: "Use present-perfect time words and keep the present link.",
        skills: [
          { title: "Since and for", ableToDo: "Choose since or for with present perfect" },
          { title: "Already/yet", ableToDo: "Place already or yet in a perfect sentence" },
        ],
        catalogueConceptIds: ["english-pp-link", "english-pp-time"],
        lessonHost: hosted(G6_HOST.yoga, "ready"),
      },
      {
        grade: 7,
        difficulty: "secure",
        understand: "Present perfect frames attempts and results that still matter.",
        ableToDo: "Form have/has + participle when the result is present.",
        skills: [
          { title: "Form perfect", ableToDo: "Build have/has + past participle accurately" },
        ],
        catalogueConceptIds: ["english-g78-present-perfect"],
        lessonHost: hosted(
          "ncert-g7-poorvi-brothers-great-invention-core",
          "ready",
        ),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-simple-past",
    title: "Simple Past",
    domainId: "grammar-domain-tenses",
    topicId: "grammar-topic-past",
    difficulty: "foundational",
    prerequisites: ["grammar-verb-action"],
    understand: "Simple past tells finished actions and stories about yesterday.",
    ableToDo: "Form regular -ed pasts and common irregular story verbs.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "The Simple Past Tense" },
    grammarInUse: { level: "essential", unitTheme: "Past simple for finished time" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Most verbs add -ed for yesterday; spelling can double a letter.",
        ableToDo: "Add -ed for regular past and spell common doubles.",
        skills: [
          { title: "Regular past", ableToDo: "Add -ed for a regular past verb" },
          { title: "Irregular bank", ableToDo: "Use went/saw/ate in a short past story" },
        ],
        catalogueConceptIds: ["english-past-regular", "english-past-irregular"],
        lessonHost: hosted(G4_HOST.mountains, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Irregular pasts carry adventure and humour scenes.",
        ableToDo: "Use common irregular past forms in a narrative beat.",
        skills: [
          { title: "Story past", ableToDo: "Tell a short past event with irregular verbs" },
        ],
        catalogueConceptIds: ["english-past-irregular"],
        lessonHost: hosted(G5_HOST.scooter, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-past-continuous",
    title: "Past Continuous",
    domainId: "grammar-domain-tenses",
    topicId: "grammar-topic-past",
    difficulty: "developing",
    prerequisites: ["grammar-simple-past", "grammar-present-continuous"],
    understand: "Was/were + -ing sets a background action that was already underway.",
    ableToDo: "Combine past continuous with simple past for an interruption.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "The Past Continuous Tense" },
    grammarInUse: { level: "basic", unitTheme: "Past continuous for background" },
    slices: [
      {
        grade: 5,
        difficulty: "developing",
        understand: "The longer action uses -ing; the interrupt is simple past.",
        ableToDo: "Build was/were + -ing and add an interruption.",
        skills: [
          { title: "Background", ableToDo: "Write was/were + -ing for a scene" },
        ],
        catalogueConceptIds: ["english-pastc-scene"],
        lessonHost: hosted(G5_HOST.scooter, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Past continuous paints what was already happening.",
        ableToDo: "Combine background and interrupt cleanly.",
        skills: [
          { title: "Interrupt", ableToDo: "Pair past continuous with a simple-past interrupt" },
        ],
        catalogueConceptIds: ["english-pastc-scene"],
        lessonHost: hosted(G6_HOST.yoga, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-past-perfect",
    title: "Past Perfect",
    domainId: "grammar-domain-tenses",
    topicId: "grammar-topic-past",
    difficulty: "secure",
    prerequisites: ["grammar-simple-past", "grammar-present-perfect"],
    understand: "Had + past participle marks the earlier of two past events.",
    ableToDo: "Order two past events with had when the sequence might be unclear.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "The Past Perfect Tense" },
    grammarInUse: { level: "intermediate", unitTheme: "Past perfect for earlier past" },
    slices: [
      {
        grade: 6,
        difficulty: "secure",
        understand: "Had packed is earlier than the taxi came.",
        ableToDo: "Place had + participle on the earlier past.",
        skills: [
          { title: "Earlier past", ableToDo: "Mark which event happened first with had" },
        ],
        catalogueConceptIds: ["english-pastp-order"],
        lessonHost: hosted(G6_HOST.yoga, "ready"),
      },
      {
        grade: 8,
        difficulty: "advanced",
        understand: "Past perfect keeps sequence clear in denser narratives.",
        ableToDo: "Form had + participle for the earlier of two pasts.",
        skills: [
          { title: "Order two pasts", ableToDo: "Rewrite a two-past story with clear had" },
        ],
        catalogueConceptIds: ["english-g78-past-perfect"],
        lessonHost: hosted(G8_HOST.kurien, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-future-forms",
    title: "Future Forms",
    domainId: "grammar-domain-tenses",
    topicId: "grammar-topic-future",
    difficulty: "developing",
    prerequisites: ["grammar-simple-present", "grammar-present-continuous"],
    understand: "Will, going to, and present continuous each colour a different future meaning.",
    ableToDo: "Choose will, going to, or present continuous for plans and arrangements.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "Future Time" },
    grammarInUse: { level: "basic", unitTheme: "Will, going to, and arrangements" },
    slices: [
      {
        grade: 5,
        difficulty: "developing",
        understand: "Will often decides or predicts; going to shows a plan or evidence.",
        ableToDo: "Choose will or going to with a reason.",
        skills: [
          { title: "Will or going to", ableToDo: "Pick will or going to for a situation" },
        ],
        catalogueConceptIds: ["english-fut-will"],
        lessonHost: hosted(G5_HOST.vocation, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Present continuous can mark a diary arrangement already set.",
        ableToDo: "Use will/going to and present continuous for set plans.",
        skills: [
          { title: "Arrangement", ableToDo: "Write a future arrangement with present continuous" },
          { title: "Plan vs promise", ableToDo: "Contrast going to with will" },
        ],
        catalogueConceptIds: ["english-fut-will", "english-fut-arrange"],
        lessonHost: hosted(G6_HOST.bharat, "ready"),
      },
      {
        grade: 7,
        difficulty: "secure",
        understand: "Travel and plans need the future form that matches intention.",
        ableToDo: "Talk about plans with clear future forms.",
        skills: [
          { title: "Travel future", ableToDo: "Write a plan and a promise with different forms" },
        ],
        catalogueConceptIds: ["english-g78-future-forms"],
        lessonHost: hosted(
          "ncert-g7-poorvi-north-south-east-west-core",
          "ready",
        ),
      },
      {
        grade: 8,
        difficulty: "advanced",
        understand: "Control will, going to, and arrangement forms in denser writing.",
        ableToDo: "Choose among future forms for meaning, not habit.",
        skills: [
          { title: "Choose future", ableToDo: "Select the future form that fits the meaning" },
        ],
        catalogueConceptIds: ["english-g78-future-forms"],
        lessonHost: hosted(G8_HOST.wonders, "planned"),
      },
    ],
  }),
];
