import {
  defineGrammarConcept,
  hosted,
  G4_HOST,
  G5_HOST,
  G6_HOST,
  G7_HOST,
  G8_HOST,
} from "@/content/grammar/define";

export const VOICE_SPEECH_USAGE_CONCEPTS = [
  defineGrammarConcept({
    id: "grammar-voice",
    title: "Active & Passive Voice",
    domainId: "grammar-domain-voice",
    topicId: "grammar-topic-voice",
    difficulty: "developing",
    prerequisites: ["grammar-verb-main-helping", "grammar-objects"],
    understand: "Voice chooses whether the doer or the receiver leads the sentence.",
    ableToDo: "Form active and passive and choose which fits the purpose.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "Active and Passive Voice" },
    grammarInUse: { level: "intermediate", unitTheme: "Passive with be + past participle" },
    slices: [
      {
        grade: 6,
        difficulty: "developing",
        understand: "Active names the doer; passive puts the receiver first.",
        ableToDo: "Write clear active sentences and form a simple passive.",
        skills: [
          { title: "Active", ableToDo: "Write an active sentence naming the doer" },
          { title: "Passive form", ableToDo: "Form was/were + past participle" },
        ],
        catalogueConceptIds: ["english-voice-active", "english-voice-passive"],
        lessonHost: hosted(G6_HOST.winner, "ready"),
      },
      {
        grade: 7,
        difficulty: "secure",
        understand: "Passive keeps tense with be + past participle.",
        ableToDo: "Form a respectful passive line accurately.",
        skills: [
          { title: "Form passive", ableToDo: "Turn an active line into a past passive" },
        ],
        catalogueConceptIds: ["english-g78-voice-form"],
        lessonHost: hosted(G7_HOST.homage, "ready"),
      },
      {
        grade: 8,
        difficulty: "advanced",
        understand: "Choose active for clarity and passive when the process or unknown doer matters.",
        ableToDo: "Choose voice to fit science, news, or clear storytelling.",
        skills: [
          { title: "Choose voice", ableToDo: "Decide active or passive for purpose" },
        ],
        catalogueConceptIds: ["english-g78-voice-choose"],
        lessonHost: hosted(G8_HOST.valour, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-speech",
    title: "Direct & Indirect Speech",
    domainId: "grammar-domain-speech",
    topicId: "grammar-topic-speech",
    difficulty: "developing",
    prerequisites: ["grammar-sentence-basics", "grammar-simple-past"],
    understand: "We can quote exact words or report them with pronoun and tense shifts.",
    ableToDo: "Punctuate direct speech and report statements, questions, and commands.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "Direct and Indirect Speech", topic: "Reporting Speech" },
    grammarInUse: { level: "intermediate", unitTheme: "Reported statements, questions, commands" },
    slices: [
      {
        grade: 5,
        difficulty: "developing",
        understand: "Quotation marks hug the spoken words; a capital starts the quote.",
        ableToDo: "Punctuate a speaker's exact words.",
        skills: [
          { title: "Direct quote", ableToDo: "Place quotation marks and the opening capital" },
        ],
        catalogueConceptIds: ["english-speech-direct"],
        lessonHost: hosted(G5_HOST.gilli, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Reporting often shifts pronoun and present tense after a past saying verb.",
        ableToDo: "Punctuate direct speech and report without quotation marks.",
        skills: [
          { title: "Direct marks", ableToDo: "Punctuate a quoted line" },
          { title: "Report statement", ableToDo: "Change pronoun and shift tense in report" },
        ],
        catalogueConceptIds: ["english-speech-direct", "english-speech-indirect"],
        lessonHost: hosted(G6_HOST.raven, "ready"),
      },
      {
        grade: 7,
        difficulty: "secure",
        understand: "Reported statements keep meaning while shifting form.",
        ableToDo: "Report a statement with pronoun and tense shifts.",
        skills: [
          { title: "Report said", ableToDo: "Turn a quoted statement into indirect speech" },
        ],
        catalogueConceptIds: ["english-g78-speech-statements"],
        lessonHost: hosted(G7_HOST.soldiers, "ready"),
      },
      {
        grade: 8,
        difficulty: "advanced",
        understand: "Reported questions lose question order; commands use to / not to.",
        ableToDo: "Report yes/no and wh- questions and commands accurately.",
        skills: [
          { title: "Report question", ableToDo: "Report a yes/no or wh- question" },
          { title: "Report command", ableToDo: "Report a command with tell/ask + to" },
        ],
        catalogueConceptIds: [
          "english-g78-speech-questions",
          "english-g78-speech-commands",
        ],
        lessonHost: hosted(G8_HOST.cherry, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-conditionals",
    title: "Conditionals",
    domainId: "grammar-domain-conditionals",
    topicId: "grammar-topic-conditionals",
    difficulty: "developing",
    prerequisites: ["grammar-complex-sentences", "grammar-future-forms"],
    understand: "If-patterns show real results and imaginary situations.",
    ableToDo: "Write zero/first conditionals and unreal if + would patterns.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Conjunction", topic: "Conditional Sentences" },
    grammarInUse: { level: "intermediate", unitTheme: "Real and unreal conditionals" },
    slices: [
      {
        grade: 5,
        difficulty: "developing",
        understand: "If + present, will for a likely future; facts can stay present/present.",
        ableToDo: "Write a first conditional and a fact condition.",
        skills: [
          { title: "Real if", ableToDo: "Write if + present, will for a real result" },
        ],
        catalogueConceptIds: ["english-cond-zero-first"],
        lessonHost: hosted(G5_HOST.parrot, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Past forms in if can signal imaginary present/future, not past time.",
        ableToDo: "Write real and unreal conditionals with would.",
        skills: [
          { title: "Real condition", ableToDo: "Write a zero or first conditional" },
          { title: "Imaginary if", ableToDo: "Write an unreal if with would" },
        ],
        catalogueConceptIds: [
          "english-cond-zero-first",
          "english-cond-unreal",
        ],
        lessonHost: hosted(G6_HOST.heart, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-gerunds",
    title: "Gerunds as Nouns",
    domainId: "grammar-domain-non-finite",
    topicId: "grammar-topic-non-finite",
    difficulty: "advanced",
    prerequisites: ["grammar-noun-phrases", "grammar-verb-action"],
    understand: "An -ing form can name an activity (a gerund) or build a progressive verb.",
    ableToDo: "Spot gerunds that name activities and contrast them with progressive verbs.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "The Verb", topic: "Gerunds" },
    grammarInUse: { level: "intermediate", unitTheme: "Gerunds as subjects and objects" },
    slices: [
      {
        grade: 8,
        difficulty: "advanced",
        understand: "Running helps you — running names the activity.",
        ableToDo: "Recognise gerunds and contrast with is running.",
        skills: [
          { title: "Spot gerund", ableToDo: "Identify an -ing form used as a noun" },
          { title: "Contrast verb", ableToDo: "Contrast a gerund with a progressive verb" },
        ],
        catalogueConceptIds: ["english-g78-gerunds"],
        lessonHost: hosted(G8_HOST.wit, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-punctuation",
    title: "Punctuation",
    domainId: "grammar-domain-punctuation",
    topicId: "grammar-topic-punctuation",
    difficulty: "foundational",
    prerequisites: ["grammar-sentence-basics"],
    understand: "Punctuation is the traffic system of writing — from end marks to semicolons.",
    ableToDo: "Choose end marks, commas, apostrophes, quotation punctuation, and semicolons/colons.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "Punctuation", topic: "Stops, Commas, and Apostrophes" },
    grammarInUse: { level: "essential", unitTheme: "End marks through semicolons" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Statements, questions, and strong feeling take different end marks; commas help lists.",
        ableToDo: "Choose end marks and use commas in lists.",
        skills: [
          { title: "End marks", ableToDo: "End a statement or question correctly" },
          { title: "List commas", ableToDo: "Punctuate a short list with commas" },
        ],
        catalogueConceptIds: ["english-punct-end", "english-punct-comma"],
        lessonHost: hosted(G4_HOST.maheshwar, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Commas pause after openers; apostrophes mark possession and contractions.",
        ableToDo: "Use commas and apostrophes accurately.",
        skills: [
          { title: "Comma pause", ableToDo: "Use a comma after a fronted phrase or in a list" },
          { title: "Apostrophe", ableToDo: "Write a contraction and a possessive" },
        ],
        catalogueConceptIds: [
          "english-punct-comma",
          "english-punct-apostrophe",
        ],
        lessonHost: hosted(G5_HOST.panchayat, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "It's means it is; possessives and contractions must not blur.",
        ableToDo: "Use apostrophes for possession and contractions carefully.",
        skills: [
          { title: "Apostrophe craft", ableToDo: "Choose contraction vs possessive apostrophe use" },
        ],
        catalogueConceptIds: ["english-punct-apostrophe"],
        lessonHost: hosted(G6_HOST.bharat, "ready"),
      },
      {
        grade: 7,
        difficulty: "secure",
        understand: "Quoted speech needs comma, capital, and marks in the right places.",
        ableToDo: "Punctuate direct speech accurately.",
        skills: [
          { title: "Quote marks", ableToDo: "Place quotation marks and the comma before the quote" },
        ],
        catalogueConceptIds: ["english-g78-speech-punct"],
        lessonHost: hosted(G7_HOST.say, "ready"),
      },
      {
        grade: 8,
        difficulty: "advanced",
        understand: "Semicolons join related independents; colons introduce.",
        ableToDo: "Join with a semicolon and introduce with a colon.",
        skills: [
          { title: "Semicolon", ableToDo: "Join two related independents with a semicolon" },
          { title: "Colon", ableToDo: "Introduce a list or explanation with a colon" },
        ],
        catalogueConceptIds: ["english-g78-semi-colon"],
        lessonHost: hosted(G8_HOST.concrete, "planned"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-capitalization",
    title: "Capitalization",
    domainId: "grammar-domain-capitalization",
    topicId: "grammar-topic-capitalization",
    difficulty: "foundational",
    understand: "Capitals mark sentence starts, the pronoun I, names, titles, and places.",
    ableToDo: "Capitalise starts, I, names, titles, and place names.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "Punctuation", topic: "Capital Letters" },
    grammarInUse: { level: "essential", unitTheme: "Capitals for starts and names" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "First word, I, and proper nouns take capitals; titles and places too.",
        ableToDo: "Capitalise sentence starts, I, names, titles, and places.",
        skills: [
          { title: "Start and I", ableToDo: "Capitalise a sentence start and the word I" },
          { title: "Titles places", ableToDo: "Capitalise important words in titles and places" },
        ],
        catalogueConceptIds: ["english-cap-start", "english-cap-titles"],
        lessonHost: hosted(G4_HOST.braille, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "Book titles and place names keep their capital patterns.",
        ableToDo: "Capitalise titles and places consistently.",
        skills: [
          { title: "Title caps", ableToDo: "Capitalise a book or story title" },
        ],
        catalogueConceptIds: ["english-cap-titles"],
        lessonHost: hosted(G5_HOST.panchayat, "ready"),
      },
    ],
  }),

  defineGrammarConcept({
    id: "grammar-usage-editing",
    title: "Usage & Editing",
    domainId: "grammar-domain-usage-editing",
    topicId: "grammar-topic-usage",
    difficulty: "foundational",
    prerequisites: ["grammar-pro-possessive"],
    understand: "A few mix-ups show up again and again — careful revision catches them.",
    ableToDo: "Choose their/there/they're, your/you're, and its/it's correctly.",
    lessonStrategy: "hosted",
    wrenMartin: { section: "Common Errors", topic: "Confusable Words" },
    grammarInUse: { level: "essential", unitTheme: "Homophones and common mix-ups" },
    slices: [
      {
        grade: 4,
        difficulty: "foundational",
        understand: "Their owns; there is a place; they're means they are — your vs you're too.",
        ableToDo: "Choose their/there/they're and your/you're.",
        skills: [
          { title: "Their trio", ableToDo: "Pick their, there, or they're" },
          { title: "Your pair", ableToDo: "Pick your or you're" },
        ],
        catalogueConceptIds: ["english-err-their", "english-err-your"],
        lessonHost: hosted(G4_HOST.smart, "planned"),
      },
      {
        grade: 5,
        difficulty: "developing",
        understand: "It's = it is; its = belonging to it — plus the earlier homophone pairs.",
        ableToDo: "Choose their/there/they're, your/you're, and its/it's.",
        skills: [
          { title: "Homophone set", ableToDo: "Choose among the common mix-up pairs" },
          { title: "Its/it's", ableToDo: "Pick its or it's" },
        ],
        catalogueConceptIds: [
          "english-err-their",
          "english-err-your",
          "english-err-its",
        ],
        lessonHost: hosted(G5_HOST.spectacles, "ready"),
      },
      {
        grade: 6,
        difficulty: "secure",
        understand: "Its/it's slips hide in fast drafting.",
        ableToDo: "Choose its and it's under light editing pressure.",
        skills: [
          { title: "Its check", ableToDo: "Fix its/it's in a short paragraph" },
        ],
        catalogueConceptIds: ["english-err-its"],
        lessonHost: hosted(G6_HOST.kites, "ready"),
      },
    ],
  }),
];
