import type { Grade5EnglishConceptId } from "@/content/lessons/grade-5-english/format";

export const GRADE_5_ENGLISH_SPINE_KINDS = ["taught", "overlap"] as const;
export type Grade5EnglishSpineKind = (typeof GRADE_5_ENGLISH_SPINE_KINDS)[number];

export type Grade5EnglishLessonHostId =
  | Grade5EnglishConceptId
  | "english-sva-simple";

export type Grade5EnglishSpineCoverage = {
  id: string;
  title: string;
  kind: Grade5EnglishSpineKind;
  hostConceptId: Grade5EnglishLessonHostId;
  objective: string;
};

/**
 * Audit of every Grade 5-visible English skill-spine concept except
 * Match Singular & Plural (gold lesson) and official Santoor chapter cores.
 */
export const GRADE_5_ENGLISH_SPINE_COVERAGE: Grade5EnglishSpineCoverage[] = [
  {
    id: "english-sp-s-form",
    title: "The -s Form",
    kind: "taught",
    hostConceptId: "english-sva-simple",
    objective: "Use the -s form so a singular subject and verb match in a short sentence.",
  },
  {
    id: "english-sub-complete",
    title: "Complete Subject & Predicate",
    kind: "taught",
    hostConceptId: "english-sva-simple",
    objective: "Name a complete subject and predicate that can stand as a full sentence.",
  },
  {
    id: "english-ch-traits",
    title: "Traits From Actions",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-papas-spectacles-core",
    objective: "Infer a character trait from what someone does in a funny mix-up.",
  },
  {
    id: "english-plot-problem",
    title: "Problem & Attempts",
    kind: "overlap",
    hostConceptId: "ncert-g5-santoor-papas-spectacles-core",
    objective: "Name the problem and the attempts that follow in a short story.",
  },
  {
    id: "english-nar-arc",
    title: "Beginning, Middle, End",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-papas-spectacles-core",
    objective: "Retell beginning, middle, and end of a humour story in order.",
  },
  {
    id: "english-inf-clues",
    title: "Clues + What You Know",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-papas-spectacles-core",
    objective: "Use text clues plus what you know to explain a mix-up.",
  },
  {
    id: "english-comp-q",
    title: "Answering From the Text",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-papas-spectacles-core",
    objective: "Answer a question using evidence from the humour passage.",
  },
  {
    id: "english-tell-voice",
    title: "Tell It Aloud",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-papas-spectacles-core",
    objective: "Tell the funny mix-up aloud so a listener can follow.",
  },
  {
    id: "english-diary-voice",
    title: "Dear Diary",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-papas-spectacles-core",
    objective: "Write a short diary line in a character’s voice after the mix-up.",
  },
  {
    id: "english-story-dialogue",
    title: "Dialogue That Moves the Story",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-papas-spectacles-core",
    objective: "Write dialogue that moves the humour scene forward.",
  },
  {
    id: "english-err-their",
    title: "Their, There, They're",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-papas-spectacles-core",
    objective: "Choose their, there, or they’re for the meaning you need.",
  },
  {
    id: "english-err-your",
    title: "Your & You're",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-papas-spectacles-core",
    objective: "Choose your or you’re for the meaning you need.",
  },
  {
    id: "english-err-its",
    title: "Its & It's",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-papas-spectacles-core",
    objective: "Choose its or it’s for the meaning you need.",
  },
  {
    id: "english-ch-change",
    title: "How Characters Change",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gone-with-the-scooter-core",
    objective: "Describe how a character changes across a scooter adventure.",
  },
  {
    id: "english-plot-turn",
    title: "Turning Point",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gone-with-the-scooter-core",
    objective: "Find the turning point when events suddenly shift.",
  },
  {
    id: "english-list-detail",
    title: "Important Details",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gone-with-the-scooter-core",
    objective: "Pick details that matter for sequencing the chase.",
  },
  {
    id: "english-notice-facts",
    title: "Who, What, When, Where",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gone-with-the-scooter-core",
    objective: "Note who, what, when, and where in the scooter events.",
  },
  {
    id: "english-sum-short",
    title: "Short & Faithful",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gone-with-the-scooter-core",
    objective: "Write a short, faithful summary of the adventure.",
  },
  {
    id: "english-main-vs-topic",
    title: "Topic vs Main Idea",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gone-with-the-scooter-core",
    objective: "Tell the topic from the main idea of the scooter story.",
  },
  {
    id: "english-det-support",
    title: "Details That Earn Their Place",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gone-with-the-scooter-core",
    objective: "Choose details that earn their place in a retelling.",
  },
  {
    id: "english-past-irregular",
    title: "Irregular Past Stories",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gone-with-the-scooter-core",
    objective: "Use irregular past verbs when retelling what happened.",
  },
  {
    id: "english-pastc-scene",
    title: "Background Action",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gone-with-the-scooter-core",
    objective: "Describe background action while a main event unfolds.",
  },
  {
    id: "english-pp-link",
    title: "Past With a Present Effect",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gone-with-the-scooter-core",
    objective: "Link a past event to a present effect in the story.",
  },
  {
    id: "english-desc-senses",
    title: "Show With Senses",
    kind: "overlap",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Show a rainbow or sky scene with sensory words.",
  },
  {
    id: "english-cre-image",
    title: "Fresh Images",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Create a fresh image that helps a reader see the rainbow.",
  },
  {
    id: "english-rv-passage",
    title: "Words Inside a Passage",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Find what a word means from how it is used in the poem.",
  },
  {
    id: "english-ctx-guess",
    title: "Guessing From the Sentence",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Guess a word’s meaning from the sentence around it.",
  },
  {
    id: "english-ctx-check",
    title: "Checking a Guess",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Check a meaning guess against the next lines.",
  },
  {
    id: "english-voc-fit",
    title: "The Meaning That Fits",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Choose the meaning that fits the rainbow context.",
  },
  {
    id: "english-syn-shade",
    title: "Shades of Meaning",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Pick a synonym with the right shade for a vivid image.",
  },
  {
    id: "english-idiom-meaning",
    title: "Not Word-by-Word",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Explain an idiom by sense, not word-by-word.",
  },
  {
    id: "english-homonym-bat",
    title: "Same Word, Different Meaning",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Tell two meanings of the same word from context.",
  },
  {
    id: "english-homo-pairs",
    title: "Sound-Alike Pairs",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Choose the right sound-alike word for a sky description.",
  },
  {
    id: "english-adj-order",
    title: "Adjective Order",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Order adjectives naturally in a descriptive phrase.",
  },
  {
    id: "english-deg-er-est",
    title: "-er & -est",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Use -er and -est to compare colours or brightness.",
  },
  {
    id: "english-deg-more-most",
    title: "More & Most",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Use more and most when -er/-est does not fit.",
  },
  {
    id: "english-adv-how",
    title: "How, When, Where",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Add how, when, or where to sharpen an observation.",
  },
  {
    id: "english-adv-degree",
    title: "Very, Too, Enough",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-rainbow-core",
    objective: "Use very, too, or enough carefully in a description.",
  },
  {
    id: "english-theme-idea",
    title: "A Lesson Without Preaching",
    kind: "overlap",
    hostConceptId: "ncert-g5-santoor-the-wise-parrot-core",
    objective: "State a lesson the wise-parrot tale suggests without preaching.",
  },
  {
    id: "english-prov-lesson",
    title: "A Lesson in a Line",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-wise-parrot-core",
    objective: "Connect a proverb-like line to the tale’s suggestion.",
  },
  {
    id: "english-ce-because",
    title: "Because & So in Texts",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-wise-parrot-core",
    objective: "Trace because-and-so links in the turning point.",
  },
  {
    id: "english-op-because",
    title: "Opinion + Reasons",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-wise-parrot-core",
    objective: "Give an opinion about the tale with a clear reason.",
  },
  {
    id: "english-cc-alike",
    title: "Alike & Different",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-wise-parrot-core",
    objective: "Say how two characters or choices are alike or different.",
  },
  {
    id: "english-fo-sort",
    title: "Checkable vs Personal",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-wise-parrot-core",
    objective: "Sort checkable story facts from personal opinions.",
  },
  {
    id: "english-conj-because-so",
    title: "Because & So",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-wise-parrot-core",
    objective: "Join ideas with because or so in a retell sentence.",
  },
  {
    id: "english-conj-although",
    title: "Although & If",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-wise-parrot-core",
    objective: "Use although or if to show a twist in the tale.",
  },
  {
    id: "english-cpx-when",
    title: "When, Because, If, Although",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-wise-parrot-core",
    objective: "Build a complex sentence with when, because, if, or although.",
  },
  {
    id: "english-cond-zero-first",
    title: "Real Conditions",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-wise-parrot-core",
    objective: "Talk about a real condition the characters face.",
  },
  {
    id: "english-mod-can",
    title: "Can & Could",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-wise-parrot-core",
    objective: "Use can or could for ability or possibility in the tale.",
  },
  {
    id: "english-mod-must-should",
    title: "Must, Should, May",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-wise-parrot-core",
    objective: "Use must, should, or may when judging a wise choice.",
  },
  {
    id: "english-rep-facts",
    title: "Facts Before Flourishes",
    kind: "overlap",
    hostConceptId: "ncert-g5-santoor-the-frog-core",
    objective: "Report frog facts from the text before adding flourishes.",
  },
  {
    id: "english-ap-pie",
    title: "Inform, Entertain, Persuade",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-frog-core",
    objective: "Say whether a frog text aims to inform, entertain, or persuade.",
  },
  {
    id: "english-para-topic",
    title: "Topic Sentence & Details",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-frog-core",
    objective: "Write a topic sentence with supporting frog details.",
  },
  {
    id: "english-para-unity",
    title: "Sticking to One Idea",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-frog-core",
    objective: "Keep one idea in a paragraph when comparing animals.",
  },
  {
    id: "english-ant-grade",
    title: "Not Always Perfect Opposites",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-frog-core",
    objective: "Choose graded opposites carefully when comparing animals.",
  },
  {
    id: "english-nouns-common-proper",
    title: "Common & Proper Nouns",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-frog-core",
    objective: "Tell common nouns from proper names in animal texts.",
  },
  {
    id: "english-nouns-count",
    title: "Countable & Uncountable",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-frog-core",
    objective: "Sort countable and uncountable nouns in a nature note.",
  },
  {
    id: "english-nouns-collective",
    title: "Collective Nouns",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-frog-core",
    objective: "Use a collective noun for a group of animals when it fits.",
  },
  {
    id: "english-nouns-abstract",
    title: "Abstract Nouns",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-frog-core",
    objective: "Spot abstract nouns such as courage or care in a comparison.",
  },
  {
    id: "english-art-the",
    title: "The",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-frog-core",
    objective: "Use the when naming a specific animal or place from the text.",
  },
  {
    id: "english-det-quant",
    title: "Some, Any, Many, Much",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-the-frog-core",
    objective: "Choose some, any, many, or much for animal counts.",
  },
  {
    id: "english-use-clear",
    title: "Say What You Mean",
    kind: "overlap",
    hostConceptId: "ncert-g5-santoor-what-a-tank-core",
    objective: "Say what you mean about water use in clear words.",
  },
  {
    id: "english-use-situation",
    title: "Fit the Situation",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-what-a-tank-core",
    objective: "Fit language to a water-saving or tank situation.",
  },
  {
    id: "english-ins-steps",
    title: "Clear Steps",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-what-a-tank-core",
    objective: "Write clear steps for using or checking a water tank.",
  },
  {
    id: "english-comm-clarity",
    title: "Say It So They Can Do It",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-what-a-tank-core",
    objective: "Give directions so a listener can follow a water task.",
  },
  {
    id: "english-comm-audience",
    title: "Know Your Listener",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-what-a-tank-core",
    objective: "Adjust a water message for the listener you mean.",
  },
  {
    id: "english-pres-plan",
    title: "Opening, Points, Close",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-what-a-tank-core",
    objective: "Plan an opening, points, and close for a tank talk.",
  },
  {
    id: "english-email-clear",
    title: "Subject & Purpose",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-what-a-tank-core",
    objective: "Write a clear subject and purpose for a water note.",
  },
  {
    id: "english-let-formal",
    title: "Formal Letters",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-what-a-tank-core",
    objective: "Draft a short formal line about a shared water need.",
  },
  {
    id: "english-op-speak",
    title: "I Think, I Hear You",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gilli-danda-core",
    objective: "Share an opinion about local play and listen to another view.",
  },
  {
    id: "english-disc-build",
    title: "Building on Ideas",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gilli-danda-core",
    objective: "Build on a classmate’s idea about the game.",
  },
  {
    id: "english-let-informal",
    title: "Friendly Letters",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gilli-danda-core",
    objective: "Write a friendly note about playing gilli danda.",
  },
  {
    id: "english-sent-types",
    title: "Statement, Question, Command, Exclamation",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gilli-danda-core",
    objective: "Use statements, questions, commands, and exclamations in play talk.",
  },
  {
    id: "english-q-wh",
    title: "Wh- Questions",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gilli-danda-core",
    objective: "Ask wh- questions to learn how the game is played.",
  },
  {
    id: "english-sw-vary",
    title: "Varying Sentences",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gilli-danda-core",
    objective: "Vary sentence length when describing a turn in the game.",
  },
  {
    id: "english-neg-double",
    title: "One Negative Is Enough",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gilli-danda-core",
    objective: "Keep one clear negative when explaining a rule.",
  },
  {
    id: "english-speech-direct",
    title: "Direct Speech",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-gilli-danda-core",
    objective: "Write direct speech for players calling a turn.",
  },
  {
    id: "english-essay-plan",
    title: "Plan Then Write",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-decision-of-the-panchayat-core",
    objective: "Plan then write a fair-decision paragraph.",
  },
  {
    id: "english-edit-revise",
    title: "Make It Clearer",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-decision-of-the-panchayat-core",
    objective: "Revise a decision paragraph to make the reason clearer.",
  },
  {
    id: "english-edit-checklist",
    title: "A Writer's Checklist",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-decision-of-the-panchayat-core",
    objective: "Use a short writer’s checklist before sharing a decision.",
  },
  {
    id: "english-comp-fanboys",
    title: "Joining With And, But, Or, So",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-decision-of-the-panchayat-core",
    objective: "Join decision ideas with and, but, or, or so.",
  },
  {
    id: "english-comp-comma",
    title: "Avoiding Run-ons",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-decision-of-the-panchayat-core",
    objective: "Avoid run-ons when explaining a panchayat choice.",
  },
  {
    id: "english-cl-independent",
    title: "Independent Clauses",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-decision-of-the-panchayat-core",
    objective: "Write an independent clause that states the problem clearly.",
  },
  {
    id: "english-punct-comma",
    title: "Commas",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-decision-of-the-panchayat-core",
    objective: "Place commas so a fair-decision sentence reads smoothly.",
  },
  {
    id: "english-punct-apostrophe",
    title: "Apostrophes",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-decision-of-the-panchayat-core",
    objective: "Use apostrophes for possession in names and places.",
  },
  {
    id: "english-cap-titles",
    title: "Titles & Places",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-decision-of-the-panchayat-core",
    objective: "Capitalise titles and place names in a village decision.",
  },
  {
    id: "english-verb-main",
    title: "Main Verbs",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-vocation-core",
    objective: "Find the main verb in a wish or vocation stanza.",
  },
  {
    id: "english-verb-helping",
    title: "Helping Verbs",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-vocation-core",
    objective: "Spot a helping verb that supports the main verb.",
  },
  {
    id: "english-verb-irregular",
    title: "Regular & Irregular Verbs",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-vocation-core",
    objective: "Use regular and irregular verbs when speaking a wish.",
  },
  {
    id: "english-verb-state",
    title: "Being & Sensing Verbs",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-vocation-core",
    objective: "Notice being and sensing verbs in the speaker’s wish.",
  },
  {
    id: "english-pc-not-stative",
    title: "Not Every Verb -ing",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-vocation-core",
    objective: "Avoid forcing -ing on verbs that do not take it well.",
  },
  {
    id: "english-fut-will",
    title: "Will & Going To",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-vocation-core",
    objective: "Use will or going to for a future wish the speaker voices.",
  },
  {
    id: "english-pro-possessive",
    title: "Possessive Pronouns",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-vocation-core",
    objective: "Use possessive pronouns when naming whose work it is.",
  },
  {
    id: "english-pro-reflexive",
    title: "Reflexive Pronouns",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-vocation-core",
    objective: "Use a reflexive pronoun when the speaker acts on themselves.",
  },
  {
    id: "english-obj-direct",
    title: "Direct Objects",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-vocation-core",
    objective: "Find the direct object of a wish verb in a line.",
  },
  {
    id: "english-phr-prep",
    title: "Prepositional Phrases",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-vocation-core",
    objective: "Read a prepositional phrase that places the vocation scene.",
  },
  {
    id: "english-prep-time",
    title: "Time: at, on, in",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-vocation-core",
    objective: "Use at, on, or in for time in a day’s-work wish.",
  },
  {
    id: "english-prep-other",
    title: "For, With, From, About",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-vocation-core",
    objective: "Use for, with, from, or about in vocation talk.",
  },
  {
    id: "english-pre-un-re",
    title: "Un-, Re-, Dis-",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-glass-bangles-core",
    objective: "Use un-, re-, or dis- to build process words carefully.",
  },
  {
    id: "english-pre-pre-mis",
    title: "Pre-, Mis-, Over-",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-glass-bangles-core",
    objective: "Use pre-, mis-, or over- when naming a making step.",
  },
  {
    id: "english-suf-ly-ful",
    title: "-ly, -ful, -less",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-glass-bangles-core",
    objective: "Add -ly, -ful, or -less to describe craft work.",
  },
  {
    id: "english-suf-tion-er",
    title: "-tion, -er, -ness",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-glass-bangles-core",
    objective: "Use -tion, -er, or -ness for craft nouns.",
  },
  {
    id: "english-root-family",
    title: "Finding the Root",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-glass-bangles-core",
    objective: "Find the root in words about making glass bangles.",
  },
  {
    id: "english-fam-pattern",
    title: "Families That Rhyme or Share a Root",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-glass-bangles-core",
    objective: "Notice word families that share a root or sound pattern.",
  },
  {
    id: "english-spell-tricky",
    title: "Tricky High-Frequency Words",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-glass-bangles-core",
    objective: "Spell tricky high-frequency words in a process note.",
  },
  {
    id: "english-nouns-possessive",
    title: "Possessive Nouns",
    kind: "taught",
    hostConceptId: "ncert-g5-santoor-glass-bangles-core",
    objective: "Form possessive nouns for a maker’s tools or bangles.",
  },
];

const coverageById = new Map(
  GRADE_5_ENGLISH_SPINE_COVERAGE.map((row) => [row.id, row]),
);

export function getGrade5EnglishSpineCoverage(conceptId: string) {
  return coverageById.get(conceptId);
}

export function getGrade5EnglishHostConceptId(conceptId: string) {
  return coverageById.get(conceptId)?.hostConceptId;
}

export function skillsHostedByGrade5English(hostConceptId: string): string[] {
  return GRADE_5_ENGLISH_SPINE_COVERAGE.filter(
    (row) => row.hostConceptId === hostConceptId,
  ).map((row) => row.id);
}

export function grade5EnglishSpineCoverageAudit() {
  const taught = GRADE_5_ENGLISH_SPINE_COVERAGE.filter((row) => row.kind === "taught");
  const overlap = GRADE_5_ENGLISH_SPINE_COVERAGE.filter(
    (row) => row.kind === "overlap",
  );
  return {
    spineItems: GRADE_5_ENGLISH_SPINE_COVERAGE.length,
    taughtCount: taught.length,
    overlapCount: overlap.length,
    taughtIds: taught.map((row) => row.id),
    overlapIds: overlap.map((row) => row.id),
    connectedIds: GRADE_5_ENGLISH_SPINE_COVERAGE.map((row) => row.id),
  };
}
